{
  "hash": "563710897032b69813a38b2bad1522f0",
  "result": {
    "markdown": "---\ntitle: \"Class Project Erika Nagai\"\nauthor: \"Erika Nagai\"\ndesription: \"Class Project - Japanese movie-goers trend in last 20 years\"\ndate: \"08/08/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - final project\n  - Erika Nagai\n  - dplyr\n  - movies\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(ggplot2)\n#install.packages(\"gridExtra\")\nlibrary(gridExtra)\nlibrary(AER)\nlibrary(stargazer)\nlibrary(stringr)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Overview:\n\nThis analysis was done for in-class assignment for DACSS 603 Introduction to Quantitative Analysis at the University of Massachusetts, Amherst.\n\nMy analysis is about Japanese moviegoers' behavior and trend over last 20 years. As this article (https://www.washingtonpost.com/business/avatar-struggles-show-how-japan-is-ditching-hollywood/2022/12/22/09197536-8234-11ed-8738-ed7217de2775_story.html) suggests, recent Hollywood movies are struggling in Japanese market. This might suggest that Japanese people are favoring domestic movies because they are getting more close-minded or Japanese movie industry is getting mature and more attractive for Japanese audience.\n\nMy research questions are: - How has Japanese movie-going behavior change for last 20 years? - Are Japanese movies getting more popular among Japanese moviegoers? - Are foreign movies getting less popular among Japanese moviegoers?\n\n## Dataset\n\nI used two datasets from two different sources.\n\n1.  By-year dataset (year) I gathered the data about general information (total box office revenue, total \\# of people who went to movie theaters, \\# of screens) of every year from 2000 to 2022 from this [website](http://www.eiren.org/statistics_e/index.html).\n\n2.  By-movie dataset ('ranking') I gathered the data of Top 100 movies in box office revenue in Japan for the last 20 years (2002-2022) by scraping data available on Box Office Mojo by [IMDbPro](https://www.boxofficemojo.com/year/2022/?area=JP&grossesOption=totalGrosses&sort=rank&sortDir=asc)\n\nThen, I added more detailed information about the movies using the dataset of movies available on [TMdb](https://www.kaggle.com/datasets/akshaypawar7/millions-of-movies) as of July 14th, 2023 to complement useful information on movies' language and genres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear <- read_csv(\"data_ErikaNagai/revised_year.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nNew names:\nRows: 23 Columns: 15\n── Column specification\n──────────────────────────────────────────────────────── Delimiter: \",\" dbl\n(15): ...1, year, total_screens, jp_movies, foreign_movies, total_movies...\nℹ Use `spec()` to retrieve the full column specification for this data. ℹ\nSpecify the column types or set `show_col_types = FALSE` to quiet this message.\n• `` -> `...1`\n```\n:::\n\n```{.r .cell-code}\nranking <- read_csv(\"data_ErikaNagai/merged_ranking.csv\") \n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 3463 Columns: 35\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (17): original_title, release_date, distributor, revised_release_date, r...\ndbl (17): year, rank, gross, total_gross, order, release_year, id, JP_releas...\nlgl  (1): re_released\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\nranking$anime <- as.factor(ranking$anime)\n```\n:::\n\n\n## Exploratory Analysis\n\n### How did Japanese moviegoers' taste change?\n\n**The year 2008 marks a significant turning point in the trend of moviegoing in Japan. Before 2008, foreign films were more popular and generated higher box office revenues compared to domestic films. However, from 2008 onwards, the situation changed, and Japanese films started to dominate in terms of box office earnings.**\n\nIn 2020, the COVID-19 pandemic impacted both Japanese and foreign films, resulting in reduced box office revenues. However, the decline in box office revenue for foreign films was significantly greater than that of Japanese films.\n\nAfter 2020, Japanese films gradually recovered their box office revenue to pre-pandemic levels, and in 2022, they recorded the second-highest box office revenue in the past 20 years. On the other hand, the box office revenue for foreign films is yet to return to its pre-pandemic levels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear %>%\n  select(c('year', 'jp_revenue', 'foreign_revenue')) %>%\n  pivot_longer(cols=c('jp_revenue', 'foreign_revenue'), names_to = 'Original region of movies', values_to = 'revenue') %>%\n  ggplot(aes(x=year, y=revenue, color=`Original region of movies`)) +\n  geom_line() +\n  scale_color_manual(values = c('coral', 'darkturquoise'), labels=c(\"Foreign Movies\", \"Japanese Movies\")) +\n  labs(y=\"Box Office Revenue in Japan\")\n```\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe exact reason for the shift in Japanese audiences' preference from foreign films to Japanese films is not fully understood. However, it seems that the increase in the number of domestically produced films alone is **not** be the sole cause. This is because the number of foreign films being screened in Japanese cinemas has also increased over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nyear %>%\n  select(c('year', 'jp_movies', 'foreign_movies')) %>%\n  pivot_longer(cols=c('jp_movies', 'foreign_movies'), names_to = 'Original region of movies', values_to = 'number_movies') %>%\n  ggplot(aes(x=year, y=number_movies, color=`Original region of movies`)) +\n  geom_line() +\n  scale_color_manual(values = c('coral', 'darkturquoise'), labels=c(\"Foreign Movies\", \"Japanese Movies\")) +\n  labs(y=\"Box Office Revenue in Japan\")\n```\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThis graph shows the region of Top 100 movies in terms of box office revenue in Japan for the last 20 years. It clearly illustrates the shift in dominance from foreign films to Japanese films.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranking %>%\n  ggplot(aes(x=year, y=rank, color=region, size=gross)) +\n  geom_point() +\n  coord_flip() +\n  scale_x_reverse() +\n  scale_color_manual(values = c('coral', 'darkturquoise', 'grey'))+\n  labs(title=\"The origin region of top movies in Japan\",\n       x='Year',\n       y='Rank',\n       size = \"Box Office Revenue in Japan\",\n       color = \"Original region of the movie\") +\n  theme(legend.position='bottom')+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe below graph demonstrates if the top 100 movies in Japan were animation or not. It shows that more Japanese animation movies are gaining popularity in Japan in recent years.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranking %>%\n  filter(region!=\"Unknown\") %>%\n  ggplot(aes(x=year, y=rank, color=anime, size=gross)) +\n  geom_point() +\n  coord_flip() +\n  scale_x_reverse() +\n  scale_color_manual(values = c('grey', 'pink'), labels=c(\"No animation\", \"Animation\"))+\n  scale_shape_manual(values = c(4, 3)) +\n  labs(title=\"The genre of top 100 movies in Japan\",\n       x='Year',\n       y='Rank') +\n  theme_minimal() +\n  facet_grid(~region) +\n  labs(color = \"Genre \\n(Anime or not)\", size = \"Box office\\nrevenue \\n (in million USD)\") \n```\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis graph compares the distribution of worldwide box office revenue and domestic (Japan) box office revenue, showing distinct trends before and after the year 2008. For instance, prior to 2008, there seems to be a strong correlation between worldwide box office revenue and domestic box office revenue, suggesting that successful movies globally also performed well in Japan. However, after 2008, a notable shift is observed: there is a growing number of movies with extremely low global box office revenue but high domestic box office revenue in Japan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranking %>%\n  mutate(after_2018 = case_when(year>=2008 ~ TRUE,\n                                TRUE ~ FALSE)) %>%\n  ggplot(aes(x=global_revenue, y=gross, color=after_2018)) +\n  geom_point(alpha = 0.1)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 741 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n## Instructions by Professor\n\n### **1. Write down multiple regression models as discussed in the lab. Please view the recordings for instructions on multicollinearity checks and OVB reduction as it pertains to model specification.**\n\nAs the exploratory analysis shows, the Japanese moviegoers behavior had a great shift around 2008. Also, in Japanese movie industry, the animation format is a critical factor to be considered. Thus, my linear model will include `region`(Foreign movie / Japanese movie), `animation`, `Worldwide box office revenue`, `after_2008` (If the movie is released before or after 2008)\n\n***Multicollinearity***: Multicollinearity occurs when there are correlation between independent variable. There is no concern about multicollinearity because there is only one numeric variable (global revenue)\n\n***Omitted Variable Bias***: Omitted variable bias happens when a model doesn't include one or more relevant variables. In my analysis, the original region of movies (Japanese/foreign) cannot be left out. I added the anime variable that refers to if the movie is animation or not because animation is a format more common in Japanese movies than foreign movies, and the region and the format should be considered separate.\n\nMy linear models are as follows;\n\nThe dependent variable of all models is **box office revenue in Japan**\n\n1.  **Model 1**\n\n    Independent variables:\n\n    1.  Original region of the movie (Japanese/Foreign/Unknown)\n\n    2.  Animation (Animation or not)\n\n2.  **Model 2**\n\n    Independent variables:\n\n    1.  Original region of the movie (Japanese/Foreing/Unknown)\n\n    2.  Animation (Animation or not)\n\n    3.  Worldwide box office revenue\n\n3.  **Model 3**\n\n    1.  Original region of the movie (Japanese/Foreing/Unknown)\n\n    2.  Animation (Animation or not)\n\n    3.  Worldwide box office revenue\n\n    4.  After_2018\n\n4.  **Model 4**\n\n    1.  Original region of the movie (Japanese/Foreing/Unknown)\n\n    2.  Animation (Animation or not)\n\n    3.  Worldwide box office revenue\n\n    4.  After_2018 \\* Original region of the movie\n\n    5.  After_2018 \\* Animation\n\n    6.  After_2018 \\* Worldwide box office revenue\n\nLog Linear model cannot be run because Worldwide box office revenue contains 0 value and log(0) is not defined.\n\n### **2.Upon writing your models, please follow the following steps that make your model-building strategy lends to both internal and external validity**\n\n#### External validity:\n\nThis analysis aims to uncover the preferences of Japanese audiences when it comes to watching movies in theaters and to understand the changing trends over time. According to the Exploratory Analysis, there has been a shift in Japanese movie-going behavior since 2008. Prior to 2008, foreign films were more commonly watched, but since then, there has been a shift towards Japanese films being more frequently viewed.\n\nThe following is the strategy I took to make my model have a high external validity:\n\n**Dependent variable**: I used a dependent variable quite representative for Japanese moviegoers preference, which is box office revenue of the movie in Japan. The independent variable \"region\" represents if the movie is Japanese movie or foreign movie. This data came from if the movie is in Japanese or other languages. Box office revenue is calculated by multiplying the number of viewers by the ticket price, which hasn't changed significantly across different movies. Thus, this dependent variable effectively reflects the popularity of movies among Japanese audiences.\n\n**Independent variable:** In order to answer the main question \"if Japanese moviegoers are watching more domestic movies and less foreign movies\", I used an independent variable \"region\", which basically means if the original language of the movie is Japanese or not. The definition of \"Japanese movies\" is not clear because it can mean that the movie is aimed for only Japanese audience, the movie is available primarily only in Japan, or it is produced by a Japanese company or organization, however I decided to use the original language used in the movie to avoid any arbitrariness. Also, I believe this definition using the original language is aligned with Japanese moviegoers' definition of Japanese/foreign movies. For example, in this analysis, \"Pokémon Detective Pikachu\", a movie produced by both American (Warner brothers) and Japanese companies (Pokemon), is considered as a foriegn movie because it is originally in English.\n\n#### Internal validity:\n\nInternal validity refers to how well the relationship between the dependent and independent variables holds true. In this analysis, we aim to investigate whether a movie being of Japanese origin or foreign origin affects its box office revenue in Japan and whether this trend changes over time.\n\nTo ensure internal validity, I took the following measures:\n\nFirst, I obtained the data for the predictor variable, which is the box office revenue in Japan, from a reliable source called IMDb Pro. There are no missing values, and since the information comes from a single source (IMDb), it can be considered consistent.\n\nThe independent variables, whether the movie is from Japan or an anime, and the worldwide box office revenue, are based on information from another trustworthy website called TMDB. Therefore, these variables should generally be unbiased and consistent. However, some of the top-grossing movies in Japan lacked information on TMDB. For instance, there are movies that were only released in Japan and don't have information on global sites, or there are discrepancies between the titles used in Japan and those registered on TMDB. In such cases, I manually entered data to indicate if the movie is Japanese or an anime to the best of my ability (you can review the data cleaning process in the GitHub link below). It's important to note that there are limitations to this data cleaning process, and I acknowledge that the information about the independent variables is not 100% accurate or consistent.\n\nThis dataset is based on over 2000 movies, making it sufficiently large for analysis and capable of withstanding statistical testing.\n\n\\[GitHub link to data cleaning process: https://github.com/Enagai-nagai/603_Summer2023_Sec_1/tree/template/posts\\]\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#a. Summary statistics for the data: \nsummary(ranking)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      year           rank        original_title         gross          \n Min.   :2002   Min.   :  1.00   Length:3463        Min.   :       86  \n 1st Qu.:2008   1st Qu.: 42.00   Class :character   1st Qu.:   989464  \n Median :2012   Median : 83.00   Mode  :character   Median :  3718929  \n Mean   :2012   Mean   : 85.66                      Mean   :  9069468  \n 3rd Qu.:2017   3rd Qu.:125.00                      3rd Qu.:  9863165  \n Max.   :2022   Max.   :200.00                      Max.   :317074514  \n                                                                       \n  total_gross        release_date       distributor            order      \n Min.   :     1686   Length:3463        Length:3463        Min.   :1.000  \n 1st Qu.:  1479284   Class :character   Class :character   1st Qu.:1.000  \n Median :  4888679   Mode  :character   Mode  :character   Median :1.000  \n Mean   : 11759325                                         Mean   :1.071  \n 3rd Qu.: 12428504                                         3rd Qu.:1.000  \n Max.   :364777208                                         Max.   :3.000  \n                                                                          \n revised_release_date  release_year  revised_title      re_released    \n Length:3463          Min.   :2002   Length:3463        Mode :logical  \n Class :character     1st Qu.:2008   Class :character   FALSE:3404     \n Mode  :character     Median :2012   Mode  :character   TRUE :59       \n                      Mean   :2012                                     \n                      3rd Qu.:2017                                     \n                      Max.   :2022                                     \n                                                                       \n       id         JP_release_date    JP_release_year   id_movies     \n Min.   :   0.0   Length:3463        Min.   :2002    Min.   :   0.0  \n 1st Qu.: 847.5   Class :character   1st Qu.:2008    1st Qu.: 847.5  \n Median :1704.0   Mode  :character   Median :2012    Median :1704.0  \n Mean   :1714.5                      Mean   :2012    Mean   :1714.5  \n 3rd Qu.:2575.5                      3rd Qu.:2017    3rd Qu.:2575.5  \n Max.   :3462.0                      Max.   :2022    Max.   :3462.0  \n NA's   :8                                           NA's   :8       \n    id_tmdb          title              genres          original_language \n Min.   :    12   Length:3463        Length:3463        Length:3463       \n 1st Qu.: 15103   Class :character   Class :character   Class :character  \n Median :120810   Mode  :character   Mode  :character   Mode  :character  \n Mean   :224565                                                           \n 3rd Qu.:382269                                                           \n Max.   :966843                                                           \n NA's   :741                                                              \n   overview           popularity      production_companies     budget         \n Length:3463        Min.   :   0.60   Length:3463          Min.   :        0  \n Class :character   1st Qu.:   5.29   Class :character     1st Qu.:        0  \n Mode  :character   Median :  17.20   Mode  :character     Median : 15000000  \n                    Mean   :  29.93                        Mean   : 41884483  \n                    3rd Qu.:  34.20                        3rd Qu.: 65000000  \n                    Max.   :1134.93                        Max.   :460000000  \n                    NA's   :741                            NA's   :741        \n global_revenue         runtime         status            tagline         \n Min.   :0.000e+00   Min.   :  0.0   Length:3463        Length:3463       \n 1st Qu.:0.000e+00   1st Qu.:100.0   Class :character   Class :character  \n Median :3.530e+07   Median :114.0   Mode  :character   Mode  :character  \n Mean   :1.454e+08   Mean   :112.2                                        \n 3rd Qu.:1.692e+08   3rd Qu.:126.0                                        \n Max.   :2.920e+09   Max.   :202.0                                        \n NA's   :741         NA's   :744                                          \n  vote_average      vote_count        credits            keywords        \n Min.   : 0.000   Min.   :    0.0   Length:3463        Length:3463       \n 1st Qu.: 6.072   1st Qu.:   24.0   Class :character   Class :character  \n Median : 6.692   Median :  866.5   Mode  :character   Mode  :character  \n Mean   : 6.380   Mean   : 2930.4                                        \n 3rd Qu.: 7.247   3rd Qu.: 3953.2                                        \n Max.   :10.000   Max.   :33262.0                                        \n NA's   :741      NA's   :741                                            \n date_difference       region          anime   \n Length:3463        Length:3463        0:2352  \n Class :character   Class :character   1:1111  \n Mode  :character   Mode  :character           \n                                               \n                                               \n                                               \n                                               \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# drop NA\ndf <- ranking %>% \n  filter(!is.na(global_revenue))\n\ndf[is.na(df)|df==\"inf\"] = NA\n\n# b. Customize my variables\ndf$JP_revenue <- df$gross\ndf$Worldwide_revenue <- df$global_revenue\ndf$after_2008 <- case_when(\n  df$year <= 2007 ~ 0,\n  TRUE ~ 1\n)\n\n# Almost 1000 movies' have 0 for their worldwide revenue, which doesn't seem correct.\n# So for those movies I filled Worldwide revenue with their total gross revenue in Japan because those movies are most likely to be available only in Japan and thus their worldwide revenue data was not available\n\ndf$Worldwide_revenue[df$Worldwide_revenue == 0] <- df$total_gross[df$Worldwide_revenue == 0]\n\n# df <- df %>% filter(Worldwide_revenue !=0)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# c. Designate your regressors and report their mean and standard deviation\n\nvars <- c(\"JP_revenue\", \"Worldwide_revenue\")\ncbind(mean = sapply(df[, vars], mean),\n      sd = sapply(df[, vars], sd),\n      max = sapply(df[, vars], max),\n      min = sapply(df[,vars], min))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                       mean        sd        max min\nJP_revenue          9231426  16418185  246836412  86\nWorldwide_revenue 148477622 260815037 2920357254   8\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# d. Estimate a basic linear equation and report summary\n\nlinear_model <- lm(JP_revenue ~ Worldwide_revenue, data = df)\nsummary(linear_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = JP_revenue ~ Worldwide_revenue, data = df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-72366877  -5507751  -3653804   1267980 204159711 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       4.820e+06  3.193e+05   15.10   <2e-16 ***\nWorldwide_revenue 2.971e-02  1.064e-03   27.92   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14480000 on 2720 degrees of freedom\nMultiple R-squared:  0.2227,\tAdjusted R-squared:  0.2225 \nF-statistic: 779.5 on 1 and 2720 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# e. Squared model:\nsquared_model <- lm(JP_revenue ~ I(Worldwide_revenue) + I(Worldwide_revenue ^ 2), data = df)\nsummary(squared_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = JP_revenue ~ I(Worldwide_revenue) + I(Worldwide_revenue^2), \n    data = df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-68607684  -5527803  -3613709   1244221 204258650 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             4.749e+06  3.426e+05  13.861   <2e-16 ***\nI(Worldwide_revenue)    3.065e-02  1.945e-03  15.758   <2e-16 ***\nI(Worldwide_revenue^2) -7.540e-13  1.307e-12  -0.577    0.564    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14480000 on 2719 degrees of freedom\nMultiple R-squared:  0.2228,\tAdjusted R-squared:  0.2223 \nF-statistic: 389.8 on 2 and 2719 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# f. Attempt a log-linear model:\nlinearlog_model <- lm(JP_revenue ~ log(Worldwide_revenue), data = df)\nsummary(linearlog_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = JP_revenue ~ log(Worldwide_revenue), data = df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-17875747  -8764061  -1754900   1997559 228251378 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            -33155687    2237726  -14.82   <2e-16 ***\nlog(Worldwide_revenue)   2467887     129145   19.11   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 15420000 on 2720 degrees of freedom\nMultiple R-squared:  0.1184,\tAdjusted R-squared:  0.118 \nF-statistic: 365.2 on 1 and 2720 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# g. Now attempt a cubic model\ncubic_model <- lm(JP_revenue ~ I(Worldwide_revenue) + I(Worldwide_revenue^2) + I(Worldwide_revenue^3), data = df)\nsummary(cubic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = JP_revenue ~ I(Worldwide_revenue) + I(Worldwide_revenue^2) + \n    I(Worldwide_revenue^3), data = df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-61494718  -5468948  -3802164   1138843 197343273 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             5.494e+06  3.706e+05  14.825  < 2e-16 ***\nI(Worldwide_revenue)    1.491e-02  3.623e-03   4.115 3.99e-05 ***\nI(Worldwide_revenue^2)  2.588e-11  5.344e-12   4.843 1.35e-06 ***\nI(Worldwide_revenue^3) -8.225e-21  1.601e-21  -5.139 2.96e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14410000 on 2718 degrees of freedom\nMultiple R-squared:  0.2303,\tAdjusted R-squared:  0.2295 \nF-statistic: 271.1 on 3 and 2718 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(df$Worldwide_revenue, df$JP_revenue,\n  pch = 20,\n  col = \"steelblue\",\n  xlab = \"Worldwide revenue\",\n  ylab = \"Revenue in Japan\",\nabline(linear_model, lwd = 2))\n\norder_id <- order(df$Worldwide_revenue)\n\n\nlines(df$Worldwide_revenue[order_id],\n      fitted(squared_model)[order_id],\n      col = \"red\",\n      lwd = 2)\n\nlines(df$Worldwide_revenue[order_id],\n      fitted(linearlog_model)[order_id],\n      col = \"green\",\n      lwd = 2)\n\nlines(df$Worldwide_revenue[order_id],\n      fitted(cubic_model)[order_id],\n      col = \"orange\",\n      lwd = 2)\n\nlegend(\"topleft\",\n  legend = c(\"Linear\", \"Squared\", \"Linear-log\", \"Cubic\"),\n  lty = 1,\n  col = c(\"black\", \"red\", \"green\", \"orange\"))\n```\n\n::: {.cell-output-display}\n![](finalProject_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### **3. Explain which robust model best explains the relationship you've set out to investigate.**\n\nAfter running these four regression models, all except the log-linear model exhibit nearly identical results, with an Adjusted R-squared value around 0.23. This similarity arises due to the coefficients of I(Worldwide_revenue\\^2) and I(Worldwide_revenue\\^3) within the Squared and Cubic models being extremely small compared to the simpler linear regression model. The log-linear model demonstrates a distinct trend from the other three models and provides less accurate predictions (with an adjusted R-squared value of 0.118).\n\nConsidering these outcomes, it's optimal to utilize a straightforward linear regression model for the Worldwide_revenue variable. This choice is based on the statistical insignificance of the coefficients for squared and cubed transformations of Worldwide_revenue, their minute values, and the ease of interpretation with fewer variables.\n\nIn the following analysis, we'll employ Worldwide_revenue as well as introduce new variables like `region` ,`anime,` and `after_2018` to explore a model that better explains the predictive variables.\n\nAgain, these variables mean as follows: `region`: Where the movie is from (Japan/Foreign/Unknown) `anime`: If the movie is animation or not `after_2018`: If the movie was among top movies of the year before 2008 / 2008 or after. This variable is incorporated because 2018 marked a significant shift in Japanese moviegoers' behavior.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(JP_revenue ~ region + anime, data = df)\nmod2 <- lm(JP_revenue ~ region + anime + Worldwide_revenue, data = df)\nmod3 <- lm(JP_revenue ~ region + anime + Worldwide_revenue + after_2008, data = df)\nmod4 <- lm(JP_revenue ~ region + anime + Worldwide_revenue + after_2008 * region + after_2008 * anime + after_2008 * Worldwide_revenue, data = df)\n```\n:::\n\n\n## 4. Now find the best model specification through the following steps:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrob_se <- list(sqrt(diag(vcovHC(mod1, type = \"HC1\"))),\n sqrt(diag(vcovHC(mod2, type = \"HC1\"))),\n sqrt(diag(vcovHC(mod3, type = \"HC1\"))),\n sqrt(diag(vcovHC(mod4, type = \"HC1\"))))\n\nstargazer(mod1, mod2, mod3, mod4,\n  title = \"Regressions\",\n  type = \"text\",\n  digits = 3,\n  header = FALSE,\n  se = rob_se,\n  object.names = TRUE,\n  model.numbers = FALSE,\n  column.labels = c(\"(I)\", \"(II)\", \"(III)\", \"(IV)\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nRegressions\n========================================================================================================================================\n                                                                         Dependent variable:                                            \n                             -----------------------------------------------------------------------------------------------------------\n                                                                             JP_revenue                                                 \n                                        (I)                        (II)                      (III)                       (IV)           \n                                        mod1                       mod2                       mod3                       mod4           \n----------------------------------------------------------------------------------------------------------------------------------------\nregionJapan                         848,775.200              9,113,670.000***           9,594,720.000***          11,642,032.000***     \n                                   (650,953.700)              (717,245.300)              (730,267.700)             (1,480,725.000)      \n                                                                                                                                        \nanime1                            4,878,989.000***           2,566,585.000***           2,623,552.000***           -3,047,104.000*      \n                                  (1,183,488.000)             (991,699.200)              (991,089.600)             (1,752,174.000)      \n                                                                                                                                        \nWorldwide_revenue                                                0.037***                   0.037***                   0.062***         \n                                                                 (0.003)                    (0.003)                    (0.005)          \n                                                                                                                                        \nafter_2008                                                                             -3,408,201.000***             164,920.600        \n                                                                                         (583,547.400)              (879,750.500)       \n                                                                                                                                        \nregionJapan:after_2008                                                                                              -2,276,563.000      \n                                                                                                                   (1,681,510.000)      \n                                                                                                                                        \nanime1:after_2008                                                                                                  6,782,232.000***     \n                                                                                                                   (2,114,947.000)      \n                                                                                                                                        \nWorldwide_revenue:after_2008                                                                                          -0.029***         \n                                                                                                                       (0.006)          \n                                                                                                                                        \nConstant                          8,066,172.000***             -120,447.300             2,157,319.000***             -936,735.600       \n                                   (385,618.700)              (558,183.600)              (683,481.400)              (576,664.500)       \n                                                                                                                                        \n----------------------------------------------------------------------------------------------------------------------------------------\nObservations                           2,722                      2,722                      2,722                      2,722           \nR2                                     0.014                      0.294                      0.302                      0.327           \nAdjusted R2                            0.014                      0.293                      0.301                      0.325           \nResidual Std. Error          16,305,349.000 (df = 2719) 13,802,573.000 (df = 2718) 13,727,603.000 (df = 2717) 13,490,275.000 (df = 2714)\nF Statistic                   19.895*** (df = 2; 2719)  377.328*** (df = 3; 2718)  293.787*** (df = 4; 2717)  188.043*** (df = 7; 2714) \n========================================================================================================================================\nNote:                                                                                                        *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = JP_revenue ~ region + anime + Worldwide_revenue + \n    after_2008 * region + after_2008 * anime + after_2008 * Worldwide_revenue, \n    data = df)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-77178377  -6278003  -1367966   1806448 201477318 \n\nCoefficients:\n                               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                  -9.367e+05  7.932e+05  -1.181 0.237714    \nregionJapan                   1.164e+07  1.298e+06   8.968  < 2e-16 ***\nanime1                       -3.047e+06  1.562e+06  -1.951 0.051152 .  \nWorldwide_revenue             6.208e-02  2.902e-03  21.393  < 2e-16 ***\nafter_2008                    1.649e+05  9.361e+05   0.176 0.860164    \nregionJapan:after_2008       -2.277e+06  1.467e+06  -1.552 0.120776    \nanime1:after_2008             6.782e+06  1.750e+06   3.875 0.000109 ***\nWorldwide_revenue:after_2008 -2.881e-02  3.134e-03  -9.193  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 13490000 on 2714 degrees of freedom\nMultiple R-squared:  0.3266,\tAdjusted R-squared:  0.3249 \nF-statistic:   188 on 7 and 2714 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(mod1, \n   c(\"regionJapan=0\", \"anime1=0\"), \n   vcov. = vcovHC(mod1, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nregionJapan = 0\nanime1 = 0\n\nModel 1: restricted model\nModel 2: JP_revenue ~ region + anime\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1   2721                        \n2   2719  2 10.755 2.226e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod2,\n   c(\"regionJapan=0\", \"anime1=0\"),\n   vcov. = vcovHC(mod2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nregionJapan = 0\nanime1 = 0\n\nModel 1: restricted model\nModel 2: JP_revenue ~ region + anime + Worldwide_revenue\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df     F    Pr(>F)    \n1   2720                       \n2   2718  2 83.91 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod3,\n   c(\"regionJapan=0\", \"anime1=0\", \"after_2008=0\"),\n   vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nregionJapan = 0\nanime1 = 0\nafter_2008 = 0\n\nModel 1: restricted model\nModel 2: JP_revenue ~ region + anime + Worldwide_revenue + after_2008\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1   2720                        \n2   2717  3 64.444 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4,\n   c(\"regionJapan=0\", \"anime1=0\", \"after_2008=0\", \"regionJapan:after_2008 = 0\", \"anime1:after_2008 = 0\"),\n   vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nregionJapan = 0\nanime1 = 0\nafter_2008 = 0\nregionJapan:after_2008 = 0\nanime1:after_2008 = 0\n\nModel 1: restricted model\nModel 2: JP_revenue ~ region + anime + Worldwide_revenue + after_2008 * \n    region + after_2008 * anime + after_2008 * Worldwide_revenue\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1   2719                        \n2   2714  5 49.357 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n## 5.Explain which robust model best explains the relationship you\\'ve set out to investigate.\n\nAmong the four models, the one that includes \"after_2008\" (indicating whether the movie was released after 2008) had the smallest Residual Std. error and the highest Adjusted R-squared value, indicating the most high-performing results. This indirectly suggests a change in the trend of box office revenue for movies in Japan around the year 2008.\n\n### Interpretation of the best-performing model\n\nTo interpret each variable and coefficient in more detail:\n\n1\\. Being a Japanese film generally is related to the increase of box office revenue in Japan (regionJapan: 11,642,032\\*\\*\\*). However, after 2008, being a Japanese film doesn't seem to inherently boost revenue, as the coefficient for regionJapan:after_2008 is statistically insignificant and negative (-6,782,232).\n\n2\\. Being an anime film is generally associated with a decrease of \\$3,047,104 in Japanese box office revenue. Yet, post-2008, being an anime film is linked to an increase in Japanese box office revenue of \\$6,782,232 - \\$3,047,104 = \\$3,735,128.\n\n3\\. Considering the relationship with worldwide box office revenue, before 2008, for every \\$1 increase in worldwide_revenue, Japanese box office revenue tended to increase by \\$0.062. However, after 2008, for every \\$1 increase in worldwide_revenue, Japanese box office revenue only increases by \\$0.033 (\\$0.062 - \\$0.029). This suggests that Japanese box office revenue is less influenced by global box office revenue post-2008.\n\nIn summary, the model incorporating \"after_2008\" yields the best results among the four models, hinting at a shift in Japanese movie revenue trends around 2008.\n\n**External and Internal Validity**\n\nAs demonstrated above, this model exhibits both external validity and internal validity. This is because the model aims to demonstrate how the trend of moviegoing behavior in Japanese cinemas has changed over the past 20 years. Specifically, it addresses the previously identified trend that \"around 2008, Japanese moviegoers shifted their preferences, watching more domestic films and fewer foreign films.\" The model uses Japanese moviegoer preferences as indicated by box office revenue in Japan, representing the variables of Japanese films/foreign films and the language spoken in movies. The inclusion of the \"after_2008\" variable further enhances external validity. Moreover, the data is sourced from a reliable and consistent database, reducing bias and ensuring high internal validity.\n\nHowever, it's worth noting that, as previously mentioned, there are missing values in the worldwide box office revenue data, and manual data processing has occurred, introducing some inconsistency in that aspect.\n\n### Observation and lnsights from the models \n\nThe results from these linear models reveal intriguing insights into the movie-going tendencies in Japanese theaters.\n\nFirst, considering solely the global box office revenue of movies, I find that it can explain less than 22% of the variation in Japan's movie box office revenue (linear model : R squared ≒ 0.2). This discovery is thought-provoking, as it implies that movies that resonate in Japan might not necessarily be highly influenced by their global popularity. This suggests that a movie's success worldwide might not directly translate to its popularity in Japan. For instance, a movie that performs exceptionally well worldwide might not garner as much attention in Japanese theaters.\n\nFurther delving into the impact of a movie's origin (Japan or overseas) and whether it is an animated film (mod1), we observe that, in terms of Japan's movie box office revenue, only the distinction of being an animated film holds statistically significant influence. The origin of being a Japanese movie appears to positively affect the box office revenue (with a coefficient of approximately 848,000), yet it does not hold statistical significance.\n\nAs mentioned earlier in the analysis, the primary focus was on uncovering how the movie-watching tendencies in Japan have evolved over time. Building upon the preliminary analysis that revealed a reversal in the total box office revenue between foreign and Japanese films around 2008, mod4 introduces a new dummy variable called \"after_2008\" to investigate the interaction of this variable with others. Two significant findings emerged as a result of this approach.\n\nFirstly, post-2008, the influence of worldwide revenue on domestic box office revenue in Japan has diminished. (The coefficient of worldwide_revenue before 2008 was 0.061, while after introducing \"after_2008,\" the coefficient for worldwide_revenue after 2008 became 0.061 - 0.028 (coefficient of worldwide_revenue:after_2008) = 0.033.) This suggests that the impact of a movie's international box office revenue on its box office revenue in Japan has decreased, indicating a deviation of Japan's movie box office revenue trend from that of the rest of the world.\n\nSecondly, though according to the exploratory analysis it appears that Japanese films gained popularity over foreign films after 2008, the reason behind this shift lies not solely in a general rise in the popularity of Japanese films, but in the increased popularity of animated Japanese films.\n\n### Additional analysis (Dividing the data into two periods)\n\nMoving forward, additional analyses were conducted to further find out the trends around the 2008 period. The dataset was divided into two distinct segments: the years 2002-2007 and 2008-2020. Separate linear regression models were then applied to each of these segments.\n\nThe aim of these analyses was to provide clearer insights into the shifts that occurred around the 2008 timeframe. By examining the data in these two distinct timeframes and running separate linear regression models for each, we sought to capture any contrasting patterns or trends that might have emerged before and after 2008. This approach allowed us to better understand how the dynamics of the movie industry, particularly in relation to Japan's movie-watching preferences, have evolved over time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_before <- df %>% filter(year<2008)\ndf_after <- df %>% filter(year>=2008)\nmod1_before <- lm(JP_revenue~region+anime+Worldwide_revenue, data = df_before)\nmod1_after <- lm(JP_revenue~region+anime+Worldwide_revenue, data = df_after)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrob_se <- list(sqrt(diag(vcovHC(mod1_before, type = \"HC1\"))),\n sqrt(diag(vcovHC(mod1_after, type = \"HC1\"))))\n\n\nstargazer(mod1_before, mod1_after, \n          type = \"text\",\n          column.labels = c(\"2002-2007\", \"2008-2020\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n========================================================================\n                                    Dependent variable:                 \n                    ----------------------------------------------------\n                                         JP_revenue                     \n                            2002-2007                 2008-2020         \n                               (1)                       (2)            \n------------------------------------------------------------------------\nregionJapan             11,642,032.000***          9,365,468.000***     \n                         (1,158,640.000)            (705,634.800)       \n                                                                        \nanime1                  -3,047,104.000**           3,735,128.000***     \n                         (1,393,877.000)            (816,401.500)       \n                                                                        \nWorldwide_revenue           0.062***                   0.033***         \n                             (0.003)                   (0.001)          \n                                                                        \nConstant                  -936,735.600               -771,815.000       \n                          (707,918.400)             (513,652.500)       \n                                                                        \n------------------------------------------------------------------------\nObservations                   682                      2,040           \nR2                            0.461                     0.281           \nAdjusted R2                   0.459                     0.280           \nResidual Std. Error 12,040,092.000 (df = 678) 13,939,750.000 (df = 2036)\nF Statistic         193.512*** (df = 3; 678)  265.276*** (df = 3; 2036) \n========================================================================\nNote:                                        *p<0.1; **p<0.05; ***p<0.01\n```\n:::\n:::\n\n\nThe results from these models exhibit similar trends as the previous analysis.\n\nTo begin with, prior to 2008, the box office revenue in Japan was influenced by the global box office revenue, but this influence diminished after 2008. (The coefficients of Worldwide_revenue in (1) and (2) decreased from 0.062 to 0.033.) Furthermore, before 2008, being an animated film was associated with a negative relationship between the global box office revenue and the predicted box office revenue in Japan. However, this trend reversed after 2008.\n\n## Conclusion\n\nThe moviegoing behavior in Japan underwent a significant shift around 2008. Before 2008, foreign films garnered higher box office revenue in Japan (indicating a larger audience), but post-2008, this trend reversed, with domestic Japanese films surpassing foreign films in box office revenue. As of 2022, the box office revenue from foreign films is less than half of that from Japanese films.\n\nThis phenomenon can be attributed to three factors:\n\nFirstly, Japanese movie preferences are diverging from global trends. Prior to 2008, a \\$1 increase in worldwide box office revenue corresponded to a \\$0.066 increase in Japanese box office revenue. However, post-2008, this correlation weakened significantly to a mere \\$0.028 increase. A global hit is not necessarily a guarantee for success in Japan.\n\nSecondly, predicting Japanese movie revenue has become more complex after 2008. Before 2008, 46% of Japanese box office revenue could be explained using three factors: 1. Japanese or foreign film, 2. Animation or not, and 3. Worldwide box office revenue. However, post-2008, only 28% of the revenue could be explained. This suggests that Japanese movie preferences are influenced by more intricate factors not covered by these simple variables.\n\nLastly, while the data indicates a growing preference for Japanese films among Japanese audiences, it's not necessarily the fact of being a Japanese film that drives revenue growth. Instead, the surge in revenue is more correlated with the presence of \"anime films,\" which are prevalent in Japanese cinema.\n\n### \n",
    "supporting": [
      "finalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}