{
  "hash": "3c0595d915346e6576a926bd10e35099",
  "result": {
    "markdown": "---\ntitle: \"Keith Martin Project 1\"\nauthor: \"Keith Martin\"\ndesription: \"Analysis on Dispensary Licensing\"\ndate: \"07/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - project1\n  - dataset\n  - ggplot2\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(readxl)\nlibrary(summarytools)\nlibrary(ggplot2)\nlibrary(magrittr)\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Reading The Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPA_Dispensary_License_Data_tab <- read_excel(\"~/Downloads/PA Dispensary License Data.tab.xlsx\")\nhead(PA_Dispensary_License_Data_tab, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 22\n   phase dispens…¹ name  diver…² opera…³ quali…⁴ secur…⁵ trans…⁶ storage label…⁷\n   <dbl> <chr>     <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1     1 D-1001-17 BHS …      31    70.4    25.6    50.2    11.8    24.4    16.4\n 2     1 D-1003-17 Prim…      68    64.8    35.6    56.2    16      37.8    18.2\n 3     1 D-1004-17 Keen…      65    63.8    32.4    72.2    12.4    30.8    13.6\n 4     1 D-1006-17 Grow…      34    48      27.2    48.4    13      20.6    14.4\n 5     1 D-1007-17 Heal…      25    51.4    26.2    51.4    13.2    23.4    14.2\n 6     1 D-1009-17 Elem…      40    66      27.8    65.6    18.6    32.4    15.8\n 7     1 D-1010-17 420 …      60    29.6    21      32.6     9.6    16.2     9.6\n 8     1 D-1011-17 Pali…      38    48      31.6    56.8     6.2    26.4    16.6\n 9     1 D-1012-17 The …      32    24.8    29.2    56.4    15      26.2    14.6\n10     1 D-1013-17 Elem…      40    66.4    31.4    65.6    18      32.6    17.2\n# … with 12 more variables: inventory <dbl>, diversion <dbl>, sanitation <dbl>,\n#   recordkeeping <dbl>, history <dbl>, capital <dbl>, community <dbl>,\n#   siteplan <dbl>, personalid <dbl>, awarded <dbl>, licensed <dbl>,\n#   dispensaries <dbl>, and abbreviated variable names ¹​dispensarynumber,\n#   ²​diversityplan, ³​operationaltimetable, ⁴​qualifications, ⁵​security,\n#   ⁶​transportation, ⁷​labeling\n```\n:::\n:::\n\nThe data set includes various companies that applied for a dispensary license in 2018. There are 16 categories that are added up to a total score. The score is used to determine whether or not the company will receive a license to operate a dispensary. \n\n## Cleaning Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n PA_Dispensary_License_Condensed<-PA_Dispensary_License_Data_tab %>%\n      select(name, diversityplan, qualifications, security, capital,licensed, awarded)\nhead(PA_Dispensary_License_Condensed, 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 10 × 7\n   name                          diver…¹ quali…² secur…³ capital licen…⁴ awarded\n   <chr>                           <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n 1 BHS Wellness, LLC                  31    25.6    50.2    28.6       0    471 \n 2 Prime Wellness of Pennsylvan…      68    35.6    56.2    67.2       0    644 \n 3 Keen Meds, LLC                     65    32.4    72.2    59.2       0    608.\n 4 Grow Ventures Penn, LLC            34    27.2    48.4    53.6       0    468.\n 5 Healing Hope, LLC                  25    26.2    51.4    37.4       0    478.\n 6 Elemental Health Group, LLC        40    27.8    65.6    62.6       0    646.\n 7 420 Nature's Root                  60    21      32.6    41.2       0    396.\n 8 PaliaTech PA, LLC                  38    31.6    56.8    50         0    512.\n 9 The Natural Dispensary, LLC        32    29.2    56.4    51.8       0    492.\n10 Elemental Health Group, LLC        40    31.4    65.6    56.2       0    618.\n# … with abbreviated variable names ¹​diversityplan, ²​qualifications, ³​security,\n#   ⁴​licensed\n```\n:::\n:::\n\n\nI grouped the data set into several categories that I will focus on in this project and in future projects.\n\n\n## Cumulative Distribution Function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(PA_Dispensary_License_Condensed, aes(x = capital)) +\n  stat_ecdf(geom = \"step\") +\n  labs(x = \"capital\", y = \"Cumulative Probability\") +\n  ggtitle(\"Cumulative Density Function for Capital\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 136 rows containing non-finite values (`stat_ecdf()`).\n```\n:::\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe CDF provides information about the cumulative probability of the variable capital taking on certain values or being less than or equal to a specific value. Specifically, for any given value x of capital, the CDF tells us the probability that capital is less than or equal to x.\n\nBy examining the CDF for capital, we can understand the distribution of the variable. In this case, the majority of the values of capital sit around the 45-70 range on the x-axis. There are not as many variables under 40. On the other hand, the CDF increases gradually, it indicates a more uniform distribution of capital across its range, Additionally, the shape of the CDF can provide insights into the central tendency, spread, and skewness of the capital variable.\n\nIn summary, the CDF for the variable capital helps us understand the probability distribution of capital, assess the likelihood of specific values or ranges, and calculate percentiles or quantiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(PA_Dispensary_License_Condensed, aes(x = licensed)) +\n  stat_ecdf(geom = \"step\") +\n  labs(x = \"Licensed\", y = \"Cumulative Probability\") +\n  ggtitle(\"Cumulative Density Function For Licensed Variable\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nContrary to above, the CDF for Licensed shows a dramatic increase. It still has a vague shape of of the cumulative density function, but since the variable in binary, it does not neatly plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(PA_Dispensary_License_Condensed, aes(x = capital, fill = licensed)) +\n  geom_density(alpha = 0.5) +\n  labs(x = \"Capital\", y = \"Density\", fill = \"licensed\") +\n  ggtitle(\"Probability Density Function\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 136 rows containing non-finite values (`stat_density()`).\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The following aesthetics were dropped during statistical transformation: fill\nℹ This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\nℹ Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\n```\n:::\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe PDF shows that the distribution of the variables Capital and Licensed is skewed left, also known as a negative-skewed distribution. This means that the tail of the distribution extends towards lower values.\n\nIn the case of the variables Capital and Licensed, a left-skewed distribution indicates that there is a concentration of higher values for Capital and a smaller number of lower values. It suggests that the proportion of observations with a value of Licensed equal to 1 may be higher compared to the proportion with a value of 0.\n\nWhen plotting the PDF, you will notice a longer tail on the left-hand side of the distribution. The majority of data points will be clustered towards the higher end of the Capital variable, with progressively fewer observations occurring as the values decrease.\n\nIt's important to keep in mind that skewness only describes the shape of the distribution and does not imply any causality or the direction of a relationship between the variables.\n\n# Summary Statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Find Summary Statistics\n avg <- PA_Dispensary_License_Condensed%>%\n  group_by(licensed)%>%\n  summarise(\n      sd_capital = sd (capital, na.rm=TRUE),\n      max_capital = max(capital, na.rm = TRUE),\n      min_capital = min(capital, na.rm = TRUE),\n      avg_capital = mean (capital, na.rm = TRUE),\n      med_capital = median(capital, na.rm = TRUE),\n      n_capital = n()) \n\n\n### Average into own variables\nLicensed_avg <- avg %>% dplyr::filter(licensed == 1) %>% pull(avg_capital)\n\nUnlicensed_avg <- avg %>% dplyr::filter(licensed == 0) %>% pull(avg_capital)\n\n### Separate Standard Deviation into own variables\nLicensed_sd <- avg %>% dplyr::filter(licensed == 1) %>% pull(sd_capital)\n\nUnlicensed_sd <- avg %>% dplyr::filter(licensed == 0) %>% pull(sd_capital)\n\n### Separate n() into own variables\nLicensed_n <- avg %>% dplyr::filter(licensed == 1) %>% pull(n_capital)\n\nUnlicensed_n <- avg %>% dplyr::filter(licensed == 0) %>% pull(n_capital)\n\n### statistical equations\n\nscore_diff <- Licensed_avg - Unlicensed_avg\n\n\nse <- sqrt(Licensed_sd^2/Licensed_n + Unlicensed_sd^2/Unlicensed_n)\n\n\n\nci_lic_l <- score_diff - 1.96* se\nci_lic_u <- score_diff + 1.96 * se\n\n\n\n### Data Frame with all of the results neatly labeled\nresults <- data.frame(\n  Licensed_avg = Licensed_avg,\n  Unlicensed_avg = Unlicensed_avg,\n  Licensed_sd = Licensed_sd,\n  Unlicensed_sd = Unlicensed_sd,\n  Licensed_n = Licensed_n,\n  Unlicensed_n = Unlicensed_n,\n  score_diff = score_diff,\n  se = se,\n  ci_lic_l = ci_lic_l,\n  ci_lic_u = ci_lic_u\n)\n\nprint(results)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Licensed_avg Unlicensed_avg Licensed_sd Unlicensed_sd Licensed_n Unlicensed_n\n1     62.59296       52.37786    4.955124       12.3944         50          337\n  score_diff        se ci_lic_l ci_lic_u\n1   10.21511 0.9730951 8.307839 12.12237\n```\n:::\n:::\n\nThe above table captures the averages, standard deviation, the number, the difference of means, the standard error and the confidence intervals. The show the relationships between capital scores of companies that received a licensed and those who did not receive a license.  Capital has a confidence interval of 8.307839 to 12.12237 when grouped by license, it means that we are estimating a range of plausible values for the average capital depending on the group (licensed).\n\nSpecifically, this confidence interval provides an estimate of the range within which we can be reasonably confident that the true average capital falls, based on the data and statistical analysis. The confidence interval suggests that we are 95% confident that the true average capital for the respective groups falls between the values of 8.307839 and 12.12237. Note the confidence interval is the upper and lower bounds of the differences in the sampe means, not the actual X values.\n# Scatterplot with Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Scatterplot using GGplot\n\nggplot(PA_Dispensary_License_Condensed, aes(x = capital, y = licensed, na.rm=TRUE)) +\n  geom_point() +\n  labs(x = \"Capital\", y = \"Licensed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 136 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe above scatter plot shows the relationship between capital score and dispensaries that received a license. As you can see, the graph does not do a great job showing the relationship since the licensed variable is binary. This will be built on in future projects when other regressors are added.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = PA_Dispensary_License_Condensed, aes(x = capital, fill = factor(licensed))) +\n  geom_bar() +\n  labs(x = \"Capital\", y = \"Count\", fill = \"Licensed\") +\n  ggtitle(\"Bar Chart: Capital vs Licensed\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 136 rows containing non-finite values (`stat_count()`).\n```\n:::\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nI have included this bar chart to further visualize the relationship between the capital score and whether or not they received a license.\n\n# Alternative Standard Error and Confidence Interval Using T Test \n\n\n::: {.cell}\n\n```{.r .cell-code}\n###Find confidence interval of of licensed vs unlicensed \n\nconfidence_level <- 0.95\nci <- t.test(PA_Dispensary_License_Condensed$capital ~ PA_Dispensary_License_Condensed$licensed, conf.level = confidence_level)$conf.int\nprint(ci)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -12.731131  -7.699081\nattr(,\"conf.level\")\n[1] 0.95\n```\n:::\n\n```{.r .cell-code}\n### Alternative method for automatically finding the standard error based on the T.Test\nresult_se <- t.test(PA_Dispensary_License_Condensed$capital ~ PA_Dispensary_License_Condensed$licensed)\nstandard_error <- result_se$stderr\nprint(standard_error)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.263008\n```\n:::\n:::\n\n\nThe above standard error and confidence intervals are additional tests showing the accuracy of the values calculated above. As you can see, the values are almost the exact same within a tenth of a decimal point.\n#Regression Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_model<-lm(licensed ~ capital, data = PA_Dispensary_License_Condensed)\n\nsummary(linear_model)$coefficient\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                Estimate  Std. Error   t value     Pr(>|t|)\n(Intercept) -0.244278261 0.085204568 -2.866962 4.499059e-03\ncapital      0.006579464 0.001553339  4.235692 3.209303e-05\n```\n:::\n\n```{.r .cell-code}\n### Have to plot it differently\n\nplot(PA_Dispensary_License_Condensed$capital, PA_Dispensary_License_Condensed$licensed, main = \"Regression Results\", xlab = \"X\", ylab = \"Y\")\nabline(linear_model, col = \"red\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nIn summary, a T-value of 4.235692 for the independent variable capital in a simple regression with the dependent variable licensed indicates a strong relationship between the variables, and the relationship is statistically significant based on the chosen level of significance. In this case, the p-value is extremely small and less than one 1%. The chosen level of significance for this case would be P<.05. More specifically, if the p-value is below the predetermined significance level, it suggests that the probability of observing the results under the null hypothesis are very low. In such cases, it is generally concluded that there is a statistically significant relationship in the data.\n\nFor each unit increase in the capital variable, there is an estimated increase of approximately 0.006579464 in the probability or likelihood of the licensed variable being equal to 1, assuming all other factors are held constant.\n\nIn plain English, this means that as the capital variable increases, the estimated effect is a slight increase in the probability of having a value of 1 for the licensed variable. However, since the coefficient is very small (0.006579464), the practical significance of this effect may be limited.\n\nSince the dependent variable is a dummy (binary) variable, the regression line does not fit that nicely on the plot. I did some additional research and found that a curve is more fitting for this type of variable. \n# Regression Analysis With Binary Variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Regression Graph for Dummy Dependent Variable\n\nmodel <- glm(licensed ~ capital, data = PA_Dispensary_License_Condensed, family = binomial)\nplot(PA_Dispensary_License_Condensed$capital, PA_Dispensary_License_Condensed$licensed, main = \"Regression Plot of Licensed vs. Capital\", xlab = \"Capital\", ylab = \"Licensed\")\n### This code adds a curve instead of a standard line(abline) for regression of dummy dependent variables\ncurve(predict(model, data.frame(capital = x), type = \"response\"), add = TRUE, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](KeithMartin_Project1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nIn the above plot, I used a general linear model to predict the curve of the dummy variable. This is a much cleaner plot that the original regression line above. This more closely illustrates the relationship between capital score and licensing outcome.\n",
    "supporting": [
      "KeithMartin_Project1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}