{
  "hash": "3d0a0b8d8b28018d32b0cdd2810cf6c6",
  "result": {
    "markdown": "---\ntitle: \"Final Project\"\nauthor: \"Sue-Ellen Duffy\"\ndate: \"08/16/2023\"\nformat:\n  html:\n    df-print: paged\n    toc: true\n    code-copy: true\n    code-tools: true\n    css: \"styles.css\"\noutput: inline\n---\n\n::: {.cell messAADT='false'}\n\n```{.r .cell-code}\nlibrary(MASS)\nlibrary(scales)\nlibrary(tidyverse)\nlibrary(summarytools)\nlibrary(stats)\nlibrary(kableExtra)\nlibrary(ggplot2)\nlibrary(hrbrthemes)\nlibrary(viridis)\nlibrary(stringr)\nlibrary(stargazer)\nlibrary(sandwich)\nlibrary(broom)\nlibrary(car)\n\nknitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)\n```\n:::\n\n\n### Boston Crash Data - Statistical Analysis of the Number of Vehicles per Crash from 2013 to 2022 by AADT (Traffic Volume)\n\n**Hypothesis**: The number of vehicles per crash increase as traffic volumes increase in Boston, Massachusetts.\n\nIn order to study this hypothesis I will look at publicly available crash data,  from the Massachusetts Department of Transportation, specifically crashes in Boston from 2013 to 2022.\n\n\nThis dataset includes 40,296 individual crashes in Boston from 2013-2022 which are represented by each row in the dataset. The dataset has been parsed down from 10 different datasets to specifically include the year, number of vehicles per crash, speed limit of the crash site, AADT (Average Annual Daily Traffic - effectively measuring traffic volume), and two original columns to the data indicating whether the driver was distracted prior to the crash which I pair down to one binary column.\n\n# Read in Data\n\n::: {.cell}\n\n```{.r .cell-code}\n#Read in Combined Data\nmydata <- read_csv(\"Sue-Ellen_Data/2013_2022_Crashes_Boston_Round_5.csv\")[, -1]\n```\n:::\n\n# Clean and filter data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Filter out AADT years with less than 500 observances\nmydata <- mydata %>%\n  mutate(AADT_YEAR = if_else(AADT_YEAR %in% c(2009, 2013, 2014, 2018, 2020), AADT_YEAR, NA))\nmydata <- mydata %>%\n mutate(AADT = if_else(AADT_YEAR %in% c(0, NA),  NA, AADT))\n\n#Filter out values from speed that are abnormal (example: 555 or -55 or 21)\nmydata <- mydata %>%\n  mutate(SPEED_LIMIT = if_else(SPEED_LIMIT %in% c(\"10\", \"15\", \"20\", \"25\", \"30\", \"35\", \"40\", \"45\", \"50\", \"55\", \"65\"), SPEED_LIMIT, NA))\n\n#Assign Distracted Binary Data\nmydata <- mydata %>%\n  mutate(D_B1 = if_else(str_detect(DRVR_CNTRB_CIRC_CL, \"Distracted|Inattention|distraction\"), 1, 0)) %>%\n  mutate(D_B1_2 = if_else(str_detect(DRVR_DISTRACTED_CL, \"electronic|External|Other|Passenger\"), 1, 0))\n\nmydata<- mydata %>% mutate(Distracted_Binary = if_else(D_B1 %in% c(0), D_B1, NA))\nmydata<- mydata %>% mutate(Distracted_Binary = if_else(D_B1_2 %in% c(0), D_B1_2, Distracted_Binary))\nmydata<- mydata %>% mutate(Distracted_Binary = if_else(D_B1 %in% c(1), D_B1, Distracted_Binary))\nmydata<- mydata %>% mutate(Distracted_Binary = if_else(D_B1_2 %in% c(1), D_B1_2, Distracted_Binary))\n```\n:::\n\n\n# Dataset Summary\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(mydata[, c(\"NUMB_VEHC\", \"AADT\", \"SPEED_LIMIT\", \"YEAR\", \"Distracted_Binary\")]) \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"NUMB_VEHC\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"AADT\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SPEED_LIMIT\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"YEAR\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Distracted_Binary\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2\",\"2\":\"NA\",\"3\":\"30\",\"4\":\"2013\",\"5\":\"1\"},{\"1\":\"1\",\"2\":\"NA\",\"3\":\"25\",\"4\":\"2013\",\"5\":\"0\"},{\"1\":\"2\",\"2\":\"56639\",\"3\":\"40\",\"4\":\"2013\",\"5\":\"0\"},{\"1\":\"1\",\"2\":\"27634\",\"3\":\"35\",\"4\":\"2013\",\"5\":\"0\"},{\"1\":\"2\",\"2\":\"56639\",\"3\":\"35\",\"4\":\"2013\",\"5\":\"0\"},{\"1\":\"2\",\"2\":\"56639\",\"3\":\"35\",\"4\":\"2013\",\"5\":\"0\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nsummary(mydata[, c(\"NUMB_VEHC\", \"AADT\", \"SPEED_LIMIT\", \"YEAR\", \"Distracted_Binary\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   NUMB_VEHC           AADT         SPEED_LIMIT         YEAR     \n Min.   : 1.000   Min.   :   211   Min.   :10.00   Min.   :2013  \n 1st Qu.: 2.000   1st Qu.: 18500   1st Qu.:30.00   1st Qu.:2015  \n Median : 2.000   Median : 42594   Median :35.00   Median :2017  \n Mean   : 1.961   Mean   : 81152   Mean   :37.69   Mean   :2017  \n 3rd Qu.: 2.000   3rd Qu.:134028   3rd Qu.:45.00   3rd Qu.:2020  \n Max.   :18.000   Max.   :260824   Max.   :65.00   Max.   :2022  \n                  NA's   :10920    NA's   :9312                  \n Distracted_Binary\n Min.   :0.000    \n 1st Qu.:0.000    \n Median :0.000    \n Mean   :0.109    \n 3rd Qu.:0.000    \n Max.   :1.000    \n NA's   :3217     \n```\n:::\n:::\n\nRegressors:\n\n::: {.cell}\n\n```{.r .cell-code}\nvars <- c(\"NUMB_VEHC\", \"AADT\", \"SPEED_LIMIT\", \"YEAR\", \"Distracted_Binary\")\noptions(scipen = 999)\nresult <- cbind(NV_mean = sapply(mydata[, vars], function(x) mean(x, na.rm = TRUE)),\n      NV_sd = sapply(mydata[, vars], function(x) sd(x, na.rm = TRUE)))\n\nresult <- round(result, 3)\nprint(result)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    NV_mean     NV_sd\nNUMB_VEHC             1.961     0.744\nAADT              81152.251 72953.537\nSPEED_LIMIT          37.691    11.001\nYEAR               2017.434     2.793\nDistracted_Binary     0.109     0.311\n```\n:::\n:::\n\n+ **NUMB_VEHC**: Number of Vehicles per Crash\n\n+ **AADT**: Average Annual Daily Traffic: average number of vehicles that pass a specific point on a road or highway in both directions over the course of a year, typically calculated by summing the traffic volumes for each day of the year and then dividing by 365. A traffic volume metric, and therefore referenced at times in this report as \"Traffic Volume\"\n\n+ **SPEED_LIMIT**: Speed Limit at the particular site of crash. Does not indicate speed of driver.\n\n+ **YEAR**: Year of Crash\n\n+ **Distracted_Binary**:  Driver Distracted 1=Yes, 0=No. I created this binary from the available data, including the two columns, Driver Contributing Circumstances and Driver Distracted. If either of the columns indicated the driver was not distracted, Distracted_Binary will read 0, and prevailing over the preceding rule, if either of the columns indicated the driver was distracted, Distracted_Binary will read 1. However if neither of the columns indicated an observance either way, the crash will read NA.\n\n# Linear and Non-Linear Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLinear_model <- lm(NUMB_VEHC ~AADT,  data = mydata)\nCubic_model <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3), data = mydata)\nQuadratic_model <- lm(NUMB_VEHC ~ AADT + I(AADT^2), data = mydata)\nLinearLog_model <- lm(NUMB_VEHC ~ log(AADT), data = mydata)\nLogLinear_model <- lm(log(NUMB_VEHC) ~ AADT, data = mydata)\nLogLog_model <- lm(log(NUMB_VEHC) ~ log(AADT), data = mydata)\nPolyLog_model <- lm(NUMB_VEHC ~ log(AADT) + I(log(AADT)^2) + I(log(AADT)^3), \n                    data = mydata)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_R2 <-rbind(\n              \"Linear\" = summary(Linear_model)$adj.r.squared,\n              \"Cubic\" = summary(Cubic_model)$adj.r.squared,\n               \"Quadratic\" = summary(Quadratic_model)$adj.r.squared,\n               \"LinearLog\" = summary(LinearLog_model)$adj.r.squared,\n               \"LogLinear\" = summary(LogLinear_model)$adj.r.squared,\n               \"LogLog\" = summary(LogLog_model)$adj.r.squared,\n               \"PolyLog\" = summary(PolyLog_model)$adj.r.squared)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nf_statistic <-rbind(\n              \"Linear\" = summary(Linear_model)$fstatistic[[\"value\"]],\n               \"Cubic\" = summary(Cubic_model)$fstatistic[[\"value\"]],\n               \"Quadratic\" = summary(Quadratic_model)$fstatistic[[\"value\"]],\n               \"LinearLog\" = summary(LinearLog_model)$fstatistic[[\"value\"]],\n               \"LogLinear\" = summary(LogLinear_model)$fstatistic[[\"value\"]],\n               \"LogLog\" = summary(LogLog_model)$fstatistic[[\"value\"]],\n               \"PolyLog\" = summary(PolyLog_model)$fstatistic[[\"value\"]])\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nadj_f <- cbind(adj_R2, f_statistic)\ncolnames(adj_f) <- c(\"adj_R2\", \"f_statistic\")\nadj_f\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              adj_R2 f_statistic\nLinear    0.03426426   1043.2236\nCubic     0.03726700    380.0314\nQuadratic 0.03536785    539.5113\nLinearLog 0.02361257    711.3933\nLogLinear 0.03085573    936.2446\nLogLog    0.02048819    615.4292\nPolyLog   0.03487512    354.8252\n```\n:::\n:::\n\n### Adjusted R2 and F-Statistic\n\nAs the analysis of the adjusted R2 and the f-statistics of the above seven models show, the model with the highest adjusted R2 values is the cubic model. This would demonstrate that the cubic model is the best fit for the data with an adjusted R2 value of 0.037, indicating that the model explains approximately 3.74% of the variability in the Numbers of Vehicles per Crash.  The cubic model also has a low f-statistic, suggesting that the model explains a significant amount of variance in the Numbers of Vehicles per Crash.  \n\nThe three models with the next closest adjusted R2 are: quadratic model, poly log model, and linear model. As the values are so close, it will be useful to visualize the models in a plot.  \n\n# Plots: Linear, Cubic, LogLinear and PolyLog\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmydata %>%\n  ggplot(aes(AADT, NUMB_VEHC, na.rm = TRUE)) +\n  geom_point(color = \"skyblue\", shape = 21, size = 0.1, na.rm = TRUE, position = position_jitter(width = 0.5, height = 0.5)) +\n  geom_smooth(method = \"lm\", se = FALSE, aes(color = \"Linear\"), size = 1, na.rm = TRUE) +\n  geom_smooth(method = lm, formula = y ~ poly(x, 3), se = FALSE, aes(color = \"Cubic\"), size = 2, linetype = \"dotted\", na.rm = TRUE) +\n  geom_smooth(method = \"lm\", formula = y ~ log(x), se = FALSE, aes(color = \"LogLinear\"), size = 1, linetype = \"dashed\", na.rm = TRUE) +\n  geom_smooth(method = \"lm\", formula = y ~ log(x) + I(log(x)^2) + I(log(x)^3), se = FALSE, aes(color = \"PolyLog\"), size = 1, na.rm = TRUE) +\n  labs(x = \"AADT\", y = \"Number of Vehicles per Crash\", title = \"Number of Vehicles per Crash by Traffic Volume\") +\n  theme_minimal() +\n  theme(\n    panel.grid = element_blank(),\n    panel.grid.major = element_line(color = \"gray\", linetype = \"dashed\"),\n    panel.grid.minor = element_blank(),\n    legend.position = \"right\"\n  ) +\n  scale_color_manual(  \n    values = c(\"Cubic\" = \"red\", \"Linear\" = \"black\", \"LogLinear\" = \"blue\", \"PolyLog\" = \"purple\"),\n    labels = c(\"Cubic\", \"Linear\", \"LogLinear\", \"PolyLog\"),\n    name = NULL  \n  ) +\n  scale_y_continuous(breaks = seq(0, 18, by = 1), minor_breaks = NULL)\n```\n\n::: {.cell-output-display}\n![](Sue-Ellen_Final_Project_DACSS_603_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n### Plot 1\n\nFrom the vantage point of the entire dataset, each model does appear to be very similar, it's no wonder the adjusted R2 were so close in value. The lines are nearly impossible to parse out here, so in the next graph I will zoom in to where the data is most centralized.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmydata %>%\n  ggplot(aes(AADT, NUMB_VEHC, na.rm = TRUE)) +\n  coord_cartesian(ylim = c(1.5, 2.5)) +\n  geom_point(color = \"skyblue\", shape = 21, size = 0.1, na.rm = TRUE, position = position_jitter(width = 0.5, height = 0.5)) +\n  geom_smooth(method = \"lm\", se = FALSE, aes(color = \"Linear\"), size = 1, na.rm = TRUE) +\n  geom_smooth(method = lm, formula = y ~ poly(x, 3), se = FALSE, aes(color = \"Cubic\"), size = 2, linetype = \"dotted\", na.rm = TRUE) +\n  geom_smooth(method = \"lm\", formula = y ~ log(x), se = FALSE, aes(color = \"LogLinear\"), size = 1, linetype = \"dashed\", na.rm = TRUE) +\n  geom_smooth(method = \"lm\", formula = y ~ log(x) + I(log(x)^2) + I(log(x)^3), se = FALSE, aes(color = \"PolyLog\"), size = 1, na.rm = TRUE) +\n  labs(x = \"AADT\", y = \"Number of Vehicles per Crash\", title = \"Number of Vehicles per Crash by Traffic Volume\") +\n  theme_minimal() +\n  theme(\n    panel.grid = element_blank(),\n    panel.grid.major = element_line(color = \"gray\", linetype = \"dashed\"),\n    panel.grid.minor = element_blank(),\n    legend.position = \"right\"\n  ) +\n  scale_color_manual(  \n    values = c(\"Cubic\" = \"red\", \"Linear\" = \"black\", \"LogLinear\" = \"blue\", \"PolyLog\" = \"purple\"),\n    labels = c(\"Cubic\", \"Linear\", \"LogLinear\", \"PolyLog\"),\n    name = NULL  \n  ) +\n  scale_y_continuous(breaks = seq(0, 10, by = 0.1), minor_breaks = NULL) + scale_x_continuous(breaks=pretty_breaks())\n```\n\n::: {.cell-output-display}\n![](Sue-Ellen_Final_Project_DACSS_603_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n### Plot 2\n\nIn order to actually see the curves and trends of these lines, I have zoomed the y-axis to coordinates (1.5, 2.5). \n\nAs we can see each line has it's own personality here, but because of how dense the data is, we cannot tell from simply looking at the data which is the best fit. I will highlight a few differences I notice initially:\n\n+ A dense concentration of the data can be observed in the very beginning of the graph with AADT numbers >50,000, spanning the full height of the adjusted y-axis. Another high concentration happens around 200,000 AADT.\n\n+ The Linear and Poly Log Models both show a high ending estimate in the last portions of their lines, ending above 2.3. \n\n+ The Log Linear and Poly Log Models both start drastically lower than the Cubic and Linear Models. \n\n+ Both the Poly log and the Cubic Models follow a similar curve in the first portion of their lines.\n\n+ The Cubic model appears to be the only model with a drop off in the final portion and has a sideways S curve.\n\nNow, these are nice observations but in order to understand whether or not they fit the data, I will look at two specific portions of the AADT data to see if the plotted trends match up with the actual data.\n\n### Examining the regression parameters through AADT quantiles\n\n::: {.cell}\n\n```{.r .cell-code}\nquantiles_0_10 <- quantile(mydata$AADT, na.rm = TRUE, probs = c(0.0, 0.01, 0.02, 0.03, .04, 0.05, 0.06, 0.07, 0.08, 0.09, .1))\nquantiles_0_10\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  0%   1%   2%   3%   4%   5%   6%   7%   8%   9%  10% \n 211 3399 3510 3936 4999 5076 7144 9069 9252 9300 9340 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmydata<-mydata%>%\n    mutate(AADT_subgroup_1 = \n               case_when(AADT >= 211   & AADT < 3399     ~ \"AADT_0-1\", \n                         AADT>=3399    & AADT < 3510     ~ \"AADT_1-2\", \n                         AADT>=3510    & AADT < 3936     ~ \"AADT_2-3\", \n                         AADT>=3936    & AADT < 4999     ~ \"AADT_3-4\", \n                         AADT>=4999    & AADT < 5076     ~ \"AADT_4-5\",\n                         AADT>=5076    & AADT < 7144     ~ \"AADT_5-6\", \n                         AADT>=7144    & AADT < 9069     ~ \"AADT_6-7\", \n                         AADT>=9069    & AADT < 9252     ~ \"AADT_7-8\", \n                         AADT>=9252    & AADT < 9300     ~ \"AADT_8-9\",\n                         AADT>=9300    & AADT < 9340     ~ \"AADT_9-10\"))\navgAADT_1 <- mydata %>% \n    group_by(AADT_subgroup_1) %>% \n    summarise(mean(NUMB_VEHC), \n              sd(NUMB_VEHC), \n              n())\ncolnames(avgAADT_1) <- c(\"AADT\", \"Y_bar\", \"s\", \"n\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\navgAADT_1 %>%\n    kbl(caption = \"Table 1: Y bar, standard deviation, and n for Number of Cars Involved per Crash by Traffic Volume 0% to 10% quantile\") %>%\n    kable_classic()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n<caption>Table 1: Y bar, standard deviation, and n for Number of Cars Involved per Crash by Traffic Volume 0% to 10% quantile</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> AADT </th>\n   <th style=\"text-align:right;\"> Y_bar </th>\n   <th style=\"text-align:right;\"> s </th>\n   <th style=\"text-align:right;\"> n </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_0-1 </td>\n   <td style=\"text-align:right;\"> 1.904110 </td>\n   <td style=\"text-align:right;\"> 0.5958478 </td>\n   <td style=\"text-align:right;\"> 292 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_1-2 </td>\n   <td style=\"text-align:right;\"> 1.935154 </td>\n   <td style=\"text-align:right;\"> 0.7488985 </td>\n   <td style=\"text-align:right;\"> 293 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_2-3 </td>\n   <td style=\"text-align:right;\"> 1.875458 </td>\n   <td style=\"text-align:right;\"> 0.7420301 </td>\n   <td style=\"text-align:right;\"> 273 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_3-4 </td>\n   <td style=\"text-align:right;\"> 2.053763 </td>\n   <td style=\"text-align:right;\"> 0.7638259 </td>\n   <td style=\"text-align:right;\"> 279 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_4-5 </td>\n   <td style=\"text-align:right;\"> 1.951368 </td>\n   <td style=\"text-align:right;\"> 0.6923402 </td>\n   <td style=\"text-align:right;\"> 329 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_5-6 </td>\n   <td style=\"text-align:right;\"> 1.866667 </td>\n   <td style=\"text-align:right;\"> 0.5468647 </td>\n   <td style=\"text-align:right;\"> 285 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_6-7 </td>\n   <td style=\"text-align:right;\"> 1.651163 </td>\n   <td style=\"text-align:right;\"> 0.6334353 </td>\n   <td style=\"text-align:right;\"> 301 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_7-8 </td>\n   <td style=\"text-align:right;\"> 1.845890 </td>\n   <td style=\"text-align:right;\"> 0.6150045 </td>\n   <td style=\"text-align:right;\"> 292 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_8-9 </td>\n   <td style=\"text-align:right;\"> 1.794355 </td>\n   <td style=\"text-align:right;\"> 0.7269037 </td>\n   <td style=\"text-align:right;\"> 248 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_9-10 </td>\n   <td style=\"text-align:right;\"> 1.881306 </td>\n   <td style=\"text-align:right;\"> 0.7222077 </td>\n   <td style=\"text-align:right;\"> 337 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:right;\"> 1.967940 </td>\n   <td style=\"text-align:right;\"> 0.7479493 </td>\n   <td style=\"text-align:right;\"> 37367 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nquantiles_90_100 <- quantile(mydata$AADT, na.rm = TRUE, probs = c(0.90, 0.91, 0.92, 0.93, .94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.0))\nquantiles_90_100\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   90%    91%    92%    93%    94%    95%    96%    97%    98%    99%   100% \n195999 197004 199278 201025 201752 201752 201752 202055 220549 225084 260824 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmydata<-mydata%>%\n    mutate(AADT_subgroup_2 = \n               case_when(AADT >= 195999  & AADT < 197004    ~ \"AADT_90-91\", \n                         AADT>=197004    & AADT < 199278    ~ \"AADT_91-92\", \n                         AADT>=199278    & AADT < 201025    ~ \"AADT_92-93\", \n                         AADT>=201025    & AADT < 201752    ~ \"AADT_93_to_96\", \n                         AADT>=201752    & AADT < 202055    ~ \"AADT_96-97\", \n                         AADT>=202055    & AADT < 220549    ~ \"AADT_97-98\", \n                         AADT>=220549    & AADT < 225084    ~ \"AADT_98-99\",\n                         AADT>=225084    & AADT < 260824    ~ \"AADT_99-100\"))\navgAADT_2 <- mydata %>% \n    group_by(AADT_subgroup_2) %>% \n    summarise(mean(NUMB_VEHC), \n              sd(NUMB_VEHC), \n              n())\ncolnames(avgAADT_2) <- c(\"AADT\", \"Y_bar\", \"s\", \"n\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\navgAADT_2 %>%\n    kbl(caption = \"Table 1: Y bar, standard deviation, and n for Number of Cars Involved per Crash by Traffic Volume 90% to 100% quantile\") %>%\n    kable_classic()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\" lightable-classic\" style='font-family: \"Arial Narrow\", \"Source Sans Pro\", sans-serif; margin-left: auto; margin-right: auto;'>\n<caption>Table 1: Y bar, standard deviation, and n for Number of Cars Involved per Crash by Traffic Volume 90% to 100% quantile</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> AADT </th>\n   <th style=\"text-align:right;\"> Y_bar </th>\n   <th style=\"text-align:right;\"> s </th>\n   <th style=\"text-align:right;\"> n </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_90-91 </td>\n   <td style=\"text-align:right;\"> 2.250814 </td>\n   <td style=\"text-align:right;\"> 0.7955910 </td>\n   <td style=\"text-align:right;\"> 307 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_91-92 </td>\n   <td style=\"text-align:right;\"> 2.337793 </td>\n   <td style=\"text-align:right;\"> 0.8332095 </td>\n   <td style=\"text-align:right;\"> 299 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_92-93 </td>\n   <td style=\"text-align:right;\"> 2.395480 </td>\n   <td style=\"text-align:right;\"> 0.9302871 </td>\n   <td style=\"text-align:right;\"> 177 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_93_to_96 </td>\n   <td style=\"text-align:right;\"> 2.319403 </td>\n   <td style=\"text-align:right;\"> 0.8349117 </td>\n   <td style=\"text-align:right;\"> 335 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_96-97 </td>\n   <td style=\"text-align:right;\"> 2.335025 </td>\n   <td style=\"text-align:right;\"> 0.8416971 </td>\n   <td style=\"text-align:right;\"> 788 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_97-98 </td>\n   <td style=\"text-align:right;\"> 2.234097 </td>\n   <td style=\"text-align:right;\"> 0.7961372 </td>\n   <td style=\"text-align:right;\"> 393 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_98-99 </td>\n   <td style=\"text-align:right;\"> 2.169096 </td>\n   <td style=\"text-align:right;\"> 0.8587227 </td>\n   <td style=\"text-align:right;\"> 343 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AADT_99-100 </td>\n   <td style=\"text-align:right;\"> 2.109756 </td>\n   <td style=\"text-align:right;\"> 0.6738971 </td>\n   <td style=\"text-align:right;\"> 164 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:right;\"> 1.937423 </td>\n   <td style=\"text-align:right;\"> 0.7317028 </td>\n   <td style=\"text-align:right;\"> 37490 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n### Explanation of Model Choice\nBy comparing the shape of the models to the shape of the Ybar values of the Number of Vehicles per Crash in the two tables above, we can see that the cubic model does indeed offer the best fit. In the first 10% quantile (Table 1), the Number of Vehicles per Crash reflects some high to low variance from Ybar 1.9 at the 1% quantile to 1.65 at the 7% quantile. This can account for the dip curve in the cubic model as the line attempts to keep up with the variation in Ybar values of the Number of Vehicles per Crash. In the final 90%-100% quantile of the AADT (Table 2), the Number of Vehicles per Crash increases and then tapers off. \n\nWhile the linear model is most easy to interpret and does okay with representing most of the data, it is too smooth and does not account for the way the Number of Vehicles per Crash changes in different quantiles of the AADT data. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(Cubic_model, vcov. = vcovHC, type = \"HC1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3), data = mydata)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.2712 -0.2547  0.0928  0.1334 16.1162 \n\nCoefficients:\n                           Estimate              Std. Error t value\n(Intercept)  1.92317068910772892565  0.01134985598478604682 169.445\nAADT        -0.00000336927973276718  0.00000056285169801682  -5.986\nI(AADT^2)    0.00000000005085065598  0.00000000000586129212   8.676\nI(AADT^3)   -0.00000000000000012890  0.00000000000000001679  -7.677\n                        Pr(>|t|)    \n(Intercept) < 0.0000000000000002 ***\nAADT          0.0000000021743937 ***\nI(AADT^2)   < 0.0000000000000002 ***\nI(AADT^3)     0.0000000000000167 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.7411 on 29372 degrees of freedom\n  (10920 observations deleted due to missingness)\nMultiple R-squared:  0.03737,\tAdjusted R-squared:  0.03727 \nF-statistic:   380 on 3 and 29372 DF,  p-value: < 0.00000000000000022\n```\n:::\n:::\n\n### Cubic Model\n\nAs the summary indicates, **the coefficients are all statistically significant at the 99.9% confidence level**. The f-statistic is also significant at the 99.9% confidence level. With such extremely small p-values, we can reject the null hypothesis that AADT has no effect on the Number of Vehicles per Crash.\n\nThis Cubic Model can be written as: \n\n$$\n\\widehat{VEHICLES per CRASH} = 1.923- 3.369e^{-6} \\times \\text{AADT} + 5.085e^{-11} \\times \\text{I}(AADT ^{2}) - 1.29e^{-16} \\times \\text{I}(AADT ^{3})\n$$\n\n# Multiple Regression Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod1 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  , data = mydata)\nmod2 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT , data = mydata)\nmod3 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT + Distracted_Binary , data = mydata)\nmod4 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT + Distracted_Binary + YEAR , data = mydata)\nmod5 <- lm(NUMB_VEHC ~ YEAR , data = mydata)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncoefficients_df <- bind_rows(\n mod1 =tidy(mod1, conf.int = TRUE),\n mod2 =tidy(mod2, conf.int = TRUE), \n mod3 =tidy(mod3, conf.int = TRUE), \n mod4 =tidy(mod4, conf.int = TRUE), \n mod5 =tidy(mod5, conf.int = TRUE))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrob_se <- list(sqrt(diag(vcovHC(mod1, type = \"HC1\"))),\nsqrt(diag(vcovHC(mod2, type = \"HC1\"))),\nsqrt(diag(vcovHC(mod3, type = \"HC1\"))),\nsqrt(diag(vcovHC(mod4, type = \"HC1\"))),\nsqrt(diag(vcovHC(mod5, type = \"HC1\"))))\n```\n:::\n\n\n### Results of Multiple Regression Models\n\n\n```{.r .cell-code}\nstargazer(mod1, mod2, mod3, mod4, mod5,  \ntitle = \"Regressions Using Boston Crash Data\",\ntype = \"html\",\ndigits = 12,\nheader = FALSE,\nse = rob_se,\nobject.names = TRUE,\nmodel.numbers = FALSE,\ncolumn.labels = c(\"(I)\", \"(II)\", \"(III)\", \"(IV)\", \"(V)\"))\n```\n\n\n<table style=\"text-align:center\"><caption><strong>Regressions Using Boston Crash Data</strong></caption>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td colspan=\"5\"><em>Dependent variable:</em></td></tr>\n<tr><td></td><td colspan=\"5\" style=\"border-bottom: 1px solid black\"></td></tr>\n<tr><td style=\"text-align:left\"></td><td colspan=\"5\">NUMB_VEHC</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(I)</td><td>(II)</td><td>(III)</td><td>(IV)</td><td>(V)</td></tr>\n<tr><td style=\"text-align:left\"></td><td>mod1</td><td>mod2</td><td>mod3</td><td>mod4</td><td>mod5</td></tr>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">AADT</td><td>-0.000003369280<sup>***</sup></td><td>-0.000003827819<sup>***</sup></td><td>-0.000003955453<sup>***</sup></td><td>-0.000003941358<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.000000568261)</td><td>(0.000000639009)</td><td>(0.000000657419)</td><td>(0.000000658412)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(AADT2)</td><td>0.000000000051<sup>***</sup></td><td>0.000000000046<sup>***</sup></td><td>0.000000000048<sup>***</sup></td><td>0.000000000048<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.000000000006)</td><td>(0.000000000007)</td><td>(0.000000000007)</td><td>(0.000000000007)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(AADT3)</td><td>-0.000000000000<sup>***</sup></td><td>-0.000000000000<sup>***</sup></td><td>-0.000000000000<sup>***</sup></td><td>-0.000000000000<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.000000000000)</td><td>(0.000000000000)</td><td>(0.000000000000)</td><td>(0.000000000000)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">SPEED_LIMIT</td><td></td><td>0.006950989000<sup>***</sup></td><td>0.006849752000<sup>***</sup></td><td>0.006852459000<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td>(0.000663658000)</td><td>(0.000684122200)</td><td>(0.000684025200)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Distracted_Binary</td><td></td><td></td><td>0.095911550000<sup>***</sup></td><td>0.095924430000<sup>***</sup></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.015868680000)</td><td>(0.015864080000)</td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">YEAR</td><td></td><td></td><td></td><td>-0.001347637000</td><td>0.005339553000<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(0.001786041000)</td><td>(0.001330296000)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>1.923171000000<sup>***</sup></td><td>1.721722000000<sup>***</sup></td><td>1.734725000000<sup>***</sup></td><td>4.454296000000</td><td>-8.810883000000<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.010939580000)</td><td>(0.023457830000)</td><td>(0.024265720000)</td><td>(3.604010000000)</td><td>(2.683741000000)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>29,376</td><td>23,769</td><td>22,446</td><td>22,446</td><td>40,296</td></tr>\n<tr><td style=\"text-align:left\">R<sup>2</sup></td><td>0.037365320000</td><td>0.042291360000</td><td>0.044150340000</td><td>0.044174140000</td><td>0.000401593900</td></tr>\n<tr><td style=\"text-align:left\">Adjusted R<sup>2</sup></td><td>0.037267000000</td><td>0.042130160000</td><td>0.043937360000</td><td>0.043918560000</td><td>0.000376786200</td></tr>\n<tr><td style=\"text-align:left\">Residual Std. Error</td><td>0.741077900000 (df = 29372)</td><td>0.755093800000 (df = 23764)</td><td>0.753679200000 (df = 22440)</td><td>0.753686600000 (df = 22439)</td><td>0.743992400000 (df = 40294)</td></tr>\n<tr><td style=\"text-align:left\">F Statistic</td><td>380.031400000000<sup>***</sup> (df = 3; 29372)</td><td>262.348000000000<sup>***</sup> (df = 4; 23764)</td><td>207.299100000000<sup>***</sup> (df = 5; 22440)</td><td>172.838900000000<sup>***</sup> (df = 6; 22439)</td><td>16.188320000000<sup>***</sup> (df = 1; 40294)</td></tr>\n<tr><td colspan=\"6\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td colspan=\"5\" style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n\n## Linear Hypothesis Test\n#### mod1\n\n::: {.cell}\n\n```{.r .cell-code}\n#mod1 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  , data = mydata)\n\nlinearHypothesis(mod1, \"AADT=0\",\n                 vcov. = vcovHC(mod1, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"29373\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"29372\",\"2\":\"1\",\"3\":\"35.15432\",\"4\":\"0.000000003079856\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod1, \"I(AADT^2)=0\",\n                 vcov. = vcovHC(mod1, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"29373\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"29372\",\"2\":\"1\",\"3\":\"72.02492\",\"4\":\"0.00000000000000002223438\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod1, \"I(AADT^3)=0\",\n                 vcov. = vcovHC(mod1, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"29373\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"29372\",\"2\":\"1\",\"3\":\"55.35238\",\"4\":\"0.0000000000001035029\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod1, c(\"I(AADT^2)=0\", \"I(AADT^3)=0\"),\n                 vcov. = vcovHC(mod1, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"29374\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"29372\",\"2\":\"2\",\"3\":\"45.51457\",\"4\":\"0.00000000000000000001835857\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n#### mod2\n\n::: {.cell}\n\n```{.r .cell-code}\n#mod2 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT , data = mydata)\nlinearHypothesis(mod2, \"SPEED_LIMIT=0\",\n                 vcov. = vcovHC(mod2, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"23765\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"23764\",\"2\":\"1\",\"3\":\"109.6995\",\"4\":\"0.0000000000000000000000001296683\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n#### mod3\n\n::: {.cell}\n\n```{.r .cell-code}\n#mod3 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT + Distracted_Binary , data = mydata)\nlinearHypothesis(mod3, \"AADT=0\",\n                 vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22441\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22440\",\"2\":\"1\",\"3\":\"36.19998\",\"4\":\"0.000000001808322\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod3, c(\"I(AADT^2)=0\", \"I(AADT^3)=0\"),\n                 vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22442\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22440\",\"2\":\"2\",\"3\":\"31.6842\",\"4\":\"0.00000000000001816011\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod3, \"SPEED_LIMIT=0\",\n                 vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22441\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22440\",\"2\":\"1\",\"3\":\"100.2495\",\"4\":\"0.00000000000000000000001505587\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod3, \"Distracted_Binary=0\",\n                 vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22441\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22440\",\"2\":\"1\",\"3\":\"36.53088\",\"4\":\"0.000000001526377\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod3, c(\"SPEED_LIMIT=0\", \"Distracted_Binary=0\"),\n                 vcov. = vcovHC(mod3, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22442\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22440\",\"2\":\"2\",\"3\":\"69.71611\",\"4\":\"0.0000000000000000000000000000006551746\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n#### mod4\n\n::: {.cell}\n\n```{.r .cell-code}\n#mod4 <- lm(NUMB_VEHC ~ AADT + I(AADT^2) + I(AADT^3)  + SPEED_LIMIT + Distracted_Binary + YEAR , data = mydata)\nlinearHypothesis(mod4, \"AADT=0\",\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22440\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"1\",\"3\":\"35.83407\",\"4\":\"0.000000002181223\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, c(\"I(AADT^2)=0\", \"I(AADT^3)=0\"),\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22441\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"2\",\"3\":\"31.68607\",\"4\":\"0.0000000000000181263\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, \"SPEED_LIMIT=0\",\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22440\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"1\",\"3\":\"100.3572\",\"4\":\"0.0000000000000000000000142626\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, \"Distracted_Binary=0\",\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22440\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"1\",\"3\":\"36.56189\",\"4\":\"0.000000001502325\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, c(\"SPEED_LIMIT=0\", \"Distracted_Binary=0\"),\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22441\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"2\",\"3\":\"69.7793\",\"4\":\"0.0000000000000000000000000000006152983\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, \"YEAR=0\",\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22440\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"1\",\"3\":\"0.569329\",\"4\":\"0.4505336\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nlinearHypothesis(mod4, c(\"SPEED_LIMIT=0\", \"Distracted_Binary=0\",\"YEAR=0\"),\n                 vcov. = vcovHC(mod4, type = \"HC1\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Res.Df\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Df\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"22442\",\"2\":\"NA\",\"3\":\"NA\",\"4\":\"NA\",\"_rn_\":\"1\"},{\"1\":\"22439\",\"2\":\"3\",\"3\":\"46.6101\",\"4\":\"0.000000000000000000000000000005092471\",\"_rn_\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n# Explanation of Multiple Regression Model Choice\n\n\nIn order to explain the relationship between the Number of Vehicles per Crash and Traffic Volume (AADT), I wrote 5 regression models including additional the additional variables: speed limit, distracted driver, and year(of crash). \nModels 1 through 3 exhibit robust significance both in terms of individual coefficients and the overall F-statistics. However, models 4 and 5 demonstrate that the particular year of the accident has little to no statistical significance when regressed with other regressors. When isolated in a regression against the Number of Vehicles per Crash, Year has a high level of significance, but has a very small adjusted R2. \n\nConcerning adjusted R-squared values, F-statistics and p-values, model 3 is the best fit. The formula for model 3 is as follows:\n\n$$\n\\begin{align*}\n\\widehat{\\text{VEHICLES per CRASH}} &= 1.7347 - 3.369e^{-6} \\times \\text{AADT} \\\\\n&\\quad + 4.8e^{-11} \\times \\text{I}(AADT^2) - 1.214e^{-16} \\times \\text{I}(AADT^3) \\\\\n&\\quad + 0.00685 \\times \\text{SPEED\\_LIMIT} + 0.095 \\times \\text{Distracted\\_Binary}\n\\end{align*}$$\n\nAmong the variables considered and analyzed, AADT (Average Annual Daily Traffic) has a significant affect on vehicles per crash across all models. In model 3, while holding I(AADT^2), I(AADT^3), SPEED_LIMIT, and Distracted_Binary constant, a 1 unit change in AADT results in a -0.00000396 change in the Number of Vehicles per Crash.  While the coefficient is negative, and indicates that an increase in AADT results in a decrease in the Number of Vehicles per Crash, the interpretation needs to be slightly more nuanced. Due to the variance in how the regressor behaves at different levels, the inclusions of all levels of the cubic model are important in deciphering an accurate estimate.\n\nThe inclusion, through the cubic model, squared and cubed terms for AADT, represented by I(AADT^2) and I(AADT^3), in models 1 through 4 contribute to the model's explanatory power. These higher-order terms capture those potential non-linear relationships between AADT and the dependent variable. In all models, I(AADT^2) and I(AADT^3) coefficients are statistically significant, which means the curvature of the relationship between AADT and the number of vehicles per crash is also relevant to the model. So, while AADT indicates a decrease in the number of vehicles per crash, the higher-order terms of the cubic model do not follow this linear pattern and will indicate increases along different levels of AADT, as we saw earlier on Plot 2.\n\nWhen included in the models, speed limit also demonstrates statistical significance with a consistently positive coefficient estimate. This implies that higher speed limits are associated with an increase in the number of vehicles per crash. The binary variable for Distracted Drivers, when included in models 3 and 4 and also demonstrated a significant positive effect on the number of vehicles per crash. In model 3 with all other variables (AADT, I(AADT2)I(AADT2), I(AADT3)I(AADT3), SPEED_LIMIT) held constant, the coefficient estimate for Distracted_Binary is 0.0959. This means that for every one-unit increase in the Distracted_Binary variable while keeping all other factors constant, the expected change in the Number of Vehicles per Crash is an increase of 0.0959. This data suggests that crashes involving distracted driving tend to involve more vehicles. \n\nThe adjusted R2 for this model is 0.04393736, which means that this model accounts for 4.4% of the variation in Number of Vehicles per Crash. The remaining variability (95.6%) is attributed to other factors not considered in the model. While model 3 offers insight into the relationship between the number of vehicles per crash, AADT, speed limit, and distracted drivers there are most certainly other factors not included that influence crash outcomes. \n\nWhat I had initially anticipated with this project was that the Number of Vehicles per Crash were increasing over time. I was only able to analyze the data over 10 years, and looking here at the fifth model we can see how small the adjusted R2 is for lm(NUMB_VEHC ~ YEAR), with Year only accounting for .04% of the variation in the Number of Vehicles per year. The F-statistic with a value of 16.19 and an associated p-value of 5.745e-05, indicate the regression is highly statistically significant, with strong evidence to suggest that the model as a whole has explanatory power and there is evidence of a relationship between Number of Vehicles per Crash and Year.\n\nHowever, when regressed with the main regressor for this report, AADT (mod4), Year loses its significance as does the Number of Vehicles per Crash. The F statistic still remains significant in mod5, but the loss of significance of the Year and Number of Vehicles per Crash lead me to believe Year is not the most beneficial regressor in considering Number of Vehicles per Crash without more extensive data. Continuing on this trend of discounting year as a beneficial regressor, when performing a linear hypothesis where Year is set to 0, the p-value increases to greater than the significance level of 0.05. In this context, its reasonable to conclude that Year does not have a substantial impact on the Number of Vehicles per Crash.\n\n# Limitations\n\n##### Scope of Data\nThe comprehensive cleaning of data for such a large dataset within a limited time frame, creates some challenges. This is a project that could take years of parsing through the original annual Crash datasets produced by MASS DOT. Some data present in the original dataset that could provide more insight into the exploration of the Number of Vehicles per Crash include: text-based columns that categorize the contributing factors to a crash, individualdriver demographics, weather and road condition data and the massive field of geospatial data. The substantial depth and breadth of this dataset offer the potential for extracting robust analytical, potentially exciting data. \n\n##### Data Cleaning\nOne limitation within the data itself is that there are mistakes. For instance, when initially cleaning the Speed Limit column, I noticed outliers like -555 or 1 mph that could not have been real numbers. They might have meant something to the person entering the data, but I could not glean any insight, so I removed this data. Additionally there was AADT data that I also removed based off of an intuition that it was not accurate. I removed AADT data and returned them to \"NA\" if the AADT_Year column (which notes what year the AADT data was collected) were odd years (like 1897), or included less than 100 readings per year. Cleaning the data in this way can remove outliers that are nonsensical (like -555 mph) but can also remove outliers that are simply outliers and completely accurate. \n\n##### AADT Year \nThe AADT values were most recently calculated in 2020 and 2018. There are no AADT values for the past 3 years.Unfortunately, due to the nature of the cleaning process, I was unable to completely organize data by the year the AADT was derived. If I was able to disaggregate this data, there may have been more interesting data analysis possible. However, the MassDot routinely uses AADT data from previous years when referring to crashes, resulting in 5+ years difference between the recorded AADT and the crash.\n\n\n\n\n# Bibliography\n\nIMPACT. Data Extract. 2023. https://apps.impact.dot.state.ma.us/cdp/home\n\nRStudio Team (2020). RStudio: Integrated Development for R. RStudio, PBC, Boston, MA URL \nhttp://www.rstudio.com/.",
    "supporting": [
      "Sue-Ellen_Final_Project_DACSS_603_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\r\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\r\n<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}