<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matt Eckstein">
<meta name="dcterms.date" content="2023-08-18">

<title>Class Project Assignment 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/DACSS_Round_Network.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Class Project Assignment 2">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://dacss.github.io/603_Summer2023_Sec_1/posts/Eckstein_class_project_assignment_2_files/figure-html/unnamed-chunk-8-1.png">
<meta name="twitter:creator" content="@UMassDACSS">
<meta name="twitter:site" content="@UMassDACSS">
<meta name="twitter:image-height" content="960">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/UMass White Wordmark Horiz.png" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://dacss.github.io/603_Summer2023_Sec_1/" rel="" target="">
 <span class="menu-text">Summer 2023 Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html" rel="" target="">
 <span class="menu-text">Contributors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://umass.edu/sbs/dacss" rel="" target="">
 <span class="menu-text">DACSS</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://dacss.github.io/603_Summer2023_Sec_1/" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#multiple-regression-models" id="toc-multiple-regression-models" class="nav-link active" data-scroll-target="#multiple-regression-models">1. Multiple regression models</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Class Project Assignment 2</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">Matt Eckstein</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matt Eckstein </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 18, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="multiple-regression-models" class="level1">
<h1>1. Multiple regression models</h1>
<p><span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox
\]</span></p>
<p><span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × netsentiment
\]</span> <span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × bordruua
\]</span> <span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × netsentiment + \beta _{3} × bordruua
\]</span> <span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × strongru
\]</span> <span class="math display">\[
NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × closewest
\]</span></p>
<p>#2a.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Eckstein_data/Orthodoxy_and_US_leadership_cleaned.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 17 Columns: 18
-- Column specification --------------------------------------------------------
Delimiter: ","
chr  (4): Country, Estimated 2010
Catholic Population, Estimated 2010
Protes...
dbl (12): bordru, bordua, bordruua, pctox, approve, disapprove, dkref, 20212...
num  (2): Estimated 2010
Orthodox Population, totalpop

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>pctox <span class="ot">&lt;-</span> data<span class="sc">$</span>pctox <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Country          Estimated 2010\nCatholic Population
 Length:17          Length:17                          
 Class :character   Class :character                   
 Mode  :character   Mode  :character                   
                                                       
                                                       
                                                       
 Estimated 2010\nProtestant Population Estimated 2010\nOrthodox Population
 Length:17                             Min.   :    20000                  
 Class :character                      1st Qu.:   250000                  
 Mode  :character                      Median :  2680000                  
                                       Mean   : 11231176                  
                                       3rd Qu.:  6730000                  
                                       Max.   :101450000                  
 Estimated 2010 Population of Other Christians    totalpop        
 Length:17                                     Min.   :  1331535  
 Class :character                              1st Qu.:  3678186  
 Mode  :character                              Median :  7291436  
                                               Mean   : 18790613  
                                               3rd Qu.: 11033783  
                                               Max.   :143242599  
     bordru           bordua          bordruua          pctox      
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   : 0.20  
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.: 5.42  
 Median :0.0000   Median :0.0000   Median :1.0000   Median :70.82  
 Mean   :0.4118   Mean   :0.3529   Mean   :0.5882   Mean   :51.39  
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:90.96  
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :99.56  
    approve         disapprove         dkref          202122chg  
 Min.   :0.0400   Min.   :0.0800   Min.   :0.1200   Min.   :-31  
 1st Qu.:0.2700   1st Qu.:0.2900   1st Qu.:0.1900   1st Qu.: -9  
 Median :0.3300   Median :0.3400   Median :0.2000   Median : -3  
 Mean   :0.3653   Mean   :0.3918   Mean   :0.2424   Mean   :  0  
 3rd Qu.:0.4100   3rd Qu.:0.4700   3rd Qu.:0.3000   3rd Qu.:  9  
 Max.   :0.8000   Max.   :0.7700   Max.   :0.4200   Max.   : 30  
   netapprove         strongru    closewest      netsentiment   
 Min.   :-73.000   Min.   :22   Min.   :48.00   Min.   :-30.00  
 1st Qu.:-21.000   1st Qu.:40   1st Qu.:61.00   1st Qu.: -8.00  
 Median :  2.000   Median :52   Median :66.00   Median : 18.00  
 Mean   : -2.647   Mean   :53   Mean   :64.76   Mean   : 11.76  
 3rd Qu.: 14.000   3rd Qu.:61   3rd Qu.:69.00   3rd Qu.: 30.00  
 Max.   : 72.000   Max.   :85   Max.   :82.00   Max.   : 40.00  </code></pre>
</div>
</div>
<p>#2b. Customizing variable names</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Most of my variable names are good as they are; though, here, I create and name additional variables that will be helpful in my analysis </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector to store the oxbucket values</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>oxbucket <span class="ot">&lt;-</span> <span class="fu">character</span>(<span class="fu">length</span>(data<span class="sc">$</span>pctox))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign values to oxbucket based on pctox</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"&lt;2%"</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="st">"2-5%"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="st">"5-10%"</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">25</span>] <span class="ot">&lt;-</span> <span class="st">"10-25%"</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">50</span>] <span class="ot">&lt;-</span> <span class="st">"25-50%"</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">50</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">75</span>] <span class="ot">&lt;-</span> <span class="st">"50-75%"</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">75</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">100</span>] <span class="ot">&lt;-</span> <span class="st">"75-100%"</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the oxbucket variable to the data frame</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>oxbucket <span class="ot">&lt;-</span> oxbucket</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>avgs <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bordruua, oxbucket) <span class="sc">%&gt;%</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(netapprove),</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sd</span>(netapprove),</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'bordruua'. You can override using the
`.groups` argument.</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>border <span class="ot">&lt;-</span> avgs <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(bordruua <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>noborder <span class="ot">&lt;-</span> avgs <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(bordruua <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(border) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Border_war"</span>, <span class="st">"Percent_orthodox"</span>, <span class="st">"mean_net_approval"</span>, <span class="st">"SD_net_approval"</span>, <span class="st">"number"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(noborder) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Border_war"</span>, <span class="st">"Percent_orthodox"</span>, <span class="st">"mean_net_approval"</span>, <span class="st">"SD_net_approval"</span>, <span class="st">"number"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>#2c. Designating regressors and reporting means and SDs</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pctox"</span>, <span class="st">"netsentiment"</span>, <span class="st">"bordruua"</span>, <span class="st">"strongru"</span>, <span class="st">"closewest"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">allvars_mean =</span> <span class="fu">sapply</span>(data[, vars], mean),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="at">allvars_sd =</span> <span class="fu">sapply</span>(data[, vars], sd))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             allvars_mean allvars_sd
pctox          51.3911765 40.9699643
netsentiment   11.7647059 22.5652648
bordruua        0.5882353  0.5072997
strongru       53.0000000 18.2688259
closewest      64.7647059  8.0972944</code></pre>
</div>
</div>
<p>#2d. Basic linear equation</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox)

Coefficients:
(Intercept)   data$pctox  
     9.8367      -0.2429  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.633 -22.724   0.684  21.560  62.484 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   9.8367    14.3169   0.687    0.503
data$pctox   -0.2429     0.2204  -1.102    0.288

Residual standard error: 36.11 on 15 degrees of freedom
Multiple R-squared:  0.07494,   Adjusted R-squared:  0.01327 
F-statistic: 1.215 on 1 and 15 DF,  p-value: 0.2877</code></pre>
</div>
</div>
<p>#2e. (Prompt 2e is identical to prompt 2d; see answer 2d)</p>
<p>#2f. Linear-log model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>Linearlog_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(netapprove <span class="sc">~</span> <span class="fu">log</span>(pctox), <span class="at">data =</span> data)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>Linearlog_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = netapprove ~ log(pctox), data = data)

Coefficients:
(Intercept)   log(pctox)  
      9.870       -4.233  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Linearlog_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = netapprove ~ log(pctox), data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-64.839 -17.429  -2.699  18.278  63.305 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    9.870     15.581   0.633    0.536
log(pctox)    -4.233      4.341  -0.975    0.345

Residual standard error: 36.41 on 15 degrees of freedom
Multiple R-squared:  0.05961,   Adjusted R-squared:  -0.003086 
F-statistic: 0.9508 on 1 and 15 DF,  p-value: 0.345</code></pre>
</div>
</div>
<p>#2g. Cubic model</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>cubic_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(netapprove <span class="sc">~</span> <span class="fu">I</span>(pctox) <span class="sc">+</span> <span class="fu">I</span>(pctox<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(pctox<span class="sc">^</span><span class="dv">3</span>), <span class="at">data =</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>data)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>cubic_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = netapprove ~ I(pctox) + I(pctox^2) + I(pctox^3), 
    data = data)

Coefficients:
(Intercept)     I(pctox)   I(pctox^2)   I(pctox^3)  
 15.0842278   -0.5664232   -0.0102011    0.0001475  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cubic_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = netapprove ~ I(pctox) + I(pctox^2) + I(pctox^3), 
    data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-49.206 -26.290  -4.445  10.840  71.997 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 15.0842278 19.7419850   0.764    0.458
I(pctox)    -0.5664232  2.6229253  -0.216    0.832
I(pctox^2)  -0.0102011  0.0659589  -0.155    0.879
I(pctox^3)   0.0001475  0.0004444   0.332    0.745

Residual standard error: 37.58 on 13 degrees of freedom
Multiple R-squared:  0.132, Adjusted R-squared:  -0.06826 
F-statistic: 0.6592 on 3 and 13 DF,  p-value: 0.5916</code></pre>
</div>
</div>
<p>#2h. Plot the observations and add the linear, log-linear, and cubic models</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">plot</span>(data<span class="sc">$</span>pctox, data<span class="sc">$</span>netapprove,</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">"Percent Orthodox"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">"Net Approval of US Leadership"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>, <span class="dv">100</span>))</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>order_id <span class="ot">&lt;-</span> <span class="fu">order</span>(data<span class="sc">$</span>pctox)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(data<span class="sc">$</span>pctox[order_id],</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted</span>(Linearlog_model)[order_id],</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> data<span class="sc">$</span>pctox[order_id],</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="fu">fitted</span>(cubic_model)[order_id],</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"orange"</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a><span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Linear"</span>, <span class="st">"Linear-Log"</span>, <span class="st">"Cubic"</span>),</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="fu">c</span>(<span class="st">"Black"</span>, <span class="st">"darkgreen"</span>, <span class="st">"orange"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Eckstein_class_project_assignment_2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>#3:</p>
<p>Visually speaking, none of the three representations (linear, linear-log, or cubic) is drastically different from the other two. The linear and linear-log models are extremely similar except for a slight upward hook at the left side of the graph in the linear-log model, and this makes the model neither noticeably better nor noticeably worse than the linear model.</p>
<p>The cubic model arguably follows the points slightly better than the other two models, but this is thanks to a dip in the model line at around 70% Orthodox that appears to be driven in large part by one point (Russia’s) with the lowest net approval of US leadership of any country in the dataset. Given the apparent ability of the curve to be noticeably influenced by this single point, it is likely that this model is overfitted. As such, there is no apparent advantage to choosing a non-linear model for this analysis.</p>
<p>#4a.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>netsentiment)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>bordruua)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>bordruua <span class="sc">+</span> data<span class="sc">$</span>netsentiment)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>strongru)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>closewest)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox)

Coefficients:
(Intercept)   data$pctox  
     9.8367      -0.2429  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$netsentiment)

Coefficients:
      (Intercept)         data$pctox  data$netsentiment  
         -27.9698             0.1812             1.3610  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$bordruua)

Coefficients:
  (Intercept)     data$pctox  data$bordruua  
      -5.9958        -0.2082        23.8848  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$bordruua + data$netsentiment)

Coefficients:
      (Intercept)         data$pctox      data$bordruua  data$netsentiment  
         -27.4665             0.1861            -1.7612             1.3849  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$strongru)

Coefficients:
  (Intercept)     data$pctox  data$strongru  
      72.0073         0.1514        -1.5553  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$closewest)

Coefficients:
   (Intercept)      data$pctox  data$closewest  
     -125.7743         -0.1266          2.0016  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.633 -22.724   0.684  21.560  62.484 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)   9.8367    14.3169   0.687    0.503
data$pctox   -0.2429     0.2204  -1.102    0.288

Residual standard error: 36.11 on 15 degrees of freedom
Multiple R-squared:  0.07494,   Adjusted R-squared:  0.01327 
F-statistic: 1.215 on 1 and 15 DF,  p-value: 0.2877</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$netsentiment)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.565 -17.029  -7.454   5.419  64.628 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)       -27.9698    14.0341  -1.993  0.06613 . 
data$pctox          0.1812     0.1907   0.950  0.35831   
data$netsentiment   1.3610     0.3463   3.930  0.00151 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 25.78 on 14 degrees of freedom
Multiple R-squared:  0.5602,    Adjusted R-squared:  0.4973 
F-statistic: 8.915 on 2 and 14 DF,  p-value: 0.003184</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$bordruua)

Residuals:
    Min      1Q  Median      3Q     Max 
-76.142 -10.584  -5.222  10.310  54.936 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)    -5.9958    18.0802  -0.332    0.745
data$pctox     -0.2082     0.2157  -0.966    0.351
data$bordruua  23.8848    17.4168   1.371    0.192

Residual standard error: 35.1 on 14 degrees of freedom
Multiple R-squared:  0.1845,    Adjusted R-squared:  0.06798 
F-statistic: 1.584 on 2 and 14 DF,  p-value: 0.2399</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$bordruua + data$netsentiment)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.476 -15.797  -7.179   5.867  64.086 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)       -27.4665    15.2018  -1.807  0.09398 . 
data$pctox          0.1861     0.2024   0.919  0.37463   
data$bordruua      -1.7612    15.3332  -0.115  0.91031   
data$netsentiment   1.3849     0.4152   3.336  0.00536 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 26.74 on 13 degrees of freedom
Multiple R-squared:  0.5606,    Adjusted R-squared:  0.4592 
F-statistic: 5.529 on 3 and 13 DF,  p-value: 0.0114</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$strongru)

Residuals:
    Min      1Q  Median      3Q     Max 
-23.523 -17.892  -3.459   3.915  73.318 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)    72.0073    21.5210   3.346  0.00480 **
data$pctox      0.1514     0.2062   0.734  0.47502   
data$strongru  -1.5553     0.4624  -3.363  0.00464 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27.8 on 14 degrees of freedom
Multiple R-squared:  0.4884,    Adjusted R-squared:  0.4153 
F-statistic: 6.681 on 2 and 14 DF,  p-value: 0.009179</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = data$netapprove ~ data$pctox + data$closewest)

Residuals:
    Min      1Q  Median      3Q     Max 
-48.347 -22.549  -6.299  16.072  61.334 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)    -125.7743    74.5317  -1.688   0.1136  
data$pctox       -0.1266     0.2139  -0.592   0.5633  
data$closewest    2.0016     1.0825   1.849   0.0857 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 33.51 on 14 degrees of freedom
Multiple R-squared:  0.2565,    Adjusted R-squared:  0.1503 
F-statistic: 2.415 on 2 and 14 DF,  p-value: 0.1256</code></pre>
</div>
</div>
<p>#4b.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>rob_se <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model2, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model3, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model4, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model5, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model6, <span class="at">type =</span> <span class="st">"HC1"</span>))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>#4c.</p>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<pre><code>
Please cite as: </code></pre>
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model, model2, model3,</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model4, model5, model6,</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Regressions of Orthodox Christian Religious ID and Net Approval of US Leadership"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="at">type =</span> <span class="st">"html"</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="at">header =</span> <span class="cn">FALSE</span>,</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="at">se =</span> rob_se,</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="at">object.names =</span> <span class="cn">TRUE</span>,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="at">model.numbers =</span> <span class="cn">FALSE</span>,</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a><span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"(I)"</span>, <span class="st">"(II)"</span>, <span class="st">"(III)"</span>, <span class="st">"(IV)"</span>, <span class="st">"(V)"</span>, <span class="st">"(VI)"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>

<table style="text-align:center">
<caption>
<strong>Regressions of Orthodox Christian Religious ID and Net Approval of US Leadership</strong>
</caption>
<tbody><tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
netapprove
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(I)
</td>
<td>
(II)
</td>
<td>
(III)
</td>
<td>
(IV)
</td>
<td>
(V)
</td>
<td>
(VI)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
model
</td>
<td>
model2
</td>
<td>
model3
</td>
<td>
model4
</td>
<td>
model5
</td>
<td>
model6
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
pctox
</td>
<td>
-0.243
</td>
<td>
0.181
</td>
<td>
-0.208
</td>
<td>
0.186
</td>
<td>
0.151
</td>
<td>
-0.127
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.207)
</td>
<td>
(0.131)
</td>
<td>
(0.189)
</td>
<td>
(0.153)
</td>
<td>
(0.116)
</td>
<td>
(0.183)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
netsentiment
</td>
<td>
</td>
<td>
1.361<sup>***</sup>
</td>
<td>
</td>
<td>
1.385<sup>***</sup>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.318)
</td>
<td>
</td>
<td>
(0.287)
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
bordruua
</td>
<td>
</td>
<td>
</td>
<td>
23.885
</td>
<td>
-1.761
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(15.950)
</td>
<td>
(11.926)
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
strongru
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-1.555<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.514)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
closewest
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
2.002<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.780)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
9.837
</td>
<td>
-27.970<sup>***</sup>
</td>
<td>
-5.996
</td>
<td>
-27.466<sup>**</sup>
</td>
<td>
72.007<sup>***</sup>
</td>
<td>
-125.774<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(12.324)
</td>
<td>
(10.611)
</td>
<td>
(11.042)
</td>
<td>
(11.524)
</td>
<td>
(25.230)
</td>
<td>
(52.850)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
17
</td>
<td>
17
</td>
<td>
17
</td>
<td>
17
</td>
<td>
17
</td>
<td>
17
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.075
</td>
<td>
0.560
</td>
<td>
0.184
</td>
<td>
0.561
</td>
<td>
0.488
</td>
<td>
0.257
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.013
</td>
<td>
0.497
</td>
<td>
0.068
</td>
<td>
0.459
</td>
<td>
0.415
</td>
<td>
0.150
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
36.114 (df = 15)
</td>
<td>
25.776 (df = 14)
</td>
<td>
35.098 (df = 14)
</td>
<td>
26.735 (df = 13)
</td>
<td>
27.801 (df = 14)
</td>
<td>
33.512 (df = 14)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
1.215 (df = 1; 15)
</td>
<td>
8.915<sup>***</sup> (df = 2; 14)
</td>
<td>
1.584 (df = 2; 14)
</td>
<td>
5.529<sup>**</sup> (df = 3; 13)
</td>
<td>
6.681<sup>***</sup> (df = 2; 14)
</td>
<td>
2.415 (df = 2; 14)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="6" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
<p>#4d. Linear hypothesis tests (F-tests) for each model:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Note the white.adjust robust fix for handling heteroskedasticity</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$pctox = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox

Note: Coefficient covariance matrix supplied.

  Res.Df Df     F Pr(&gt;F)
1     16                
2     15  1 1.382 0.2581</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model2, <span class="fu">c</span>(<span class="st">"data$netsentiment=0"</span>, <span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$netsentiment = 0
data$pctox = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox + data$netsentiment

Note: Coefficient covariance matrix supplied.

  Res.Df Df      F   Pr(&gt;F)   
1     16                      
2     14  2 10.277 0.001793 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model3, <span class="fu">c</span>(<span class="st">"data$bordruua=0"</span>, <span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$bordruua = 0
data$pctox = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox + data$bordruua

Note: Coefficient covariance matrix supplied.

  Res.Df Df     F Pr(&gt;F)
1     16                
2     14  2 1.525 0.2517</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model4, <span class="fu">c</span>(<span class="st">"data$netsentiment=0"</span>, <span class="st">"data$pctox=0"</span>, <span class="st">"data$bordruua=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$netsentiment = 0
data$pctox = 0
data$bordruua = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox + data$bordruua + data$netsentiment

Note: Coefficient covariance matrix supplied.

  Res.Df Df      F   Pr(&gt;F)   
1     16                      
2     13  3 7.8231 0.003093 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model5, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>, <span class="st">"data$strongru=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$pctox = 0
data$strongru = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox + data$strongru

Note: Coefficient covariance matrix supplied.

  Res.Df Df      F  Pr(&gt;F)  
1     16                    
2     14  2 5.6243 0.01612 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model6, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>, <span class="st">"data$closewest=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Linear hypothesis test

Hypothesis:
data$pctox = 0
data$closewest = 0

Model 1: restricted model
Model 2: data$netapprove ~ data$pctox + data$closewest

Note: Coefficient covariance matrix supplied.

  Res.Df Df     F  Pr(&gt;F)  
1     16                   
2     14  2 3.505 0.05833 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>#5.</p>
<p>I have examined the influence of the percentage of Eastern European countries’ populations that identify as Orthodox Christian, as measured by Pew Research, on their populations’ net approval of US leadership in the world (the difference between the share of people who expressed approval and the share who expressed disapproval), as measured by Gallup.</p>
<p>I have considered a series of six models for examining contributing factors in this relationship:</p>
<p>-model (I), which uses the percentage of countries’ populations identifying as Orthodox (pctox) as the sole independent variable to explain variation in net approval of US leadership (netapprove) -model (II), which uses both pctox and netsentiment, a variable that measures the difference in each surveyed country between the percentages of respondents who agree with the statements “It is in our country’s interest to work closely with the U.S. and other Western powers” and “A strong Russia is necessary to balance the influence of the West.” -model (III), which uses both pctox and bordruua, a dummy variable that accounts for geographic proximity to the Russia-Ukraine conflict and takes the value 1 in countries that border Russia and/or Ukraine and 0 in countries that do not border either -model (IV), which uses pctox, netsentiment, and bordruua together -model (V), which uses pctox and strongru, a variable that codes for levels of agreement with the statement “A strong Russia is necessary to balance the influence of the West” -model (VI), which uses pctox and closewest, a variable that codes for levels of agreement with the statement “It is in our country’s interest to work closely with the U.S. and other Western powers”</p>
<p>I began this analysis hypothesizing that the share of countries’ populations that identify as Orthodox would negatively predict public approval of US leadership, due to Russia’s history as a major influence on public opinion in the Orthodox world and its use of Orthodox religious themes in anti-Western political propaganda attempting to justify actions such as its invasion of Ukraine. When I used pctox as my sole independent variable in model (I), it was negatively signed, but not statistically significant. In the other models where it was included alongside other variables, its sign was sometimes positive and sometimes negative, but it never attained statistical significance, meaning that I did not find evidence in favor of my initial hypothesis.</p>
<p>I did find, though, that inclusion of the netsentiment variable measuring the difference between respondents’ endorsement of the pro-Western statement and their endorsement of the pro-Russian statement resulted in its significance as a predictor of net approval of US leadership. Similarly, including the pro-Western statement or the pro-Russian statement alone without making any reference to the other also resulted in statistical significance as a predictor of net approval of US leadership. In model II, the coefficient on netsentiment of 1.361 was statistically significant at the 1% level, meaning that an increase in netsentiment of one percentage point, holding all else constant, led to an increase in US leadership approval of 1.361 percentage points and that there was a less than one percent chance of the study finding a value at least as extreme as the one observed in the absence of a true relationship. In model IV, the coefficient on netsentiment was a very similar 1.385, also significant at the 1% level. Model V found that the coefficient on strongru, measuring agreement with the pro-Russian statement, was -1.555, and that this finding was also significant at the 1% level. This means that, if all other variables’ values are held constant, increasing a surveyed country’s agreement that a strong Russia is necessary to balance the West by one percentage point led to a 1.555 percentage point decrease in net approval of US leadership. Conversely, in Model VI, the coefficient on closewest was 2.002, meaning that, holding all else constant, increasing a country’s agreement with the pro-Western statement by one percentage point led to a 2.002 percentage point increase in net approval of US leadership. However, this was a somewhat weaker finding, being statistically significant at the 5% level, meaning that there was a less than 5% but greater than 1% chance of finding a value at least as extreme as the one observed in the absence of a true relationship.</p>
<p>In no model was the bordruua variable, measuring whether or not a country borders Russia and/or Ukraine, statistically significant, meaning that this analysis did not find evidence of geographic proximity to the Russian invasion of Ukraine as a meaningful predictor of attitudes towards US leadership.</p>
<p>Considering these factors, although no model found statistical significance of the predictor I set out to investigate, the model that best explains the relationship between Orthodox Christian religious affiliation and views of US leadership is model (II). It finds a potential alternative explanation, netsentiment, highly statistically significant. Furthermore, an F-test finds that the model has a p-value of 0.001793, meaning that, if the model’s variables were collectively not truly related to net approval of US leadership, there would be only a 1 in 558 chance of data at least as extreme as what was observed occurring by chance. The significance of netsentiment sheds light on where some of the impact I expected to come from pctox is actually coming from and thus provides insights into why pctox lacks significance.</p>
<p>This analysis has a few limitations. Notably, it does not include a variable measuring the percentage of ethnic Russians in the included countries, because no dataset was available that measured this variable across countries in a consistent manner. This poses a risk of omitted variable bias, meaning that the absence of this factor from the analysis could cause have distorted the estimates of some coefficients. Of the included countries, those with large minorities of ethnic Russians and where the majority ethnic group has few adherents of Orthodox Christianity - that is, Estonia and Latvia - are most likely to be affected, since some of the effects the model is attributing to Orthodox religious affiliation may in fact be caused at least in part by Russian ethnic identity. Also, the small sample size of 17 countries can result in large confidence intervals for some estimates, meaning that there is a risk of some estimated values being further from their true values than they would have been with a larger sample. The scope of this risk, though, is limited, since the small number of countries in Eastern Europe will automatically limit the scope of the data - the sample of 17 is a relatively large share of the entire universe of Eastern European countries. Additionally, this analysis would have benefited from, and future analysis would benefit from, availability of data at a more granular level, to analyze the relationship between Orthodox identity and approval of US leadership in the world broken down by sub-national dimensions such as administrative division (province, oblast, etc.), age, gender, and ethnicity.</p>
<p>While the missing data on Russian ethnicity threatens some aspects of internal validity, the scope of this threat is limited. While the lack of data on Russian ethnicity may cause some distortion of results when it comes to Estonia and Latvia, the risk of distortion of results via conflation of the impacts of Russian ethnicity with those of Orthodox religious affiliation is relatively low elsewhere. The netsentiment variable, by measuring the difference between national publics’ feelings towards the West and their feelings towards Russia, is a suitable regressor for accounting for non-religious political factors that impact Eastern Europeans’ views of US leadership in the world. The credibility of the Pew Research Center and Gallup as data sources likely means the risk of an errors-in-variables bias caused by mismeasuring values of variables is quite low. Furthermore, the risk of simultaneous causality bias, the phenomenon wherein a dependent and an independent variable are causes of each other, is also low, since it seems much less likely (although theoretically possible) for a person to change their religious affiliation as a result of their views of US leadership than it does for a person’s pre-existing religious affiliation to affect their views of US leadership.</p>
<p>External validity of this analysis is likely strong, because the countries included in the study are roughly representative of Eastern European countries as a whole, and each variable has a consistent time and source for every included country.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="DACSS/603_Summer_Sec_1" data-repo-id="" data-category="Announcements" data-category-id="" data-mapping="url" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb66" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Class Project Assignment 2"</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Matt Eckstein"</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="an">desription:</span><span class="co"> "Religious Identification as Orthodox Christian vs. Approval of US Leadership in the World"</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "08/18/2023"</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a><span class="co">  - Matt Eckstein</span></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>)</span>
<span id="cb66-28"><a href="#cb66-28" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-29"><a href="#cb66-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-30"><a href="#cb66-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-31"><a href="#cb66-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-32"><a href="#cb66-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-33"><a href="#cb66-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-34"><a href="#cb66-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-35"><a href="#cb66-35" aria-hidden="true" tabindex="-1"></a><span class="fu"># 1. Multiple regression models</span></span>
<span id="cb66-36"><a href="#cb66-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-37"><a href="#cb66-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-38"><a href="#cb66-38" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-39"><a href="#cb66-39" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox</span>
<span id="cb66-40"><a href="#cb66-40" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-41"><a href="#cb66-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-42"><a href="#cb66-42" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-43"><a href="#cb66-43" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × netsentiment</span>
<span id="cb66-44"><a href="#cb66-44" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-45"><a href="#cb66-45" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-46"><a href="#cb66-46" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × bordruua</span>
<span id="cb66-47"><a href="#cb66-47" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-48"><a href="#cb66-48" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-49"><a href="#cb66-49" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × netsentiment + \beta _{3} × bordruua</span>
<span id="cb66-50"><a href="#cb66-50" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-51"><a href="#cb66-51" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-52"><a href="#cb66-52" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × strongru</span>
<span id="cb66-53"><a href="#cb66-53" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-54"><a href="#cb66-54" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-55"><a href="#cb66-55" aria-hidden="true" tabindex="-1"></a>NetApprove_{i} = \beta_{0} + \beta _{1} × pctox + \beta _{2} × closewest</span>
<span id="cb66-56"><a href="#cb66-56" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb66-57"><a href="#cb66-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-58"><a href="#cb66-58" aria-hidden="true" tabindex="-1"></a>#2a. </span>
<span id="cb66-59"><a href="#cb66-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-62"><a href="#cb66-62" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-63"><a href="#cb66-63" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Eckstein_data/Orthodoxy_and_US_leadership_cleaned.csv"</span>)</span>
<span id="cb66-64"><a href="#cb66-64" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>pctox <span class="ot">&lt;-</span> data<span class="sc">$</span>pctox <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb66-65"><a href="#cb66-65" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span>
<span id="cb66-66"><a href="#cb66-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-67"><a href="#cb66-67" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-68"><a href="#cb66-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-69"><a href="#cb66-69" aria-hidden="true" tabindex="-1"></a>#2b. Customizing variable names</span>
<span id="cb66-70"><a href="#cb66-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-73"><a href="#cb66-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-74"><a href="#cb66-74" aria-hidden="true" tabindex="-1"></a><span class="co">#Most of my variable names are good as they are; though, here, I create and name additional variables that will be helpful in my analysis </span></span>
<span id="cb66-75"><a href="#cb66-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-76"><a href="#cb66-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a vector to store the oxbucket values</span></span>
<span id="cb66-77"><a href="#cb66-77" aria-hidden="true" tabindex="-1"></a>oxbucket <span class="ot">&lt;-</span> <span class="fu">character</span>(<span class="fu">length</span>(data<span class="sc">$</span>pctox))</span>
<span id="cb66-78"><a href="#cb66-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-79"><a href="#cb66-79" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign values to oxbucket based on pctox</span></span>
<span id="cb66-80"><a href="#cb66-80" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"&lt;2%"</span></span>
<span id="cb66-81"><a href="#cb66-81" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="st">"2-5%"</span></span>
<span id="cb66-82"><a href="#cb66-82" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">5</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">10</span>] <span class="ot">&lt;-</span> <span class="st">"5-10%"</span></span>
<span id="cb66-83"><a href="#cb66-83" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">25</span>] <span class="ot">&lt;-</span> <span class="st">"10-25%"</span></span>
<span id="cb66-84"><a href="#cb66-84" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">50</span>] <span class="ot">&lt;-</span> <span class="st">"25-50%"</span></span>
<span id="cb66-85"><a href="#cb66-85" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">50</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">75</span>] <span class="ot">&lt;-</span> <span class="st">"50-75%"</span></span>
<span id="cb66-86"><a href="#cb66-86" aria-hidden="true" tabindex="-1"></a>oxbucket[data<span class="sc">$</span>pctox <span class="sc">&gt;=</span> <span class="dv">75</span> <span class="sc">&amp;</span> data<span class="sc">$</span>pctox <span class="sc">&lt;</span> <span class="dv">100</span>] <span class="ot">&lt;-</span> <span class="st">"75-100%"</span></span>
<span id="cb66-87"><a href="#cb66-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-88"><a href="#cb66-88" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the oxbucket variable to the data frame</span></span>
<span id="cb66-89"><a href="#cb66-89" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>oxbucket <span class="ot">&lt;-</span> oxbucket</span>
<span id="cb66-90"><a href="#cb66-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-91"><a href="#cb66-91" aria-hidden="true" tabindex="-1"></a>avgs <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb66-92"><a href="#cb66-92" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bordruua, oxbucket) <span class="sc">%&gt;%</span></span>
<span id="cb66-93"><a href="#cb66-93" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(netapprove),</span>
<span id="cb66-94"><a href="#cb66-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sd</span>(netapprove),</span>
<span id="cb66-95"><a href="#cb66-95" aria-hidden="true" tabindex="-1"></a>  <span class="fu">n</span>())</span>
<span id="cb66-96"><a href="#cb66-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-97"><a href="#cb66-97" aria-hidden="true" tabindex="-1"></a>border <span class="ot">&lt;-</span> avgs <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(bordruua <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb66-98"><a href="#cb66-98" aria-hidden="true" tabindex="-1"></a>noborder <span class="ot">&lt;-</span> avgs <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(bordruua <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb66-99"><a href="#cb66-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-100"><a href="#cb66-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-101"><a href="#cb66-101" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(border) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Border_war"</span>, <span class="st">"Percent_orthodox"</span>, <span class="st">"mean_net_approval"</span>, <span class="st">"SD_net_approval"</span>, <span class="st">"number"</span>)</span>
<span id="cb66-102"><a href="#cb66-102" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(noborder) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Border_war"</span>, <span class="st">"Percent_orthodox"</span>, <span class="st">"mean_net_approval"</span>, <span class="st">"SD_net_approval"</span>, <span class="st">"number"</span>)</span>
<span id="cb66-103"><a href="#cb66-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-104"><a href="#cb66-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-105"><a href="#cb66-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-106"><a href="#cb66-106" aria-hidden="true" tabindex="-1"></a>#2c. Designating regressors and reporting means and SDs</span>
<span id="cb66-107"><a href="#cb66-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-110"><a href="#cb66-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-111"><a href="#cb66-111" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"pctox"</span>, <span class="st">"netsentiment"</span>, <span class="st">"bordruua"</span>, <span class="st">"strongru"</span>, <span class="st">"closewest"</span>)</span>
<span id="cb66-112"><a href="#cb66-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-113"><a href="#cb66-113" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">allvars_mean =</span> <span class="fu">sapply</span>(data[, vars], mean),</span>
<span id="cb66-114"><a href="#cb66-114" aria-hidden="true" tabindex="-1"></a><span class="at">allvars_sd =</span> <span class="fu">sapply</span>(data[, vars], sd))</span>
<span id="cb66-115"><a href="#cb66-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-116"><a href="#cb66-116" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-117"><a href="#cb66-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-118"><a href="#cb66-118" aria-hidden="true" tabindex="-1"></a>#2d. Basic linear equation</span>
<span id="cb66-119"><a href="#cb66-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-122"><a href="#cb66-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-123"><a href="#cb66-123" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox)</span>
<span id="cb66-124"><a href="#cb66-124" aria-hidden="true" tabindex="-1"></a>model</span>
<span id="cb66-125"><a href="#cb66-125" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb66-126"><a href="#cb66-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-127"><a href="#cb66-127" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-128"><a href="#cb66-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-129"><a href="#cb66-129" aria-hidden="true" tabindex="-1"></a>#2e. (Prompt 2e is identical to prompt 2d; see answer 2d)</span>
<span id="cb66-130"><a href="#cb66-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-131"><a href="#cb66-131" aria-hidden="true" tabindex="-1"></a>#2f. Linear-log model</span>
<span id="cb66-132"><a href="#cb66-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-135"><a href="#cb66-135" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-136"><a href="#cb66-136" aria-hidden="true" tabindex="-1"></a>Linearlog_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(netapprove <span class="sc">~</span> <span class="fu">log</span>(pctox), <span class="at">data =</span> data)</span>
<span id="cb66-137"><a href="#cb66-137" aria-hidden="true" tabindex="-1"></a>Linearlog_model</span>
<span id="cb66-138"><a href="#cb66-138" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Linearlog_model)</span>
<span id="cb66-139"><a href="#cb66-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-140"><a href="#cb66-140" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-141"><a href="#cb66-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-142"><a href="#cb66-142" aria-hidden="true" tabindex="-1"></a>#2g. Cubic model</span>
<span id="cb66-143"><a href="#cb66-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-146"><a href="#cb66-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-147"><a href="#cb66-147" aria-hidden="true" tabindex="-1"></a>cubic_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(netapprove <span class="sc">~</span> <span class="fu">I</span>(pctox) <span class="sc">+</span> <span class="fu">I</span>(pctox<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(pctox<span class="sc">^</span><span class="dv">3</span>), <span class="at">data =</span></span>
<span id="cb66-148"><a href="#cb66-148" aria-hidden="true" tabindex="-1"></a>data)</span>
<span id="cb66-149"><a href="#cb66-149" aria-hidden="true" tabindex="-1"></a>cubic_model</span>
<span id="cb66-150"><a href="#cb66-150" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cubic_model)</span>
<span id="cb66-151"><a href="#cb66-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-152"><a href="#cb66-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-153"><a href="#cb66-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-154"><a href="#cb66-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-155"><a href="#cb66-155" aria-hidden="true" tabindex="-1"></a>#2h. Plot the observations and add the linear, log-linear, and cubic models</span>
<span id="cb66-156"><a href="#cb66-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-157"><a href="#cb66-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-160"><a href="#cb66-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-161"><a href="#cb66-161" aria-hidden="true" tabindex="-1"></a>plot <span class="ot">&lt;-</span> <span class="fu">plot</span>(data<span class="sc">$</span>pctox, data<span class="sc">$</span>netapprove,</span>
<span id="cb66-162"><a href="#cb66-162" aria-hidden="true" tabindex="-1"></a><span class="at">pch =</span> <span class="dv">20</span>,</span>
<span id="cb66-163"><a href="#cb66-163" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb66-164"><a href="#cb66-164" aria-hidden="true" tabindex="-1"></a><span class="at">xlab =</span> <span class="st">"Percent Orthodox"</span>,</span>
<span id="cb66-165"><a href="#cb66-165" aria-hidden="true" tabindex="-1"></a><span class="at">ylab =</span> <span class="st">"Net Approval of US Leadership"</span>,</span>
<span id="cb66-166"><a href="#cb66-166" aria-hidden="true" tabindex="-1"></a><span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>),</span>
<span id="cb66-167"><a href="#cb66-167" aria-hidden="true" tabindex="-1"></a><span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>, <span class="dv">100</span>))</span>
<span id="cb66-168"><a href="#cb66-168" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb66-169"><a href="#cb66-169" aria-hidden="true" tabindex="-1"></a>order_id <span class="ot">&lt;-</span> <span class="fu">order</span>(data<span class="sc">$</span>pctox)</span>
<span id="cb66-170"><a href="#cb66-170" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(data<span class="sc">$</span>pctox[order_id],</span>
<span id="cb66-171"><a href="#cb66-171" aria-hidden="true" tabindex="-1"></a><span class="fu">fitted</span>(Linearlog_model)[order_id],</span>
<span id="cb66-172"><a href="#cb66-172" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb66-173"><a href="#cb66-173" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb66-174"><a href="#cb66-174" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> data<span class="sc">$</span>pctox[order_id],</span>
<span id="cb66-175"><a href="#cb66-175" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="fu">fitted</span>(cubic_model)[order_id],</span>
<span id="cb66-176"><a href="#cb66-176" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="st">"orange"</span>,</span>
<span id="cb66-177"><a href="#cb66-177" aria-hidden="true" tabindex="-1"></a><span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb66-178"><a href="#cb66-178" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>,</span>
<span id="cb66-179"><a href="#cb66-179" aria-hidden="true" tabindex="-1"></a><span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Linear"</span>, <span class="st">"Linear-Log"</span>, <span class="st">"Cubic"</span>),</span>
<span id="cb66-180"><a href="#cb66-180" aria-hidden="true" tabindex="-1"></a><span class="at">lty =</span> <span class="dv">1</span>,</span>
<span id="cb66-181"><a href="#cb66-181" aria-hidden="true" tabindex="-1"></a><span class="at">col =</span> <span class="fu">c</span>(<span class="st">"Black"</span>, <span class="st">"darkgreen"</span>, <span class="st">"orange"</span>))</span>
<span id="cb66-182"><a href="#cb66-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-183"><a href="#cb66-183" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb66-184"><a href="#cb66-184" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-185"><a href="#cb66-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-186"><a href="#cb66-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-187"><a href="#cb66-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-188"><a href="#cb66-188" aria-hidden="true" tabindex="-1"></a>#3:</span>
<span id="cb66-189"><a href="#cb66-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-190"><a href="#cb66-190" aria-hidden="true" tabindex="-1"></a>Visually speaking, none of the three representations (linear, linear-log, or cubic) is drastically different from the other two. The linear and linear-log models are extremely similar except for a slight upward hook at the left side of the graph in the linear-log model, and this makes the model neither noticeably better nor noticeably worse than the linear model.</span>
<span id="cb66-191"><a href="#cb66-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-192"><a href="#cb66-192" aria-hidden="true" tabindex="-1"></a>The cubic model arguably follows the points slightly better than the other two models, but this is thanks to a dip in the model line at around 70% Orthodox that appears to be driven in large part by one point (Russia's) with the lowest net approval of US leadership of any country in the dataset. Given the apparent ability of the curve to be noticeably influenced by this single point, it is likely that this model is overfitted. As such, there is no apparent advantage to choosing a non-linear model for this analysis.</span>
<span id="cb66-193"><a href="#cb66-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-194"><a href="#cb66-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-195"><a href="#cb66-195" aria-hidden="true" tabindex="-1"></a>#4a.</span>
<span id="cb66-196"><a href="#cb66-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-199"><a href="#cb66-199" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-200"><a href="#cb66-200" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox)</span>
<span id="cb66-201"><a href="#cb66-201" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>netsentiment)</span>
<span id="cb66-202"><a href="#cb66-202" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>bordruua)</span>
<span id="cb66-203"><a href="#cb66-203" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>bordruua <span class="sc">+</span> data<span class="sc">$</span>netsentiment)</span>
<span id="cb66-204"><a href="#cb66-204" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>strongru)</span>
<span id="cb66-205"><a href="#cb66-205" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(data<span class="sc">$</span>netapprove <span class="sc">~</span> data<span class="sc">$</span>pctox <span class="sc">+</span> data<span class="sc">$</span>closewest)</span>
<span id="cb66-206"><a href="#cb66-206" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model)</span>
<span id="cb66-207"><a href="#cb66-207" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model2)</span>
<span id="cb66-208"><a href="#cb66-208" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model3)</span>
<span id="cb66-209"><a href="#cb66-209" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model4)</span>
<span id="cb66-210"><a href="#cb66-210" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model5)</span>
<span id="cb66-211"><a href="#cb66-211" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(model6)</span>
<span id="cb66-212"><a href="#cb66-212" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span>
<span id="cb66-213"><a href="#cb66-213" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span>
<span id="cb66-214"><a href="#cb66-214" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span>
<span id="cb66-215"><a href="#cb66-215" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)</span>
<span id="cb66-216"><a href="#cb66-216" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)</span>
<span id="cb66-217"><a href="#cb66-217" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model6)</span>
<span id="cb66-218"><a href="#cb66-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-219"><a href="#cb66-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-220"><a href="#cb66-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-221"><a href="#cb66-221" aria-hidden="true" tabindex="-1"></a>#4b.</span>
<span id="cb66-222"><a href="#cb66-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-225"><a href="#cb66-225" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-226"><a href="#cb66-226" aria-hidden="true" tabindex="-1"></a>rob_se <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb66-227"><a href="#cb66-227" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model2, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb66-228"><a href="#cb66-228" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model3, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb66-229"><a href="#cb66-229" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model4, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb66-230"><a href="#cb66-230" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model5, <span class="at">type =</span> <span class="st">"HC1"</span>))),</span>
<span id="cb66-231"><a href="#cb66-231" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">diag</span>(<span class="fu">vcovHC</span>(model6, <span class="at">type =</span> <span class="st">"HC1"</span>))))</span>
<span id="cb66-232"><a href="#cb66-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-233"><a href="#cb66-233" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-234"><a href="#cb66-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-235"><a href="#cb66-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-236"><a href="#cb66-236" aria-hidden="true" tabindex="-1"></a>#4c. </span>
<span id="cb66-237"><a href="#cb66-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-238"><a href="#cb66-238" aria-hidden="true" tabindex="-1"></a><span class="in">```{r my latextable, results = "asis"}</span></span>
<span id="cb66-239"><a href="#cb66-239" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb66-240"><a href="#cb66-240" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(model, model2, model3,</span>
<span id="cb66-241"><a href="#cb66-241" aria-hidden="true" tabindex="-1"></a>model4, model5, model6,</span>
<span id="cb66-242"><a href="#cb66-242" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Regressions of Orthodox Christian Religious ID and Net Approval of US Leadership"</span>,</span>
<span id="cb66-243"><a href="#cb66-243" aria-hidden="true" tabindex="-1"></a><span class="at">type =</span> <span class="st">"html"</span>,</span>
<span id="cb66-244"><a href="#cb66-244" aria-hidden="true" tabindex="-1"></a><span class="at">digits =</span> <span class="dv">3</span>,</span>
<span id="cb66-245"><a href="#cb66-245" aria-hidden="true" tabindex="-1"></a><span class="at">header =</span> <span class="cn">FALSE</span>,</span>
<span id="cb66-246"><a href="#cb66-246" aria-hidden="true" tabindex="-1"></a><span class="at">se =</span> rob_se,</span>
<span id="cb66-247"><a href="#cb66-247" aria-hidden="true" tabindex="-1"></a><span class="at">object.names =</span> <span class="cn">TRUE</span>,</span>
<span id="cb66-248"><a href="#cb66-248" aria-hidden="true" tabindex="-1"></a><span class="at">model.numbers =</span> <span class="cn">FALSE</span>,</span>
<span id="cb66-249"><a href="#cb66-249" aria-hidden="true" tabindex="-1"></a><span class="at">column.labels =</span> <span class="fu">c</span>(<span class="st">"(I)"</span>, <span class="st">"(II)"</span>, <span class="st">"(III)"</span>, <span class="st">"(IV)"</span>, <span class="st">"(V)"</span>, <span class="st">"(VI)"</span>))</span>
<span id="cb66-250"><a href="#cb66-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-251"><a href="#cb66-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-252"><a href="#cb66-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-253"><a href="#cb66-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-254"><a href="#cb66-254" aria-hidden="true" tabindex="-1"></a>#4d. Linear hypothesis tests (F-tests) for each model:</span>
<span id="cb66-255"><a href="#cb66-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-258"><a href="#cb66-258" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb66-259"><a href="#cb66-259" aria-hidden="true" tabindex="-1"></a><span class="co">#Note the white.adjust robust fix for handling heteroskedasticity</span></span>
<span id="cb66-260"><a href="#cb66-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-261"><a href="#cb66-261" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-262"><a href="#cb66-262" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model2, <span class="fu">c</span>(<span class="st">"data$netsentiment=0"</span>, <span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-263"><a href="#cb66-263" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model3, <span class="fu">c</span>(<span class="st">"data$bordruua=0"</span>, <span class="st">"data$pctox=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-264"><a href="#cb66-264" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model4, <span class="fu">c</span>(<span class="st">"data$netsentiment=0"</span>, <span class="st">"data$pctox=0"</span>, <span class="st">"data$bordruua=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-265"><a href="#cb66-265" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model5, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>, <span class="st">"data$strongru=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-266"><a href="#cb66-266" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(model6, <span class="fu">c</span>(<span class="st">"data$pctox=0"</span>, <span class="st">"data$closewest=0"</span>), <span class="at">white.adjust =</span> <span class="st">"hc1"</span>)</span>
<span id="cb66-267"><a href="#cb66-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-268"><a href="#cb66-268" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-269"><a href="#cb66-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb66-270"><a href="#cb66-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-271"><a href="#cb66-271" aria-hidden="true" tabindex="-1"></a>#5.</span>
<span id="cb66-272"><a href="#cb66-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-273"><a href="#cb66-273" aria-hidden="true" tabindex="-1"></a>I have examined the influence of the percentage of Eastern European countries' populations that identify as Orthodox Christian, as measured by Pew Research, on their populations' net approval of US leadership in the world (the difference between the share of people who expressed approval and the share who expressed disapproval), as measured by Gallup.</span>
<span id="cb66-274"><a href="#cb66-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-275"><a href="#cb66-275" aria-hidden="true" tabindex="-1"></a>I have considered a series of six models for examining contributing factors in this relationship:</span>
<span id="cb66-276"><a href="#cb66-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-277"><a href="#cb66-277" aria-hidden="true" tabindex="-1"></a>-model (I), which uses the percentage of countries' populations identifying as Orthodox (pctox) as the sole independent variable to explain variation in net approval of US leadership (netapprove)</span>
<span id="cb66-278"><a href="#cb66-278" aria-hidden="true" tabindex="-1"></a>-model (II), which uses both pctox and netsentiment, a variable that measures the difference in each surveyed country between the percentages of respondents who agree with the statements "It is in our country's interest to work closely with the U.S. and other Western powers" and "A strong Russia is necessary to balance the influence of the West."</span>
<span id="cb66-279"><a href="#cb66-279" aria-hidden="true" tabindex="-1"></a>-model (III), which uses both pctox and bordruua, a dummy variable that accounts for geographic proximity to the Russia-Ukraine conflict and takes the value 1 in countries that border Russia and/or Ukraine and 0 in countries that do not border either</span>
<span id="cb66-280"><a href="#cb66-280" aria-hidden="true" tabindex="-1"></a>-model (IV), which uses pctox, netsentiment, and bordruua together</span>
<span id="cb66-281"><a href="#cb66-281" aria-hidden="true" tabindex="-1"></a>-model (V), which uses pctox and strongru, a variable that codes for levels of agreement with the statement "A strong Russia is necessary to balance the influence of the West"</span>
<span id="cb66-282"><a href="#cb66-282" aria-hidden="true" tabindex="-1"></a>-model (VI), which uses pctox and closewest, a variable that codes for levels of agreement with the statement "It is in our country's interest to work closely with the U.S. and other Western powers"</span>
<span id="cb66-283"><a href="#cb66-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-284"><a href="#cb66-284" aria-hidden="true" tabindex="-1"></a>I began this analysis hypothesizing that the share of countries' populations that identify as Orthodox would negatively predict public approval of US leadership, due to Russia's history as a major influence on public opinion in the Orthodox world and its use of Orthodox religious themes in anti-Western political propaganda attempting to justify actions such as its invasion of Ukraine. When I used pctox as my sole independent variable in model (I), it was negatively signed, but not statistically significant. In the other models where it was included alongside other variables, its sign was sometimes positive and sometimes negative, but it never attained statistical significance, meaning that I did not find evidence in favor of my initial hypothesis.</span>
<span id="cb66-285"><a href="#cb66-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-286"><a href="#cb66-286" aria-hidden="true" tabindex="-1"></a>I did find, though, that inclusion of the netsentiment variable measuring the difference between respondents' endorsement of the pro-Western statement and their endorsement of the pro-Russian statement resulted in its significance as a predictor of net approval of US leadership. Similarly, including the pro-Western statement or the pro-Russian statement alone without making any reference to the other also resulted in statistical significance as a predictor of net approval of US leadership. In model II, the coefficient on netsentiment of 1.361 was statistically significant at the 1% level, meaning that an increase in netsentiment of one percentage point, holding all else constant, led to an increase in US leadership approval of 1.361 percentage points and that there  was a less than one percent chance of the study finding a value at least as extreme as the one observed in the absence of a true relationship. In model IV, the coefficient on netsentiment was a very similar 1.385, also significant at the 1% level. Model V found that the coefficient on strongru, measuring agreement with the pro-Russian statement, was -1.555, and that this finding was also significant at the 1% level. This means that, if all other variables' values are held constant, increasing a surveyed country's agreement that a strong Russia is necessary to balance the West by one percentage point led to a 1.555 percentage point decrease in net approval of US leadership. Conversely, in Model VI, the coefficient on closewest was 2.002, meaning that, holding all else constant, increasing a country's agreement with the pro-Western statement by one percentage point led to a 2.002 percentage point increase in net approval of US leadership. However, this was a somewhat weaker finding, being statistically significant at the 5% level, meaning that there was a less than 5% but greater than 1% chance of finding a value at least as extreme as the one observed in the absence of a true relationship.</span>
<span id="cb66-287"><a href="#cb66-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-288"><a href="#cb66-288" aria-hidden="true" tabindex="-1"></a>In no model was the bordruua variable, measuring whether or not a country borders Russia and/or Ukraine, statistically significant, meaning that this analysis did not find evidence of geographic proximity to the Russian invasion of Ukraine as a meaningful predictor of attitudes towards US leadership.</span>
<span id="cb66-289"><a href="#cb66-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-290"><a href="#cb66-290" aria-hidden="true" tabindex="-1"></a>Considering these factors, although no  model found statistical significance of the predictor I set out to investigate, the model that best explains the relationship between Orthodox Christian religious affiliation and views of US leadership is model (II). It finds a potential alternative explanation, netsentiment, highly statistically significant. Furthermore, an F-test finds that the model has a p-value of 0.001793, meaning that, if the model's variables were collectively not truly related to net approval of US leadership, there would be only a 1 in 558 chance of data at least as extreme as what was observed occurring by chance. The significance of netsentiment sheds light on where some of the impact I expected to come from pctox is actually coming from and thus provides insights into why pctox lacks significance.</span>
<span id="cb66-291"><a href="#cb66-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-292"><a href="#cb66-292" aria-hidden="true" tabindex="-1"></a>This analysis has a few limitations. Notably, it does not include a variable measuring the percentage of ethnic Russians in the included countries, because no dataset was available that measured this variable across countries in a consistent manner. This poses a risk of omitted variable bias, meaning that the absence of this factor from the analysis could cause have distorted the estimates of some coefficients. Of the included countries, those with large minorities of ethnic Russians and where the majority ethnic group has few adherents of Orthodox Christianity - that is, Estonia and Latvia - are most likely to be affected, since some of the effects the model is attributing to Orthodox religious affiliation may in fact be caused at least in part by Russian ethnic identity. Also, the small sample size of 17 countries can result in large confidence intervals for some estimates, meaning that there is a risk of some estimated values being further from their true values than they would have been with a larger sample. The scope of this risk, though, is limited, since the small number of countries in Eastern Europe will automatically limit the scope of the data - the sample of 17 is a relatively large share of the entire universe of Eastern European countries. Additionally, this analysis would have benefited from, and future analysis would benefit from, availability of data at a more granular level, to analyze the relationship between Orthodox identity and approval of US leadership in the world broken down by sub-national dimensions such as administrative division (province, oblast, etc.), age, gender, and ethnicity.</span>
<span id="cb66-293"><a href="#cb66-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-294"><a href="#cb66-294" aria-hidden="true" tabindex="-1"></a>While the missing data on Russian ethnicity threatens some aspects of internal validity, the scope of this threat is limited. While the lack of data on Russian ethnicity may cause some distortion of results when it comes to Estonia and Latvia, the risk of distortion of results via conflation of the impacts of Russian ethnicity with those of Orthodox religious affiliation is relatively low elsewhere. The netsentiment variable, by measuring the difference between national publics' feelings towards the West and their feelings towards Russia, is a suitable regressor for accounting for non-religious political factors that impact Eastern Europeans' views of US leadership in the world. The credibility of the Pew Research Center and Gallup as data sources likely means the risk of an errors-in-variables bias caused by mismeasuring values of variables is quite low. Furthermore, the risk of simultaneous causality bias, the phenomenon wherein a dependent and an independent variable are causes of each other, is also low, since it seems much less likely (although theoretically possible) for a person to change their religious affiliation as a result of their views of US leadership than it does for a person's pre-existing religious affiliation to affect their views of US leadership.</span>
<span id="cb66-295"><a href="#cb66-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-296"><a href="#cb66-296" aria-hidden="true" tabindex="-1"></a>External validity of this analysis is likely strong, because the countries included in the study are roughly representative of Eastern European countries as a whole, and each variable has a consistent time and source for every included country.</span>
<span id="cb66-297"><a href="#cb66-297" aria-hidden="true" tabindex="-1"></a></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



</body></html>