{
  "hash": "53373ef8cd62a4e9279d9e1a6fafb74d",
  "result": {
    "markdown": "---\ntitle: \"Length of UFO Encounters: Multiple Regressions\"\nauthor: \"Peri (Teresa) Lardo\"\ndesription: \"Multiple Regression models for UFO sightings data set\"\ndate: \"8/17/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - Project2\n  - Peri Teresa Lardo\n  - UFO sightings\n---\n\n\n## Load libraries and dataset, clean data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load libraries\nlibrary(tidyverse)\nlibrary(readr)\nlibrary(dplyr)\nlibrary(lubridate)\n\nknitr::opts_chunk$set(echo = TRUE)\n\n# Create shape categories for personal sanity\n\nround <- c(\"disk\", \"round\", \"sphere\", \"circle\", \"dome\")\ntriangular <- c(\"triangle\", \"cone\", \"pyramid\", \"delta\", \"chevron\")\noval <- c(\"oval\", \"teardrop\", \"egg\", \"crescent\")\nparallelogram <- c(\"cross\", \"diamond\", \"hexagon\", \"rectangle\")\ncylinder <- c(\"cylinder\", \"cigar\")\n\n# Import data & clean necessary elements\nufo_sighting_data <- read_csv(\"data/ufo_sighting_data.csv\") %>% drop_na(UFO_shape, length_of_encounter_seconds, country, Date_time, latitude) %>%\n  filter(length_of_encounter_seconds < 86400) %>%\n  filter(country %in% c(\"us\", \"ca\")) %>%\n  filter(!str_detect(description, 'HOAX')) %>%\n  filter(!UFO_shape %in% c(\"light\", \"fireball\", \"flare\", \"flash\", \"other\", \"unknown\", \"formation\", \"changing\", \"changed\")) %>%\n  mutate(Shape_Category = case_when(\n         UFO_shape %in% round ~ \"Round\",\n         UFO_shape %in% triangular ~ \"Triangular\",\n         UFO_shape %in% oval ~ \"Oval\",\n         UFO_shape %in% parallelogram ~ \"Parallelogram\",\n         UFO_shape %in% cylinder ~ \"Cylinder\"))\n\n# Make sure the Date_time column is actually in datetime format\nufo_sighting_data$Date_time <- parse_date_time(ufo_sighting_data$Date_time, \"mdy_HM\")\n\n# Create separate variables for the Month & time of day (by hour) of the encounters\nufo_sighting_data$Month = month(ufo_sighting_data$Date_time)\nufo_sighting_data$Hour = 1 + hour(ufo_sighting_data$Date_time)\n\n# Create dummy variables for categorical Shape (x) variable\nlibrary(fastDummies)\nufo_sighting_data <- dummy_cols(ufo_sighting_data, select_columns = 'Shape_Category')\n\nsummary(ufo_sighting_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Date_time                          city           state/province    \n Min.   :1910-01-02 00:00:00.00   Length:32352       Length:32352      \n 1st Qu.:2001-02-07 11:07:30.00   Class :character   Class :character  \n Median :2006-09-09 20:45:00.00   Mode  :character   Mode  :character  \n Mean   :2003-07-04 07:34:43.36                                        \n 3rd Qu.:2011-05-28 22:30:00.00                                        \n Max.   :2014-05-08 00:00:00.00                                        \n   country           UFO_shape         length_of_encounter_seconds\n Length:32352       Length:32352       Min.   :    0.01           \n Class :character   Class :character   1st Qu.:   30.00           \n Mode  :character   Mode  :character   Median :  180.00           \n                                       Mean   :  821.47           \n                                       3rd Qu.:  600.00           \n                                       Max.   :73800.00           \n described_duration_of_encounter description        date_documented   \n Length:32352                    Length:32352       Length:32352      \n Class :character                Class :character   Class :character  \n Mode  :character                Mode  :character   Mode  :character  \n                                                                      \n                                                                      \n                                                                      \n    latitude       longitude       Shape_Category         Month       \n Min.   :17.97   Min.   :-170.48   Length:32352       Min.   : 1.000  \n 1st Qu.:34.23   1st Qu.:-112.45   Class :character   1st Qu.: 4.000  \n Median :39.18   Median : -89.01   Mode  :character   Median : 7.000  \n Mean   :38.65   Mean   : -94.84                      Mean   : 6.835  \n 3rd Qu.:42.25   3rd Qu.: -80.22                      3rd Qu.: 9.000  \n Max.   :72.70   Max.   : -52.67                      Max.   :12.000  \n      Hour       Shape_Category_Cylinder Shape_Category_Oval\n Min.   : 1.00   Min.   :0.00000         Min.   :0.0000     \n 1st Qu.:12.00   1st Qu.:0.00000         1st Qu.:0.0000     \n Median :20.00   Median :0.00000         Median :0.0000     \n Mean   :16.42   Mean   :0.08562         Mean   :0.1339     \n 3rd Qu.:22.00   3rd Qu.:0.00000         3rd Qu.:0.0000     \n Max.   :24.00   Max.   :1.00000         Max.   :1.0000     \n Shape_Category_Parallelogram Shape_Category_Round Shape_Category_Triangular\n Min.   :0.00000              Min.   :0.0000       Min.   :0.000            \n 1st Qu.:0.00000              1st Qu.:0.0000       1st Qu.:0.000            \n Median :0.00000              Median :0.0000       Median :0.000            \n Mean   :0.06979              Mean   :0.4677       Mean   :0.243            \n 3rd Qu.:0.00000              3rd Qu.:1.0000       3rd Qu.:0.000            \n Max.   :1.00000              Max.   :1.0000       Max.   :1.000            \n```\n:::\n:::\n\n\n# Model Building\n\nIn Project I, we started off interested in the independent variable of ***UFO Shape*** (transformed into a series of dummy variables) and the dependent variable of ***Length of Encounter (in Seconds)***. Another possible (available) variable that may contribute to the length of a UFO sighting is the hour of day (measured 1-24 from 1st hour of the day, midnight to one, to the 24th hour, 11PM to midnight).\n\nThe time of day may influence the length of a sighting (and contribute to the identification of UFO shape) in part because of how much or how little light is available outdoors, where UFOs are traditionally seen (but if you ever spot one in the middle of your kitchen or a Starbucks, definitely let me know). The month of the year would also play into the expected level of sunlight at any given time because the amount of sunlight at, for instance, 7 pm in July is much different than at 7 pm in February.\n\nLatitude is another element that can influence the amount of light at a given time of day & year. There is also a preexisting cultural association between UFOs/paranormal activity and a certain latitude - the 37th parallel north.\n\nDue to the variations in seasons in different hemispheres represented in our dataset, I have limited the data to reported UFO sightings in Canada and the United States. Just over 96% of the sightings in the dataset are from these two countries.\n\n### Variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Customize variables\nufo_sighting_data$seconds <- ufo_sighting_data$length_of_encounter_seconds\nufo_sighting_data$Round <- ufo_sighting_data$Shape_Category_Round\nufo_sighting_data$Triangular <- ufo_sighting_data$Shape_Category_Triangular\nufo_sighting_data$Cylindrical <- ufo_sighting_data$Shape_Category_Cylinder\nufo_sighting_data$Oval <- ufo_sighting_data$Shape_Category_Oval\n\n\n# Designate regressors, report mean & standard deviations thereof\nvars <- c(\"seconds\", \"Round\", \"Triangular\", \"Cylindrical\", \"Oval\", \"latitude\", \"Hour\", \"Month\")\ncbind(Mean = sapply(ufo_sighting_data[, vars], mean),\n      StandardDev = sapply(ufo_sighting_data[, vars], sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                    Mean  StandardDev\nseconds     821.46936078 2699.9808513\nRound         0.46766815    0.4989613\nTriangular    0.24298343    0.4288918\nCylindrical   0.08562067    0.2798074\nOval          0.13393299    0.3405856\nlatitude     38.65174613    5.6948996\nHour         16.41654303    7.5296713\nMonth         6.83490974    3.1924518\n```\n:::\n:::\n\n\n### Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLinear_model_UFO <- lm(seconds ~ Hour, data = ufo_sighting_data)\nLinear_model_UFO\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = seconds ~ Hour, data = ufo_sighting_data)\n\nCoefficients:\n(Intercept)         Hour  \n    1010.08       -11.49  \n```\n:::\n:::\n\n\n### Log-Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nLinearlog_model_UFO <- lm(seconds ~ log(Hour), data = ufo_sighting_data)\nLinearlog_model_UFO\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = seconds ~ log(Hour), data = ufo_sighting_data)\n\nCoefficients:\n(Intercept)    log(Hour)  \n       1113         -114  \n```\n:::\n:::\n\n\n### Quadratic Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquad_model_UFO <- lm(seconds ~ I(Hour) + I((Hour)^2), data = ufo_sighting_data)\nquad_model_UFO\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = seconds ~ I(Hour) + I((Hour)^2), data = ufo_sighting_data)\n\nCoefficients:\n(Intercept)      I(Hour)  I((Hour)^2)  \n   1209.751      -63.737        2.017  \n```\n:::\n:::\n\n\n### Cubic Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncubic_model_UFO <- lm(seconds ~ I(Hour) + I((Hour)^2) + I((Hour)^3) + Month, data = ufo_sighting_data)\ncubic_model_UFO\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = seconds ~ I(Hour) + I((Hour)^2) + I((Hour)^3) + \n    Month, data = ufo_sighting_data)\n\nCoefficients:\n(Intercept)      I(Hour)  I((Hour)^2)  I((Hour)^3)        Month  \n  1.210e+03   -6.584e+01    2.217e+00   -5.094e-03    6.439e-01  \n```\n:::\n:::\n\n\n## Plot Observations & Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(ufo_sighting_data$Hour, ufo_sighting_data$seconds,\n     pch = 20,\n     col = \"orange\",\n     ylim = c(300, 1300), \n     xlab = \"Hour of Day\",\n     ylab = \"Length of Sighting in Seconds\",\n     main = \"Models \\n Y-limited for zoomed-in view\")\n\nabline(Linear_model_UFO, lwd=2)\n\norder_id <- order(ufo_sighting_data$Hour)\n\nlines(ufo_sighting_data$Hour[order_id],\n     fitted(Linearlog_model_UFO)[order_id],\n     col = \"blue\",\n     lwd = 2)\n\nlines(x = ufo_sighting_data$Hour[order_id],\n      y = fitted(cubic_model_UFO)[order_id],\n      col = \"red\",\n      lwd = 4)\n\nlines(x = ufo_sighting_data$Hour[order_id],\n     y = fitted(quad_model_UFO)[order_id],\n     col = \"green\",\n     lwd = 2)\n \nlegend(\"bottomright\",\n       legend = c(\"Linear\", \"Linear-Log\", \"Cubic\", \"Quadratic\"),\n       lty = 1,\n       col = c(\"black\", \"blue\", \"red\", \"green\"))\n```\n\n::: {.cell-output-display}\n![](Project2-TeresaLardo_files/figure-html/Plot of Models chunk-1.png){width=672}\n:::\n:::\n\n\n![](images/HoursGraphPlot-01.jpg)\n\n## Linear or Non-Linear?\n\nI think a non-linear equation may better explain the possible relationship between the hour of the day and the duration of UFO sightings. When I inspect the zoomed-out view of the plot above and concentrate on the lower Y-values where most data points collect, I can see that the values do not a) uniformly increase throughout the day, b) uniformly decrease throughout the day, or c) remain constant throughout the day. There appears to be undulation in the shape of the data points.\n\nThe plot above shows a dip in encounter/sighting duration during the morning hours when many people are waking up and starting their work day, but sighting duration is higher again during the late afternoon/evening hours. The sighting duration seems to level off during the final few hours of the day (9PM to midnight), so at first I thought a quadratic equation may be best-suited. But my love for bar charts cannot be quelled, so I also made a bar chart to better visualize the mean sighting duration per hour. The bar chart showed a dip in the duration mean from 10PM to midnight that persuades me toward a cubic model. In the zoomed-in model plot above, the cubic and quadratic curves follow a very similar path. When developing my model specifications, I will make both quadratic and cubic models to determine which will be more appropriate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(ufo_sighting_data %>% \n  group_by(Hour), aes(x = Hour, y = mean(seconds), fill = Hour)) + \n  geom_bar(stat = \"identity\") + \n  ggtitle(\"The Bar Chart that Persuaded Me to Consider Cubic Models\") + \n  xlab(\"Hour of Day\") + \n  ylab(\"Duration Mean (in seconds)\") +\n  theme(legend.position = \"none\") + \n  scale_fill_gradient2(low = \"darkorchid4\", high = \"purple4\", mid = \"gold2\", midpoint = 12)\n```\n\n::: {.cell-output-display}\n![](Project2-TeresaLardo_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n# Model Specifications\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create multiple specifications\nUFO_shape_mod1 <- lm(seconds ~ Hour, data = ufo_sighting_data)\n\nUFO_shape_mod2 <- lm(seconds ~ Hour + I(Hour^2), data = ufo_sighting_data)\n\nUFO_shape_mod3 <- lm(seconds ~ Hour + I(Hour^2) + I(Hour^3), data = ufo_sighting_data)\n\nUFO_shape_mod4 <- lm(seconds ~ Hour + I(Hour^2) + I(Hour^3) + Triangular + Round + Cylindrical + Oval, data = ufo_sighting_data)\n\nUFO_shape_mod5 <- lm(seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + Oval, data = ufo_sighting_data)\n\nUFO_shape_mod6 <- lm(seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + Oval + latitude, data = ufo_sighting_data)\n\nUFO_shape_mod7 <- lm(seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + Oval + latitude + Month, data = ufo_sighting_data)\n```\n:::\n\n\n### Robust Standard Errors\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get Standard Errors for each model\nlibrary(sandwich)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'sandwich' was built under R version 4.2.3\n```\n:::\n\n```{.r .cell-code}\nrob_se <- list(sqrt(diag(vcovHC(UFO_shape_mod1, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod2, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod3, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod4, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod5, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod6, type = \"HC1\"))),\nsqrt(diag(vcovHC(UFO_shape_mod7, type = \"HC1\"))))\n\nrob_se\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n(Intercept)        Hour \n  41.009453    2.206693 \n\n[[2]]\n(Intercept)        Hour   I(Hour^2) \n 58.5748592   9.8733651   0.3603472 \n\n[[3]]\n(Intercept)        Hour   I(Hour^2)   I(Hour^3) \n78.20407203 27.81302690  2.49462059  0.06308149 \n\n[[4]]\n(Intercept)        Hour   I(Hour^2)   I(Hour^3)  Triangular       Round \n92.23228915 27.71464434  2.49367437  0.06325126 59.81228591 55.20980249 \nCylindrical        Oval \n66.58233104 64.37162303 \n\n[[5]]\n(Intercept)        Hour   I(Hour^2)  Triangular       Round Cylindrical \n 74.9282701   9.9506300   0.3661259  59.8083911  55.1664977  66.5348160 \n       Oval \n 64.3743712 \n\n[[6]]\n(Intercept)        Hour   I(Hour^2)  Triangular       Round Cylindrical \n125.3779287   9.9103213   0.3646796  59.8119217  55.1978495  66.5465776 \n       Oval    latitude \n 64.3793529   2.8077180 \n\n[[7]]\n(Intercept)        Hour   I(Hour^2)  Triangular       Round Cylindrical \n129.0824232   9.9088788   0.3646046  59.8118663  55.1984879  66.5479794 \n       Oval    latitude       Month \n 64.3451071   2.8077880   4.5789916 \n```\n:::\n:::\n\n\n## Multiple Regression Specification Models\n\n\n\n```{.r .cell-code}\nmodels <- list(UFO_shape_mod1, UFO_shape_mod2, UFO_shape_mod3,\nUFO_shape_mod4, UFO_shape_mod5, UFO_shape_mod6, UFO_shape_mod7)\n\nlibrary(stargazer)\n```\n\n```\n\nPlease cite as: \n```\n\n```\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n```\n\n```\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n\n```{.r .cell-code}\nstargazer(models,\ntitle = \"Regressions on UFO Sighting Duration\",\ntype = \"html\",\ndigits = 3,\nheader = FALSE,\nse = rob_se,\nobject.names = TRUE,\nmodel.numbers = FALSE,\ncolumn.labels = c(\"(I)\", \"(II)\", \"(III)\", \"(IV)\", \"(V)\", \"(VI)\", \"(VII)\"))\n```\n\n\n<table style=\"text-align:center\"><caption><strong>Regressions on UFO Sighting Duration</strong></caption>\n<tr><td colspan=\"8\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td colspan=\"7\"><em>Dependent variable:</em></td></tr>\n<tr><td></td><td colspan=\"7\" style=\"border-bottom: 1px solid black\"></td></tr>\n<tr><td style=\"text-align:left\"></td><td colspan=\"7\">seconds</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(I)</td><td>(II)</td><td>(III)</td><td>(IV)</td><td>(V)</td><td>(VI)</td><td>(VII)</td></tr>\n<tr><td style=\"text-align:left\"></td><td>models</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td></tr>\n<tr><td colspan=\"8\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Hour</td><td>-11.489<sup>***</sup></td><td>-63.737<sup>***</sup></td><td>-65.808<sup>**</sup></td><td>-64.960<sup>**</sup></td><td>-64.791<sup>***</sup></td><td>-65.266<sup>***</sup></td><td>-65.305<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(2.207)</td><td>(9.873)</td><td>(27.813)</td><td>(27.715)</td><td>(9.951)</td><td>(9.910)</td><td>(9.909)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(Hour2)</td><td></td><td>2.017<sup>***</sup></td><td>2.216</td><td>2.077</td><td>2.061<sup>***</sup></td><td>2.080<sup>***</sup></td><td>2.081<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td>(0.360)</td><td>(2.495)</td><td>(2.494)</td><td>(0.366)</td><td>(0.365)</td><td>(0.365)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(Hour3)</td><td></td><td></td><td>-0.005</td><td>-0.0004</td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.063)</td><td>(0.063)</td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Triangular</td><td></td><td></td><td></td><td>-91.436</td><td>-91.437</td><td>-91.532</td><td>-91.563</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(59.812)</td><td>(59.808)</td><td>(59.812)</td><td>(59.812)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Round</td><td></td><td></td><td></td><td>58.712</td><td>58.716</td><td>58.921</td><td>58.927</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(55.210)</td><td>(55.166)</td><td>(55.198)</td><td>(55.198)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Cylindrical</td><td></td><td></td><td></td><td>-110.424<sup>*</sup></td><td>-110.420<sup>*</sup></td><td>-110.470<sup>*</sup></td><td>-110.466<sup>*</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(66.582)</td><td>(66.535)</td><td>(66.547)</td><td>(66.548)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Oval</td><td></td><td></td><td></td><td>-33.922</td><td>-33.923</td><td>-33.994</td><td>-33.904</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(64.372)</td><td>(64.374)</td><td>(64.379)</td><td>(64.345)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">latitude</td><td></td><td></td><td></td><td></td><td></td><td>-2.944</td><td>-2.957</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td>(2.808)</td><td>(2.808)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Month</td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.835</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td>(4.579)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>1,010.075<sup>***</sup></td><td>1,209.751<sup>***</sup></td><td>1,213.769<sup>***</sup></td><td>1,222.002<sup>***</sup></td><td>1,221.673<sup>***</sup></td><td>1,336.895<sup>***</sup></td><td>1,331.886<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(41.009)</td><td>(58.575)</td><td>(78.204)</td><td>(92.232)</td><td>(74.928)</td><td>(125.378)</td><td>(129.082)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td colspan=\"8\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>32,352</td><td>32,352</td><td>32,352</td><td>32,352</td><td>32,352</td><td>32,352</td><td>32,352</td></tr>\n<tr><td style=\"text-align:left\">R<sup>2</sup></td><td>0.001</td><td>0.002</td><td>0.002</td><td>0.003</td><td>0.003</td><td>0.003</td><td>0.003</td></tr>\n<tr><td style=\"text-align:left\">Adjusted R<sup>2</sup></td><td>0.001</td><td>0.002</td><td>0.002</td><td>0.002</td><td>0.002</td><td>0.002</td><td>0.002</td></tr>\n<tr><td style=\"text-align:left\">Residual Std. Error</td><td>2,698.636 (df = 32350)</td><td>2,697.357 (df = 32349)</td><td>2,697.399 (df = 32348)</td><td>2,696.683 (df = 32344)</td><td>2,696.641 (df = 32345)</td><td>2,696.631 (df = 32344)</td><td>2,696.671 (df = 32343)</td></tr>\n<tr><td style=\"text-align:left\">F Statistic</td><td>33.243<sup>***</sup> (df = 1; 32350)</td><td>32.479<sup>***</sup> (df = 2; 32349)</td><td>21.655<sup>***</sup> (df = 3; 32348)</td><td>12.311<sup>***</sup> (df = 7; 32344)</td><td>14.363<sup>***</sup> (df = 6; 32345)</td><td>12.489<sup>***</sup> (df = 7; 32344)</td><td>10.932<sup>***</sup> (df = 8; 32343)</td></tr>\n<tr><td colspan=\"8\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td colspan=\"7\" style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n\n\n### Hypothesis Testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.2.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'car'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:dplyr':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:purrr':\n\n    some\n```\n:::\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod1,\nc(\"Hour=0\"),\nvcov. = vcovHC(UFO_shape_mod1, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32350  1 27.106 1.938e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod2,\nc(\"Hour=0\", \"I(Hour^2)=0\"),\nvcov. = vcovHC(UFO_shape_mod2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2)\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32349  2 25.788 6.448e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod3,\nc(\"Hour=0\", \"I(Hour^2)=0\", \"I(Hour^3)=0\"),\nvcov. = vcovHC(UFO_shape_mod3, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\nI(Hour^3) = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2) + I(Hour^3)\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32348  3 17.206 3.686e-11 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod4,\nc(\"Hour=0\", \"I(Hour^2)=0\", \"I(Hour^3)=0\", \"Triangular=0\", \"Round=0\", \"Cylindrical=0\", \"Oval=0\"),\nvcov. = vcovHC(UFO_shape_mod4, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\nI(Hour^3) = 0\nTriangular = 0\nRound = 0\nCylindrical = 0\nOval = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2) + I(Hour^3) + Triangular + Round + \n    Cylindrical + Oval\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df     F    Pr(>F)    \n1  32351                       \n2  32344  7 10.95 6.894e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod5,\nc(\"Hour=0\", \"I(Hour^2)=0\", \"Triangular=0\", \"Round=0\", \"Cylindrical=0\", \"Oval=0\"),\nvcov. = vcovHC(UFO_shape_mod5, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\nTriangular = 0\nRound = 0\nCylindrical = 0\nOval = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + \n    Oval\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32345  6 12.775 1.826e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod6,\nc(\"Hour=0\", \"I(Hour^2)=0\", \"Triangular=0\", \"Round=0\", \"Cylindrical=0\", \"Oval=0\", \"latitude=0\"),\nvcov. = vcovHC(UFO_shape_mod6, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\nTriangular = 0\nRound = 0\nCylindrical = 0\nOval = 0\nlatitude = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + \n    Oval + latitude\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32344  7 11.293 2.241e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(UFO_shape_mod7,\nc(\"Hour=0\", \"I(Hour^2)=0\", \"Triangular=0\", \"Round=0\", \"Cylindrical=0\", \"Oval=0\", \"latitude=0\", \"Month=0\"),\nvcov. = vcovHC(UFO_shape_mod7, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nHour = 0\nI(Hour^2) = 0\nTriangular = 0\nRound = 0\nCylindrical = 0\nOval = 0\nlatitude = 0\nMonth = 0\n\nModel 1: restricted model\nModel 2: seconds ~ Hour + I(Hour^2) + Triangular + Round + Cylindrical + \n    Oval + latitude + Month\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1  32351                        \n2  32343  8 9.9102 7.108e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nAfter running linear hypothesis tests, we reject the null hypothesis at the **.1%** significance level for each and every one of the seven models.\n\n# Findings & Conclusion\n\nIn all of the cubic models tested, the coefficient on the ***Hour^3^*** variable runs close to zero (-0.005 on model III and -0.0004 on model IV), suggesting negligible influence from cubic formulas. The coefficient on ***Hour^2^*** is reliably just over 2.0, and the coefficient on ***Hour*** stabilizes between -66 and -63 once ***Hour^2^*** is added to the specifications. Coefficients on each of the dummy variables for UFO shape remain similar across all regressions that include them.\n\nThe R^2^ and adjusted R^2^ values for the seven different model specifications indicate that none of the tested regressors are good predictors for the duration of a UFO sighting; none of the adjusted R^2^ values surpasses .002. Including the ***latitude*** and ***Month*** variables did not raise these low values. The model that best explains the influence of the hour of day and UFO shape on the duration of UFO sightings - and by \"best\" I do mean \"barely least terrible\" - is Model V:\n\n$$\nDuration = 1221.673 - 64.791(H) + 2.061(H^2) - 91.437(T) + 58.716(R) - 110.420(C) - 33.923(O)\n$$\n\n|          |                |           |                 |          |\n|----------|----------------|-----------|-----------------|----------|\n| H = Hour | T = Triangular | R = Round | C = Cylindrical | O = Oval |\n\nThe multiple regression table indicates that ***Hour*** and ***Hour^2^*** are both statistically significant at the **.1%** level and that the dummy variable for ***Cylindrical*** UFOs is statistically significant at the **5%** level in this model.\n\n### What Does This Mean for UFO Shapes?\n\nThe original pursuit of Project 1 was to investigate if and how the shape of UFOs affected the duration of sightings - do people who see round UFOs tend to have longer sightings? Do sightings of cigar-shaped cylindrical crafts tend to be relatively brief? We can use our chosen model formula to find the population mean of duration time when crafts of different shapes appear, holding all other variables constant.\n\n| Coefficient | UFO Shape   | Pop. Mean (seconds) |\n|-------------|-------------|---------------------|\n| -91.437     | Triangular  | 1130.24             |\n| 58.716      | Round       | 1280.39             |\n| -110.420    | Cylindrical | 1111.25             |\n| -33.923     | Oval        | 1187.75             |\n\nThe results shown in the table above suggest that sightings of round UFOs trend longer than the other shape categories, while triangular, oval, and cylindrical crafts don't drastically vary from each other in terms of sighting duration.\n\nFurther studies on craft shape and sighting duration would be necessary to establish any sort of external validity. However, considering that the low R^2^ values indicate that the shape category regressors are not good predictors of duration length, I strongly doubt that these findings can be generalized in the wider study of ufology.\n\n# Citations\n\nHlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables. R package version 5.2.3. https://CRAN.R-project.org/package=stargazer\n",
    "supporting": [
      "Project2-TeresaLardo_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}