{
  "hash": "d33ab5202666fba8f145232420ce4c3c",
  "result": {
    "markdown": "---\ntitle: \"Final Project, Air Quality and Lung/Heart Disease Deaths\"\nauthor: \"Joseph Vincent\"\ndesription: \"Air Quality and Deaths\"\ndate: \"08/12/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\ncategories:\n  - final project\n  - Joseph Vincent\neditor: \n  markdown: \n    wrap: sentence\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(lubridate)\nlibrary(readxl)\nlibrary(car)\nlibrary(sandwich)\nlibrary(stargazer)\n\nknitr::opts_chunk$set(echo = TRUE)\n```\n:::\n\n\n## Introduction\n\nPoor air quality has been shown to have a massively negative impact on human health.\nIn particular, air pollution is known to worsen pulmonary and cardiovascular diseases.\\[1\\] Just this year, researchers out of Boston University showed that air pollution caused by oil and gas production in the US resulted in over 7500 excess deaths and \\$77 billion in total health impacts in a single year.\\[2\\]\n\nThe goal of my project is to assess whether there is a noticeable relationship between air quality trends and related causes of death in California for the decade of 2000-2010.\n\n**My findings are that, while inconclusive across all counties in California, in large metropolitan counties of California, days where PM2.5 is above the national average have a positive and statistically significant impact on deaths caused by heart and lung diseases.**\n\n## Reading, cleaning and combining data sets\n\nIn order to accomplish this, I've had to combine data from a variety of sources and estimate and/or create some variables.\n\n1.  **Air quality**\n\n[SOURCE](https://data.cdc.gov/Environmental-Health-Toxicology/Air-Quality-Measures-on-the-National-Environmental/cjae-szjv) \\[3\\]\n\nI'm using the CDC's database for Air Quality Measures on the National Environmental Health Tracking Network.\nThe most recent, complete historic data available contains per-county data on air quality between the years of 1999 and 2013, inclusive.\n\nThis data is collected by the Environmental Protection Agency's network of more than 4,000 outdoor ambient air monitoring systems around the US, called the Air Quality System (AQS).\n\nThese systems collect two main types of data:\n\n-   **Fine Particulate Matter (PM2.5) Concentrations**\n\nThis refers to tiny particulate matter in the air measuring two and a half microns or less in width that originates from a variety of pollutants.\nExposure to PM2.5 particles can cause both short and long term health effects.\nPM2.5 sources include wildfires and fossil fuel combustion.\n\n-   **Ozone Concentrations**\n\nHigh concentrations of Ozone near the ground level can be harmful, causing irritation to the respiratory system and aggravating a variety of chronic lung diseases.\nThis is often referred to as \"smog\" and is produced by things like car emissions and power plants.\n\nWhile this data is of high quality, it is lacking in rural areas where monitors are not present.\nTo account for this, the CDC and EPA developed statistical models to fill in gaps in data across regions and time.\nThis allows for granular analysis of county air quality data.\n\n**Two important concepts used in my analysis are PM2.5 Days and Ozone Days.**\n\n*A measure of \"PM2.5 Days\" for a particular county-year represents the number of days with PM2.5 levels over the NAAQS.*\n\n*A measure of \"Ozone Days\" for a particular county-year represents the number of days with the maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard (NAAQS).*\n\n2.  **Deaths by Cause**\n\n[SOURCE](https://data.chhs.ca.gov/dataset/death-profiles-by-county/resource/e692e6a1-bddd-48ab-a0c8-fa0f1f43e9f4?i%20nner_span=True) \\[4\\]\n\nIn order to draw conclusions about air quality's immediate impact on public health, I'm combining my air quality data with a data set from the state of California's Department of Health and Human Services (HHS) on annual number of deaths by county, including primary cause of death.\nThis data also spans the years 1999-2013, but I will be using 2000-2010.\n\nWhile the data includes a wide variety of causes, for my analysis I will be focusing on **chronic lower respiratory disease (CLD), and diseases of the heart (HTD)**, as these are the main relevant categories for air quality health impacts.\n\n3.  **Population**\n\n[SOURCE](https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-counties.html) \\[5\\]\n\nI'm also using per-county population data from the United States Census Bureau.\nWhile there are census packages out there for easy use within R, I required annual data by county, which only exists from 2005 onwards in most data sets.\nI'm instead using the County Intercensal Tables 2000-2010 for the state of California.\n\n4.  **Power Plant Density**\n\n[SOURCE](https://www.eia.gov/electricity/data/eia860/) \\[6\\]\n\nI'm using power plant location data from the U.S.\nEnergy Information Administration data in order to calculate density of power plants per county.\nThis will be used as a proxy for social determinants of health and neighborhood quality.\n\n5.  **RUCC**\n\n[SOURCE](https://www.ers.usda.gov/) \\[7\\]\n\nIn order to select subsets of my data, I've used data from the Economic Research Service of the US Department of Agriculture to obtain Rural Urban Continuum Codes (RUCC) per county.\nThis is a classification scheme on a 8-1 scale that groups counties into categories based on the size of metro areas contained within.\nThis will be used to take subsets of the data in order to make comparisons across similar counties.\n\nSee the code chunk below for details about reading, manipulating and combining the data sets:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#reading in air quality data\nairquality <- read_csv(\"Final Project Data/Air_Quality_Measures_on_the_National_Environmental_Health_Tracking_Network.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 218635 Columns: 14\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (8): MeasureName, MeasureType, StratificationLevel, StateName, CountyNam...\ndbl (6): MeasureId, StateFips, CountyFips, ReportYear, Value, MonitorOnly\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n#reading in deaths data set\ncalideaths <- read_csv(\"Final Project Data/2021-05-14_deaths_final_1999_2013_county_year_sup.csv\") %>%\n  #filtering for occurrence deaths (i.e. all deaths that occurred, disregarding residence)\n  filter(Geography_Type == \"Occurrence\") %>%\n  #de-selecting geography type as they are now all occurrence\n  select(-Geography_Type)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 292320 Columns: 10\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (7): County, Geography_Type, Strata, Strata_Name, Cause, Cause_Desc, Ann...\ndbl (3): Year, Count, Annotation_Code\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n#reading in population data\npopulations <- read_csv(\"Final Project Data/co-est00int-tot.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 3194 Columns: 20\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (2): STNAME, CTYNAME\ndbl (18): SUMLEV, REGION, DIVISION, STATE, COUNTY, ESTIMATESBASE2000, POPEST...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n\n```{.r .cell-code}\n#cleaning air quality data\nairqualitycali <- airquality %>%\n  #arranging by year\n  arrange(`ReportYear`) %>%\n  #filtering for california only and 2000-2010\n  filter(StateName == \"California\" & `ReportYear` %in% c(2000:2010)) %>%\n  #selecting only relevant columns\n  select(CountyName, ReportYear, MeasureName, Value) %>%\n  #renaming county and year to be consistent with deaths data set\n  rename(\"County\" = `CountyName`, \"Year\" = `ReportYear`) %>%\n  #pivoting so that each row is a year-county for merging data\n  pivot_wider(names_from = MeasureName, values_from = Value) %>%\n  #renaming Air Quality columns\n  rename(\"Ozone Days Delete\" = `Number of days with maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard`,\n         \"Ozone Person Days Delete\" = `Number of person-days with maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard`,\n         \"PM2.5 Percent of Days Delete\" = `Percent of days with PM2.5 levels over the National Ambient Air Quality Standard (NAAQS)`,\n         \"PM2.5 Person Days Delete\" = `Person-days with PM2.5 over the National Ambient Air Quality Standard`,\n         \"PM2.5 Annual Average Delete\" = `Annual average ambient concentrations of PM2.5 in micrograms per cubic meter (based on seasonal averages and daily measurement)`,\n         \"Ozone Days\" = `Number of days with maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard (monitor and modeled data)`,\n         \"Ozone Person Days\" = `Number of person-days with maximum 8-hour average ozone concentration over the National Ambient Air Quality Standard (monitor and modeled data)`,\n         \"PM2.5 Percent of Days\" = `Percent of days with PM2.5 levels over the National Ambient Air Quality Standard (monitor and modeled data)`,\n         \"PM2.5 Person Days\" = `Number of person-days with PM2.5 over the National Ambient Air Quality Standard (monitor and modeled data)`,\n         \"PM2.5 Annual Average\" = `Annual average ambient concentrations of PM 2.5 in micrograms per cubic meter, based on seasonal averages and daily measurement (monitor and modeled data)`)\n\n#filling in modeled data for first year, where there is no modeled data\nairqualitycali <- airqualitycali %>%\n  mutate(`Ozone Days` = case_when(\n    `Year` == 2000 ~ `Ozone Days Delete`,\n    TRUE ~ as.numeric(as.character(`Ozone Days`)))) %>%\n  mutate(`Ozone Person Days` = case_when(\n    `Year` == 2000 ~ `Ozone Person Days Delete`,\n    TRUE ~ as.numeric(as.character(`Ozone Person Days`)))) %>%\n  mutate(`PM2.5 Percent of Days` = case_when(\n    `Year` == 2000  ~ `PM2.5 Percent of Days Delete`,\n    TRUE ~ as.numeric(as.character(`PM2.5 Percent of Days`)))) %>%\n  mutate(`PM2.5 Person Days` = case_when(\n    `Year` == 2000 ~ `PM2.5 Person Days Delete`,\n    TRUE ~ as.numeric(as.character(`PM2.5 Person Days`)))) %>%\n  mutate(`PM2.5 Annual Average` = case_when(\n    `Year` == 2000 ~ `PM2.5 Annual Average Delete`,\n    TRUE ~ as.numeric(as.character(`PM2.5 Annual Average`)))) %>%\n  select(!contains(\"Delete\"))\n\n#cleaning deaths data\ncalideathsclean <- calideaths %>%\n  #filtering for 2000-2010\n  filter(`Year` %in% c(2000:2010)) %>%\n  #filling in suppressed data\n  mutate(Count = case_when(\n    Annotation_Code == 1 ~ 0,\n    TRUE ~ as.numeric(as.character(Count)))) %>%\n  #de-selecting some unused columns\n  select(-Cause_Desc, -Annotation_Code, -Annotation_Desc) %>%\n  #focusing on relevant conditions\n  filter(Cause %in% c(\"ALL\", \"CLD\", \"HTD\")) %>%\n  rename(\"Deaths\" = `Count`) %>%\n  rename(\"Strata Name\" = `Strata_Name`)\n\n# cleaning population data\npopulationstidy <- populations %>%\n  filter(STNAME == \"California\" & CTYNAME != \"California\") %>%\n  separate(CTYNAME, into = c(\"County\", \"Delete\"), sep = \" County\") %>%\n  select(County, POPESTIMATE2000:POPESTIMATE2010, -CENSUS2010POP) %>%\n  rename(\"2000\" = POPESTIMATE2000,\n         \"2001\" = POPESTIMATE2001,\n         \"2002\" = POPESTIMATE2002,\n         \"2003\" = POPESTIMATE2003,\n         \"2004\" = POPESTIMATE2004,\n         \"2005\" = POPESTIMATE2005,\n         \"2006\" = POPESTIMATE2006,\n         \"2007\" = POPESTIMATE2007,\n         \"2008\" = POPESTIMATE2008,\n         \"2009\" = POPESTIMATE2009,\n         \"2010\" = POPESTIMATE2010) %>%\n  pivot_longer(col = c(`2000`:`2010`), names_to = \"Year\", values_to = \"Population\") %>%\n  mutate(`Year` = as.numeric(Year))\n\n#merging data\nairqualityanddeaths <- left_join(calideathsclean, airqualitycali, by = c(\"County\", \"Year\"))\nairqualityanddeaths <- left_join(airqualityanddeaths, populationstidy, by = c(\"County\", \"Year\"))\n\n#For the remaining missing air quality data not filled in by models in 2000, replacing NAs with zero, as they are all small rural counties that will skew means higher for 2000\nairqualityanddeaths <- airqualityanddeaths %>%\n  mutate(`Ozone Days` = replace_na(`Ozone Days`, 0),\n         `Ozone Person Days` = replace_na(`Ozone Person Days`, 0),\n         `PM2.5 Percent of Days` = replace_na(`PM2.5 Percent of Days`, 0),\n         `PM2.5 Person Days` = replace_na(`PM2.5 Person Days`, 0),\n         `PM2.5 Annual Average` = replace_na(`PM2.5 Annual Average`, 0)) %>%\n# Creating standardized deaths per 100,000 column\n  mutate(\"Deaths per 100,000\" = `Deaths`/`Population`*100000) %>%\n# Creating a raw PM2.5 Days column\n  mutate(\"PM2.5 Days\" = `PM2.5 Percent of Days`/100*365) %>%\n# Re-arranging\n  select(Year, County, Population, Strata, `Strata Name`, Cause, Deaths, `Deaths per 100,000`, `Ozone Days`, `Ozone Person Days`, `PM2.5 Days`, `PM2.5 Person Days`, `PM2.5 Percent of Days`, `PM2.5 Annual Average`) %>% \n# Turning Year into a date for ease of plotting time series'\n  mutate(Year = make_date(year=Year)) %>%\n# Filtering out Sierra county due to unreliable data\n  filter(County != \"Sierra\") %>%\n# Filtering out strata for this analysis\n  filter(Strata == \"Total Population\") %>%\n  select(-Strata, -`Strata Name`)\n\n# adding square mile values to each county\nairqualityanddeaths <- airqualityanddeaths %>%\n  mutate(sqmiles = case_when(\n    County == \"San Bernardino\" ~ 20057,\n    County == \"Inyo\" ~ 10181,\n    County == \"Kern\" ~ 8132,\n    County == \"Riverside\" ~ 7206,\n    County == \"Siskiyou\" ~ 6278,\n    County == \"Fresno\" ~ 5958,\n    County == \"Tulare\" ~ 4824,\n    County == \"Lassen\" ~ 4541,\n    County == \"San Diego\" ~ 4207,\n    County == \"Imperial\" ~ 4177,\n    County == \"Los Angeles\" ~ 4057,\n    County == \"Modoc\" ~ 3918,\n    County == \"Shasta\" ~ 3775,\n    County == \"Humboldt\" ~ 3568,\n    County == \"Mendocino\" ~ 3506,\n    County == \"San Luis Obispo\" ~ 3299,\n    County == \"Monterey\" ~ 3281,\n    County == \"Trinity\" ~ 3179,\n    County == \"Mono\" ~ 3049,\n    County == \"Tehama\" ~ 2950,\n    County == \"Santa Barbara\" ~ 2735,\n    County == \"Plumas\" ~ 2553,\n    County == \"Tuolumne\" ~ 2221,\n    County == \"Madera\" ~ 2137,\n    County == \"Merced\" ~ 1935,\n    County == \"Ventura\" ~ 1843,\n    County == \"El Dorado\" ~ 1708,\n    County == \"Butte\" ~ 1636,\n    County == \"Sonoma\" ~ 1576,\n    County == \"Stanislaus\" ~ 1495,\n    County == \"Mariposa\" ~ 1449,\n    County == \"Placer\" ~ 1407,\n    County == \"San Joaquin\" ~ 1391,\n    County == \"Kings\" ~ 1389,\n    County == \"San Benito\" ~ 1389,\n    County == \"Glenn\" ~ 1314,\n    County == \"Santa Clara\" ~ 1290,\n    County == \"Lake\" ~ 1256,\n    County == \"Colusa\" ~ 1151,\n    County == \"Calaveras\" ~ 1020,\n    County == \"Yolo\" ~ 1015,\n    County == \"Del Norte\" ~ 1006,\n    County == \"Sacramento\" ~ 965,\n    County == \"Nevada\" ~ 958,\n    County == \"Solano\" ~ 822,\n    County == \"Orange\" ~ 791,\n    County == \"Napa\" ~ 748,\n    County == \"Alameda\" ~ 739,\n    County == \"Alpine\" ~ 738,\n    County == \"Contra Costa\" ~ 716,\n    County == \"Yuba\" ~ 632,\n    County == \"Sutter\" ~ 602,\n    County == \"Amador\" ~ 595,\n    County == \"Marin\" ~ 520,\n    County == \"San Mateo\" ~ 448,\n    County == \"Santa Cruz\" ~ 445,\n    County == \"San Francisco\" ~ 47\n  ))\n\nairqualityanddeaths <- airqualityanddeaths %>%\n  mutate(Popdensity = Population/sqmiles)\n\n# source https://www.eia.gov/electricity/data/eia860/\nplants <- read_excel(\"Final Project Data/CA Plants 2010.xlsx\")\nplantsbycounty <- as.data.frame(table(plants$COUNTY)) %>%\n  rename(\"County\" = `Var1`, \"Plants\" = `Freq`)\nairqualityanddeaths <- left_join(airqualityanddeaths, plantsbycounty, by = \"County\")\n\nunemployment <- read_excel(\"Final Project Data/Incomedata.xlsx\")\nunemployment <- unemployment %>%\n  filter(State == \"CA\" & grepl(\"CA\", Area_Name) & Area_Name != \"Sierra, CA\") %>%\n  separate(col = Area_Name, into = c(\"County\", \"Delete\"), sep = \" County\") %>%\n  select(County, contains(\"Unemployment_rate\")) %>%\n  pivot_longer(cols = 2:24, names_to = \"Yeardelete\", values_to = \"Unemploymentrate\") %>%\n  separate(col = Yeardelete, into = c(\"Delete\", \"Year\"), sep = \"rate_\") %>%\n  mutate(`Year` = as.numeric(Year)) %>%\n  mutate(Year = make_date(year=Year)) %>%\n  select(County, Year, Unemploymentrate) %>%\n  filter(year(Year) %in% 2000:2010)\n\nincome <- read_excel(\"Final Project Data/Incomedata.xlsx\")\nincome <- income %>%\n  filter(State == \"CA\" & grepl(\"CA\", Area_Name)) %>%\n  separate(col = Area_Name, into = c(\"County\", \"Delete\"), sep = \" County\") %>%\n  select(County, Median_Household_Income_2021) %>%\n  rename(`2021` = `Median_Household_Income_2021`) %>%\n  #estimating 2000 raw income data based on income growth rates\n  mutate(`2000raw` = `2021`*.6,\n  #then calculating inflation adjusted values to normalized year 2010\n  # inflation adjustment from here: https://www.usinflationcalculator.com/\n  `2000` = `2000raw` + `2000raw`*0.266,\n  #then estimating subsequent years based on real income growth rate\n  # rates from here: https://www.multpl.com/us-median-real-income-growth/table/by-year\n  `2001` = `2000` + `2000`*-0.022,\n  `2002` = `2001` + `2001`*-0.013,\n  `2003` = `2002` + `2002`*-0.001,\n  `2004` = `2003` + `2003`*-0.004,\n  `2005` = `2004` + `2004`*0.011,\n  `2006` = `2005` + `2005`*0.008,\n  `2007` = `2006` + `2006`*0.013,\n  `2008` = `2007` + `2007`*-0.037,\n  `2009` = `2008` + `2008`*-0.007,\n  `2010` = `2009` + `2009`*-0.026) %>%\n  select(-`2021`, -`2000raw`) %>%\n  pivot_longer(cols = c(`2000`:`2010`), values_to = \"medianrealincome\", names_to = \"Year\") %>%\n  mutate(`Year` = as.numeric(Year)) %>%\n  mutate(Year = make_date(year=Year))\n \n         \nRUCC <- read_excel(\"Final Project Data/Incomedata.xlsx\")\nRUCC <- RUCC %>%\n  filter(State == \"CA\" & grepl(\"CA\", Area_Name)) %>%\n  separate(col = Area_Name, into = c(\"County\", \"Delete\"), sep = \" County\") %>%\n  select(County, Rural_Urban_Continuum_Code_2013) %>%\n  rename(RUCC = `Rural_Urban_Continuum_Code_2013`)\n\nairqualityanddeaths <- left_join(airqualityanddeaths, unemployment, by = c(\"County\", \"Year\"))\n\nairqualityanddeaths <- left_join(airqualityanddeaths, income, by = c(\"County\", \"Year\"))\n\nairqualityanddeaths <- left_join(airqualityanddeaths, RUCC, by = \"County\")\n\nairqualityanddeaths <- airqualityanddeaths %>%\n    mutate(Plants = if_else(is.na(Plants), 0, Plants))\n\nairqualityanddeaths <- airqualityanddeaths %>%\n  mutate(Powerplantdensity = Plants/sqmiles*1000)\n\nairqualityanddeaths <- airqualityanddeaths %>%\n  select(-Deaths) %>%\n  filter(Cause %in% c(\"CLD\", \"HTD\")) %>%\n  pivot_wider(names_from = Cause, values_from = `Deaths per 100,000`)  %>%\n  mutate(Deathsper100kheartlung = HTD + CLD) %>%\n  filter(!is.na(Deathsper100kheartlung)) %>%\n  filter(Deathsper100kheartlung > 0)\n```\n:::\n\n\n## The Issue with Small Counties\n\nBefore creating an optimal model for explaining heart and lung disease deaths, I want to explain why I've chosen to take a subset of the data for the final analysis.\n\nMy original data set contains 609 observations - inique county-years in California, from 2000-2010 inclusive.\nThis includes all 57 counties (minus Sierra due to missing data).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(airqualityanddeaths)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 609\n```\n:::\n\n```{.r .cell-code}\nunique(airqualityanddeaths$County)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Alameda\"         \"Amador\"          \"Butte\"           \"Calaveras\"      \n [5] \"Colusa\"          \"Contra Costa\"    \"Del Norte\"       \"El Dorado\"      \n [9] \"Fresno\"          \"Glenn\"           \"Humboldt\"        \"Imperial\"       \n[13] \"Inyo\"            \"Kern\"            \"Kings\"           \"Lake\"           \n[17] \"Lassen\"          \"Los Angeles\"     \"Madera\"          \"Marin\"          \n[21] \"Mariposa\"        \"Mendocino\"       \"Merced\"          \"Modoc\"          \n[25] \"Mono\"            \"Monterey\"        \"Napa\"            \"Nevada\"         \n[29] \"Orange\"          \"Placer\"          \"Plumas\"          \"Riverside\"      \n[33] \"Sacramento\"      \"San Benito\"      \"San Bernardino\"  \"San Diego\"      \n[37] \"San Francisco\"   \"San Joaquin\"     \"San Luis Obispo\" \"San Mateo\"      \n[41] \"Santa Barbara\"   \"Santa Clara\"     \"Santa Cruz\"      \"Shasta\"         \n[45] \"Siskiyou\"        \"Solano\"          \"Sonoma\"          \"Stanislaus\"     \n[49] \"Sutter\"          \"Tehama\"          \"Trinity\"         \"Tulare\"         \n[53] \"Tuolumne\"        \"Ventura\"         \"Yolo\"            \"Yuba\"           \n```\n:::\n:::\n\n\nPerforming a basic linear model of Air Quality on Death Rate using this data reveals that there is almost no signal between the two.\nIn fact, there is a slightly negative beta coefficient for PM2.5 Days, and extremely low significance, with a P-value of nearly 60%, and an R squared of 0.0006.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(lm(data = airqualityanddeaths, `Deathsper100kheartlung` ~ `PM2.5 Days`))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Deathsper100kheartlung ~ `PM2.5 Days`, data = airqualityanddeaths)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-164.72  -49.89  -11.20   43.48  233.36 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  235.3998     3.7644  62.533   <2e-16 ***\n`PM2.5 Days`  -0.1033     0.1770  -0.584    0.559    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 75.2 on 607 degrees of freedom\nMultiple R-squared:  0.0005614,\tAdjusted R-squared:  -0.001085 \nF-statistic: 0.341 on 1 and 607 DF,  p-value: 0.5595\n```\n:::\n:::\n\n\nGraphing a scatter plot and the linear model shows a bit more detail about what is going on.\nAs you get down into the counties with low PM2.5 Days (i.e. better air quality), there is an extreme variance in the rate of deaths.\nAs a result, though there does seem to be slight positive visual trend as you get into the county-years with higher PM2.5 Days, the overall trend is inconclusive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nairqualityanddeaths %>% \n  ggplot(aes(x = `PM2.5 Days`, y = `Deathsper100kheartlung`)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  labs(title = \"PM2.5 Days vs CLD and HTD Deaths per 100k\",\n       subtitle = \"Across all County-Years, CA, 2000-2010\",\n       x = \"PM 2.5 Days\",\n       y = \"CLD and HTD Deaths per 100,000\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProject_JosephVincent_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nI believe that this is largely being driven including small rural counties in my model, which is doing two things:\n\n### 1. The Law of Small Numbers\n\nWhen the population for a county is small, small random changes in absolute deaths cause a large swing in the death rate for that county.\nThere are plenty of instances where deaths by heart or lung disease are in the single or low double digits.\n\n### 2. Social Determinants of Health\n\nSmaller counties do not compare well to larger counties on a number of factors, including access to healthcare, income, education status, type of employment, etc.\n\nIn similar analyses, researchers have accounted for this by calculating excess deaths.\nI am unable to do so with the available data and time constraints for this analysis.\n\n*Attempting to reduce OMB by adding variables related to social determinants of health into the model is not strong enough to correct for these errors.* This was also the case when attempting log or cubic models.\n\n## Selecting a Subset of Large, Metro Counties\n\nTherefore, I have opted to only perform an analysis on large, metropolitan counties.\nBy doing so, I can focus more on the impact of air quality directly on deaths by lung or heart disease instead of other hidden variables.\n\nI'm conscious that this is not the ideal approach, as it opens the door to sample selection bias; however, it will allow me to draw more meaningful conclusions about the affect of air quality in metropolitan counties until I can measure excess deaths in a more sophisticated manner.\n\n*In my analysis, therefore, I can only make claims about large metropolitan counties in California, not US or CA counties in general.*\n\nBelow, I have used RUCC to filter only for counties with a score of 1, which indicates that metropolitan areas of 1 million in population or more are at least partially within their boundaries.\n\nThis still leaves me with more than enough data to draw statistical inferences; 176 observations, including 16 unique counties across the 11 years.\n\nSee below for a list of unique counties included.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlargemetrocounties <- airqualityanddeaths %>%\n  filter(RUCC <= 1)\n\nnrow(largemetrocounties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 176\n```\n:::\n\n```{.r .cell-code}\nunique(largemetrocounties$County)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Alameda\"        \"Contra Costa\"   \"El Dorado\"      \"Los Angeles\"   \n [5] \"Marin\"          \"Orange\"         \"Placer\"         \"Riverside\"     \n [9] \"Sacramento\"     \"San Benito\"     \"San Bernardino\" \"San Diego\"     \n[13] \"San Francisco\"  \"San Mateo\"      \"Santa Clara\"    \"Yolo\"          \n```\n:::\n:::\n\n\n## Analysis\n\n## 1. Identifying My Model\n\n$$\nHeart and Lung Death Rate = \\beta_0 + PM2.5Days*\\beta_1 + OzoneDays*\\beta_2 + PowerPlantDensity*\\beta_3 + \\epsilon\n$$\n\nMy hypothesis is that air quality, specifically PM2.5 Days per year, will result in a higher rate of deaths by heart and lung causes in large metropolitan counties in California.\n\nWhile I believe PM2.5 Days will have a larger impact, Ozone Days are also a factor that should be included in my analysis.\nWhile these two are strongly correlated, Ozone and PM2.5 may have varying health impacts.\n\nFinally, I would like to try to account for Social Determinants of Health.\nThese are the conditions of a person's environment and lifestyle that impact their health outcomes.\nI want to select a measure of social determinants of health that reduced Omitted Variable Bias.\nTo do so, it needs to not only have a potential impact on heart and lung disease deaths, but also be correlated with air quality.\nTherefore, I have chosen the *density of power plants* per 1,000 square miles.\nPower plants are a leading polluter and contributor to poor air quality.\nSimultaneously, power plants tend to be located in poorer, less affluent neighborhoods.\nThus, *including power plants will allow me to test for whether what I am actually measuring are social determinants of health's impacts on rate of death by heart and lung disease.*\n\n## 2. Creating A Model Strategy to Ensure External and Internal Validity\n\n#### a. Summary of Data and b. Custom Variables\n\nMy composite data set consists of a few different groups of variables.\nI will explore means and SDs\n\nFirst are Year and County.\nEach observation in my data is a unique combination of the two.\n\nNext are the air quality data types.\nThese include PM2.5 Days and Ozone Days, but also some additional ways of measuring PM2.5 or Ozone which I will not explore further in this analysis.\n\nI have calculated death rate totals for CLD and HTD types, and combined those to produce a Death per 100k by Heart and Lung Disease variable.\n\nI've included county populations and square miles per county in order to create variables that are normalized.\nThese include my death rates, population density, and power plant density.\n\nFinally, I have a whole set of economic data (Median Income, Unemployment Rate, etc.) that I added to test various variables to determine the best social determinant of health.\nI will not explore these further here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(largemetrocounties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Year               County            Population        Ozone Days    \n Min.   :2000-01-01   Length:176         Min.   :  53781   Min.   :  0.00  \n 1st Qu.:2002-01-01   Class :character   1st Qu.: 252440   1st Qu.:  2.75  \n Median :2005-01-01   Mode  :character   Median :1141384   Median : 10.00  \n Mean   :2004-12-31                      Mean   :1712229   Mean   : 31.80  \n 3rd Qu.:2008-01-01                      3rd Qu.:1934820   3rd Qu.: 46.25  \n Max.   :2010-01-01                      Max.   :9830420   Max.   :125.00  \n Ozone Person Days     PM2.5 Days     PM2.5 Person Days   PM2.5 Percent of Days\n Min.   :0.000e+00   Min.   :  0.00   Min.   :        0   Min.   : 0.000       \n 1st Qu.:5.953e+05   1st Qu.:  4.00   1st Qu.:  1745962   1st Qu.: 1.096       \n Median :9.023e+06   Median : 10.97   Median :  9124978   Median : 3.005       \n Mean   :9.349e+07   Mean   : 16.87   Mean   : 47249901   Mean   : 4.623       \n 3rd Qu.:6.817e+07   3rd Qu.: 19.00   3rd Qu.: 34198875   3rd Qu.: 5.205       \n Max.   :1.084e+09   Max.   :117.00   Max.   :818212890   Max.   :32.055       \n PM2.5 Annual Average    sqmiles          Popdensity           Plants     \n Min.   : 0.00        Min.   :   47.0   Min.   :   38.72   Min.   :  0.0  \n 1st Qu.:10.67        1st Qu.:  733.2   1st Qu.:  196.16   1st Qu.:  6.5  \n Median :11.96        Median : 1152.5   Median : 1006.42   Median : 18.0  \n Mean   :13.46        Mean   : 2910.1   Mean   : 2026.27   Mean   : 30.0  \n 3rd Qu.:14.68        3rd Qu.: 2295.2   3rd Qu.: 1693.30   3rd Qu.: 38.5  \n Max.   :30.34        Max.   :20057.0   Max.   :17137.51   Max.   :103.0  \n Unemploymentrate medianrealincome      RUCC   Powerplantdensity\n Min.   : 2.800   Min.   : 52063   Min.   :1   Min.   :  0.000  \n 1st Qu.: 4.700   1st Qu.: 58359   1st Qu.:1   1st Qu.:  6.062  \n Median : 5.400   Median : 71932   Median :1   Median : 14.002  \n Mean   : 6.424   Mean   : 73156   Mean   :1   Mean   : 22.923  \n 3rd Qu.: 7.200   3rd Qu.: 83474   3rd Qu.:1   3rd Qu.: 22.466  \n Max.   :15.500   Max.   :107226   Max.   :1   Max.   :148.936  \n      CLD             HTD         Deathsper100kheartlung\n Min.   : 0.00   Min.   : 69.54   Min.   : 69.54        \n 1st Qu.:30.30   1st Qu.:149.67   1st Qu.:182.79        \n Median :35.05   Median :171.72   Median :206.04        \n Mean   :36.24   Mean   :169.31   Mean   :205.55        \n 3rd Qu.:41.26   3rd Qu.:194.44   3rd Qu.:230.44        \n Max.   :73.95   Max.   :249.26   Max.   :306.13        \n```\n:::\n:::\n\n\n#### c. Means and Standard Deviations of Regressors\n\nFind the means and standard deviations of my regressors in the table below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanandsd <- largemetrocounties %>%\n  summarise(MeanDeathsper100k = mean(`Deathsper100kheartlung`),\n            SDDeathsper100k = sd(`Deathsper100kheartlung`),\n            MeanPM2.5Days = mean(`PM2.5 Days`),\n            SDPM2.5Days = sd(`PM2.5 Days`),\n            MeanOzoneDays = mean(`Ozone Days`),\n            SDOzoneDays = sd(`Ozone Days`),\n            MeanPowerplantdensity = mean(`Powerplantdensity`),\n            SDPowerplantdensity = sd(`Powerplantdensity`))\nmeanandsd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 8\n  MeanDeathsper100k SDDeathspe…¹ MeanP…² SDPM2…³ MeanO…⁴ SDOzo…⁵ MeanP…⁶ SDPow…⁷\n              <dbl>        <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n1              206.         43.7    16.9    20.8    31.8    38.8    22.9    34.5\n# … with abbreviated variable names ¹​SDDeathsper100k, ²​MeanPM2.5Days,\n#   ³​SDPM2.5Days, ⁴​MeanOzoneDays, ⁵​SDOzoneDays, ⁶​MeanPowerplantdensity,\n#   ⁷​SDPowerplantdensity\n```\n:::\n:::\n\n\n#### d. Estimating a Simple Linear Model\n\nMy first basic linear model uses only PM2.5 Days as a regressor on Deaths per 100,000.\n\nSeen in the summary below, this is of itself a statistically significant relationship.\n\nThe coefficient on PM2.5 Days is .95.\nSuggesting that for each additional day of PM2.5 levels over the national average, counties will experience an additional .95 deaths per 100,000 for that year.\n\nThe p-value is extremely small (e-10).\n\nThe adjusted r-squared is just under .2, but this alone is not meaningful until compared with other models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplemod <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ `PM2.5 Days`)\nsummary(simplemod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Deathsper100kheartlung ~ `PM2.5 Days`, data = largemetrocounties)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-130.443  -17.874    0.427   19.526  110.114 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  189.5654     3.7996  49.891  < 2e-16 ***\n`PM2.5 Days`   0.9471     0.1421   6.664 3.37e-10 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 39.1 on 174 degrees of freedom\nMultiple R-squared:  0.2033,\tAdjusted R-squared:  0.1988 \nF-statistic: 44.41 on 1 and 174 DF,  p-value: 3.373e-10\n```\n:::\n:::\n\n\n#### e. Estimating a Simple LinearLog Regression\n\nI've estimated a simple linear-log regression below, to see if changes in PM2.5 Days measured as a percentage yield better results for a uni-variate model.\n\nAs you can see below, while still statistically significant, the adjusted R squared value has decreased to .13, suggesting it is a worse fit to my data than the linear model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplelogmod <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ log(`PM2.5 Days`+.1))\n\nsummary(simplelogmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Deathsper100kheartlung ~ log(`PM2.5 Days` + 0.1), \n    data = largemetrocounties)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-139.714  -17.141    1.317   19.800  114.558 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              185.112      4.974  37.216  < 2e-16 ***\nlog(`PM2.5 Days` + 0.1)   10.030      1.921   5.222 5.01e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 40.73 on 174 degrees of freedom\nMultiple R-squared:  0.1355,\tAdjusted R-squared:  0.1305 \nF-statistic: 27.27 on 1 and 174 DF,  p-value: 5.012e-07\n```\n:::\n:::\n\n\n#### g. Estimating a Simple Cubic Model\n\nWhen treating PM2.5 Days as a cubic variable, the adjusted R squared increases, at first suggesting that it may be a better fit.\n\nHowever, as seen below, the p-values on the coefficients, particularly for the squared and cubed orders have gotten much worse.\nPM2.5 Days squared has a 0.08 p-value, and PM2.5 Days cubed has a 0.13 p-value.\nGiven that these are several magnitudes worse than for my linear model, this does not give me a lot of confidence that a cubic model is the best fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplecubicmod <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + I(`PM2.5 Days`^3))\n\nsummary(simplecubicmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Deathsper100kheartlung ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + \n    I(`PM2.5 Days`^3), data = largemetrocounties)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-133.114  -17.442   -0.444   18.445  117.140 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        1.812e+02  5.766e+00  31.432  < 2e-16 ***\nI(`PM2.5 Days`)    2.295e+00  7.147e-01   3.211  0.00158 ** \nI(`PM2.5 Days`^2) -3.379e-02  1.922e-02  -1.758  0.08054 .  \nI(`PM2.5 Days`^3)  2.025e-04  1.331e-04   1.522  0.12984    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38.9 on 172 degrees of freedom\nMultiple R-squared:  0.2203,\tAdjusted R-squared:  0.2067 \nF-statistic:  16.2 on 3 and 172 DF,  p-value: 2.554e-09\n```\n:::\n:::\n\n\n#### h. Plotting Simple Linear, Log and Cubic Models\n\nI've plotted the three models below along with a scatter plot of PM2.5 Days against Deaths per 100,000.\n\nThe linear model is in blue, the log model is in green, and the cubic model is in red.\n\nIt's clear from this plot that there is a large concentration of county-years with lower PM2.5 Days, particularly less than 30.\nThere is a lot of variance in the data at this level and some heteroskedasticity, but this will be addressed further later on when I calculate robust standard errors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplemod_predict <- cbind(largemetrocounties, predict(simplemod, interval = 'confidence')) %>%\n  rename(\"fitlm\" = fit, \"lwrlm\" = lwr, \"uprlm\" = upr)\n\nsimplelogmod_predict <- cbind(simplemod_predict, predict(simplelogmod, interval = 'confidence')) %>%\n  rename(\"fitlog\" = fit, \"lwrlog\" = lwr, \"uprlog\" = upr)\n\nsimplecubicmod_predict <- cbind(simplelogmod_predict, predict(simplecubicmod, interval = 'confidence')) %>%\n  rename(\"fitcub\" = fit, \"lwrcub\" = lwr, \"uprcub\" = upr)\n\nsimplecubicmod_predict %>%\n  ggplot(aes(x = `PM2.5 Days`, y = `Deathsper100kheartlung`)) +\n  geom_point() +\n  geom_smooth(aes(x = `PM2.5 Days`, y = fitlm), col = \"blue\") +\n  geom_smooth(aes(x = `PM2.5 Days`, y = fitlog), col = \"green\") +\n  geom_smooth(aes(x = `PM2.5 Days`, y = fitcub), col = \"red\") +\n  labs(title = \"CLD and HTD Deaths per 100k ~ PM2.5 Days\",\n       subtitle = \"Large Metro County-Years, CA, 2000-2010\",\n       x = \"PM 2.5 Days\",\n       y = \"CLD and HTD Deaths per 100,000\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n`geom_smooth()` using method = 'loess' and formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](FinalProject_JosephVincent_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n## 3. Visual Analysis of Models\n\nThe log model (green) seems do a pretty good job below 30 days, but is probably the worst visual fit because it plateaus too soon, not accounting for the distinct increase in deaths as the highest PM2.5 Day levels are reached.\n\nWhen it comes to the linear (blue) and cubic (red) models, they are visually very closely matched.\nThere is perhaps a slight edge to the cubic model, given the small 'bump' around 30 days.\nThere is also a 'dip' towards the lower end of the data.\nIt's not clear to me whether this improves the model, due to the distinct spread of death rates at this point.\n\nOverall, I don't believe that the linear and cubic models are visually distinct enough to eliminate either entirely from contention.\n\nI will still include all models in further analysis to investigate further.\n\n## 4. Finding the Optimal Model\n\n#### a. Estimating Specifications for Uni-variate and Multivariate of Each Type\n\nI've created 3 models under each of the types previously identified (linear, log, and cubic).\n\nIn each, I've iteratively added the two additional regressors as previously identified: Ozone Days and Power Plant Density in an attempt to reduce OVB.\n\n#### Linear models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplelm <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ `PM2.5 Days`)\nmultlm1 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ `PM2.5 Days` + `Ozone Days`)\nmultlm2 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ `PM2.5 Days` + `Ozone Days` + `Powerplantdensity`)\n```\n:::\n\n\n#### Log Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplelog <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ log(`PM2.5 Days` + .1))\nmultlog1 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ log(`PM2.5 Days` + .1) + `Ozone Days`)\nmultlog2 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ log(`PM2.5 Days` + .1) + `Ozone Days` + `Powerplantdensity`)\n```\n:::\n\n\n#### Cubic Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimplecub <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + I(`PM2.5 Days`^3))\nmultcub1 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + I(`PM2.5 Days`^3) + `Ozone Days`)\nmultcub2 <- lm(data = largemetrocounties, `Deathsper100kheartlung` ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + I(`PM2.5 Days`^3) + `Ozone Days` + `Powerplantdensity`)\n```\n:::\n\n\n#### Calculating Robust Standard Errors\n\nI've calculated robust standard errors for each model.\nDoing so allows me to account for the heteroskedasticity apparent in the data, with their being a higher variance in death rate for county-years with lower PM2.5 Days.\nThis will allow me to compare models while maintaining the OLS assumptions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrob_se <- list(sqrt(diag(vcovHC(simplelm, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multlm1, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multlm2, type = \"HC1\"))),\n                sqrt(diag(vcovHC(simplelog, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multlog1, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multlog2, type = \"HC1\"))),\n                sqrt(diag(vcovHC(simplecub, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multcub1, type = \"HC1\"))),\n                sqrt(diag(vcovHC(multcub2, type = \"HC1\"))))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodlist <- list(simplelm, multlm1, multlm2, simplelog, multlog1, multlog2, simplecub, multcub1, multcub2)\n```\n:::\n\n\n### Reporting in Stargazer\n\nSee below for a detailed report of the models.\nI will discuss these results further in the conclusion section.\n\n\n\n```{.r .cell-code}\nsuppressWarnings(stargazer(modlist,\n          title = \"Linear Regressions Using CA Air Quality and Deaths by Cause Data\",\n          type = \"html\",\n          se = rob_se,\n          digits = 3,\n          header = FALSE,\n          object.names = TRUE,\n          model.numbers = FALSE,\n          column.labels = c(\"simplelm\", \"multlm1\", \"multlm2\", \"simplelog\", \"multlog1\", \"multlog2\", \"simplecub\", \"multcub1\", \"multcub2\"),\n          model.names = FALSE))\n```\n\n\n<table style=\"text-align:center\"><caption><strong>Linear Regressions Using CA Air Quality and Deaths by Cause Data</strong></caption>\n<tr><td colspan=\"10\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td colspan=\"9\"><em>Dependent variable:</em></td></tr>\n<tr><td></td><td colspan=\"9\" style=\"border-bottom: 1px solid black\"></td></tr>\n<tr><td style=\"text-align:left\"></td><td colspan=\"9\">Deathsper100kheartlung</td></tr>\n<tr><td style=\"text-align:left\"></td><td>simplelm</td><td>multlm1</td><td>multlm2</td><td>simplelog</td><td>multlog1</td><td>multlog2</td><td>simplecub</td><td>multcub1</td><td>multcub2</td></tr>\n<tr><td style=\"text-align:left\"></td><td>modlist</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td><td>NA</td></tr>\n<tr><td colspan=\"10\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">`PM2.5 Days`</td><td>0.947<sup>***</sup></td><td>0.649<sup>***</sup></td><td>0.592<sup>***</sup></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.102)</td><td>(0.127)</td><td>(0.127)</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">`Ozone Days`</td><td></td><td>0.249<sup>***</sup></td><td>0.339<sup>***</sup></td><td></td><td>0.356<sup>***</sup></td><td>0.444<sup>***</sup></td><td></td><td>0.252<sup>***</sup></td><td>0.343<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td>(0.068)</td><td>(0.072)</td><td></td><td>(0.072)</td><td>(0.076)</td><td></td><td>(0.071)</td><td>(0.075)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Powerplantdensity</td><td></td><td></td><td>0.333<sup>***</sup></td><td></td><td></td><td>0.332<sup>***</sup></td><td></td><td></td><td>0.330<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td>(0.072)</td><td></td><td></td><td>(0.070)</td><td></td><td></td><td>(0.069)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">log(`PM2.5 Days` + 0.1)</td><td></td><td></td><td></td><td>10.030<sup>***</sup></td><td>5.959<sup>***</sup></td><td>5.044<sup>**</sup></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td>(2.026)</td><td>(2.131)</td><td>(2.158)</td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(`PM2.5 Days`)</td><td></td><td></td><td></td><td></td><td></td><td></td><td>2.295<sup>***</sup></td><td>1.998<sup>***</sup></td><td>1.875<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td>(0.641)</td><td>(0.650)</td><td>(0.641)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(`PM2.5 Days`2)</td><td></td><td></td><td></td><td></td><td></td><td></td><td>-0.034<sup>**</sup></td><td>-0.036<sup>**</sup></td><td>-0.035<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td>(0.015)</td><td>(0.015)</td><td>(0.015)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">I(`PM2.5 Days`3)</td><td></td><td></td><td></td><td></td><td></td><td></td><td>0.0002<sup>**</sup></td><td>0.0002<sup>***</sup></td><td>0.0002<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td>(0.0001)</td><td>(0.0001)</td><td>(0.0001)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>189.565<sup>***</sup></td><td>186.675<sup>***</sup></td><td>177.131<sup>***</sup></td><td>185.112<sup>***</sup></td><td>182.099<sup>***</sup></td><td>173.560<sup>***</sup></td><td>181.225<sup>***</sup></td><td>178.656<sup>***</sup></td><td>169.684<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(3.924)</td><td>(4.049)</td><td>(5.035)</td><td>(5.500)</td><td>(5.163)</td><td>(6.013)</td><td>(5.890)</td><td>(5.874)</td><td>(6.667)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>\n<tr><td colspan=\"10\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>176</td><td>176</td><td>176</td><td>176</td><td>176</td><td>176</td><td>176</td><td>176</td><td>176</td></tr>\n<tr><td style=\"text-align:left\">R<sup>2</sup></td><td>0.203</td><td>0.232</td><td>0.297</td><td>0.135</td><td>0.213</td><td>0.277</td><td>0.220</td><td>0.249</td><td>0.313</td></tr>\n<tr><td style=\"text-align:left\">Adjusted R<sup>2</sup></td><td>0.199</td><td>0.223</td><td>0.285</td><td>0.131</td><td>0.204</td><td>0.264</td><td>0.207</td><td>0.232</td><td>0.292</td></tr>\n<tr><td style=\"text-align:left\">Residual Std. Error</td><td>39.099 (df = 174)</td><td>38.493 (df = 173)</td><td>36.941 (df = 172)</td><td>40.730 (df = 174)</td><td>38.969 (df = 173)</td><td>37.468 (df = 172)</td><td>38.905 (df = 172)</td><td>38.285 (df = 171)</td><td>36.741 (df = 170)</td></tr>\n<tr><td style=\"text-align:left\">F Statistic</td><td>44.414<sup>***</sup> (df = 1; 174)</td><td>26.170<sup>***</sup> (df = 2; 173)</td><td>24.225<sup>***</sup> (df = 3; 172)</td><td>27.268<sup>***</sup> (df = 1; 174)</td><td>23.433<sup>***</sup> (df = 2; 173)</td><td>21.945<sup>***</sup> (df = 3; 172)</td><td>16.200<sup>***</sup> (df = 3; 172)</td><td>14.198<sup>***</sup> (df = 4; 171)</td><td>15.470<sup>***</sup> (df = 5; 170)</td></tr>\n<tr><td colspan=\"10\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td colspan=\"9\" style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n\n\n#### d. Linear Hypothesis Tests\n\nNext, I will perform linear hypothesis tests for each model.\nThis ensures that the relationship between air quality and death rate is statistically significant for each model.\n\nAs can be seen below, the F-statistic for all of the models are statistically significant, with p-values well below even 0.1.\n\n#### Simple Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(simplelm, \n                   \"`PM2.5 Days` = 0\", \n                   vcov. = vcovHC(simplelm, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nPM2.5 Days` = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ `PM2.5 Days`\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    174  1 86.165 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Linear Model 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multlm1, \n                   c(\"`PM2.5 Days` = 0\", \"`Ozone Days` = 0\"),\n                   vcov. = vcovHC(multlm1, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nPM2.5 Days` = 0\nOzone Days` = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ `PM2.5 Days` + `Ozone Days`\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    173  2 50.717 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Linear Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multlm2, \n                   c(\"`PM2.5 Days` = 0\", \"`Ozone Days` = 0\", \"Powerplantdensity = 0\"),\n                   vcov. = vcovHC(multlm2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nPM2.5 Days` = 0\nOzone Days` = 0\nPowerplantdensity = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ `PM2.5 Days` + `Ozone Days` + Powerplantdensity\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    172  3 35.417 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Simple Log Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(simplelog, \n                   \"log(`PM2.5 Days` + 0.1) = 0\",\n                   vcov. = vcovHC(simplelog, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nlog(`PM2.5 Days` + 0.1) = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ log(`PM2.5 Days` + 0.1)\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    174  1 24.502 1.744e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Log Model 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multlog1, \n                   c(\"log(`PM2.5 Days` + 0.1) = 0\", \"`Ozone Days` = 0\"),\n                   vcov. = vcovHC(multlog1, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nlog(`PM2.5 Days` + 0.1) = 0\nOzone Days` = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ log(`PM2.5 Days` + 0.1) + `Ozone Days`\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df     F    Pr(>F)    \n1    175                       \n2    173  2 32.24 1.257e-12 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Log Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multlog2, \n                   c(\"log(`PM2.5 Days` + 0.1) = 0\", \"`Ozone Days` = 0\", \"Powerplantdensity = 0\"),\n                   vcov. = vcovHC(multlog2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nlog(`PM2.5 Days` + 0.1) = 0\nOzone Days` = 0\nPowerplantdensity = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ log(`PM2.5 Days` + 0.1) + `Ozone Days` + \n    Powerplantdensity\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df     F    Pr(>F)    \n1    175                       \n2    172  3 24.01 4.986e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Simple Cubic Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(simplecub, \n                   c(\"I(`PM2.5 Days`)  = 0\", \"I(`PM2.5 Days`^2) = 0\", \"I(`PM2.5 Days`^3) = 0\"),\n                   vcov. = vcovHC(simplecub, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nI(`PM2.5 Days`) = 0\nI(`PM2.5 Days`^2) = 0\nI(`PM2.5 Days`^3) = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + \n    I(`PM2.5 Days`^3)\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    172  3 33.367 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Cubic Model 1\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multcub1, \n                   c(\"I(`PM2.5 Days`)  = 0\", \"I(`PM2.5 Days`^2) = 0\", \"I(`PM2.5 Days`^3) = 0\", \"`Ozone Days` = 0\"),\n                   vcov. = vcovHC(multcub1, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nI(`PM2.5 Days`) = 0\nI(`PM2.5 Days`^2) = 0\nI(`PM2.5 Days`^3) = 0\nOzone Days` = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + \n    I(`PM2.5 Days`^3) + `Ozone Days`\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    171  4 28.326 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### Multiple Cubic Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinearHypothesis(multcub2, \n                   c(\"I(`PM2.5 Days`)  = 0\", \"I(`PM2.5 Days`^2) = 0\", \"I(`PM2.5 Days`^3) = 0\", \"`Ozone Days` = 0\", \"Powerplantdensity = 0\"),\n                   vcov. = vcovHC(multcub2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear hypothesis test\n\nHypothesis:\nI(`PM2.5 Days`) = 0\nI(`PM2.5 Days`^2) = 0\nI(`PM2.5 Days`^3) = 0\nOzone Days` = 0\nPowerplantdensity = 0\n\nModel 1: restricted model\nModel 2: Deathsper100kheartlung ~ I(`PM2.5 Days`) + I(`PM2.5 Days`^2) + \n    I(`PM2.5 Days`^3) + `Ozone Days` + Powerplantdensity\n\nNote: Coefficient covariance matrix supplied.\n\n  Res.Df Df      F    Pr(>F)    \n1    175                        \n2    170  5 24.417 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n## 5. Selecting the Optimal Model\n\nI believe that the multiple linear model, including PM2.5 Days, Ozone Days and Power Plant Density best explains the relationship between PM2.5 Days and the rate of deaths caused by heart and lung diseases.\n\n$$\nHeart and Lung Death Rate = \\beta_0 + PM2.5Days*\\beta_1 + OzoneDays*\\beta_2 + PowerPlantDensity*\\beta_3 + \\epsilon\n$$\n\n**As seen from calculating the F-statistics, in each case, we can reject the null hypothesis that there is no relationship between PM2.5 Days and the rate of deaths of heart and lung diseases in large metropolitan counties.**\n\nIn order to select the optimal model for explaining this relationship, I took a number of steps:\n\nFirst, I used the **visual analysis** of simple models to identify that a **linear or cubic model** were the most likely candidates for explaining the relationship, as discussed in section 1.g.\n\n#### The Multivariate Model Reduces OVB\n\nNext, I began including additional variables in my models to see how they affected model fit and their impact on the Beta1 coefficient.\nI will use the case of the linear model below as an example:\n\n-   In the simple linear model, PM2.5 Days had a coefficient of 0.95, with a p-value of well below 0.1%.\n\n-   After adding Ozone Days as a regressor, the coefficient on PM2.5 Days decreased by around 30% to 0.65.\n    Ozone Days had a coefficient of 0.25.\n    Both remained statistically significant at the 0.1% level.\n\n-   Finally, when adding Power Plant Density into the regression model, the coefficient on PM2.5 Days decreased by an additional 10% (0.59), with Ozone Days and Power Plant Density both at around 0.33.\n    All of these were statistically significant at the 0.1% level.\n\n**Because adding these additional variables reduced the coefficient on PM2.5 Days by considerable margins, and all variables remained statistically significant, it's safe to assume that adding these variables reduced omitted variable bias, and multi-colinearity was not present. Additionally, the adjusted R squared value increased in each case, suggesting that each subsequent model better fit the data.**\n\n#### The Multi-Linear Model is Extremely Significant and Easy to Interpret\n\nBased on adjusted R squared alone, which indicates how well the model fits the data, the cubic model with additional regressors of Ozone Days and Power Plant Density (0.292) is slightly superior to the multivariate linear model (0.285) - but these are very close and do not tell the entire story.\n\nWhen we look at the significance levels of the individual coefficients for the squared and cubic orders of PM2.5 Days, we see a marked decrease in p-values, both only signficant at the 10% level vs 0.1% level for all variables in the linear model.\n\nFinally, the F-statistic, though significant, is considerably lower in the cubic model (15) than in the linear model (24).\n\nBecause of all of these factors, and because the linear model is easier to interpret, I have decided that the multi-linear model best explains this relationship.\n\n**In summary, for each additional day of PM2.5 levels over the NAAQS national average, an additional 0.59 deaths per 100,000 of heart and lung causes occur in large metropolitan counties, while holding Ozone Days and Social Determinants of Health constant. To put this into perspective, if Los Angeles county (9.8 million population) were to experience an additional 10 PM2.5 Days in a calendar year, my model estimates they could expect roughly an additional 60 deaths by lung and heart causes.**\n\n### **Bibliography**\n\n\\[1\\] Kurt, O. K., Zhang, J., & Pinkerton, K. E.\n(2016).\nPulmonary health effects of air pollution.\n*Current opinion in pulmonary medicine*, *22*(2), 138--143.\nhttps://doi.org/10.1097/MCP.0000000000000248\n\n\\[2\\] Jonathan J Buonocore *et al* (2023) Air pollution and health impacts of oil & gas production in the United States *Environ. Res.: Health* **1** 021006.\nhttps://iopscience.iop.org/article/10.1088/2752-5309/acc886\n\n\\[3\\] Centers for Disease Control and Prevention (2018).\n*Air Quality Measures on the National Environmental Health Tracking Network, 1999 - 2013,* \\[https://data.cdc.gov/Environmental-Health-Toxicology/Air-Quality-Measures-on-the-National-Environmental/cjae-szjv\\].\n\n\\[4\\] California Health and Human Services (2021).\n*1999-2013 Final Deaths by Year by County*,\\[https://data.chhs.ca.gov/dataset/death-profiles-by-county/resource/e692e6a1-bddd-48ab-a0c8-fa0f1f43e9f4?i\n%20nner_span=True\\].\n\n\\[5\\] United States Census Bureau (2021).\n*County Intercensal Tables: 2000-2010*,\\[https://www.census.gov/data/tables/time-series/demo/popest/intercensal-2000-2010-counties.html\\].\n\n\\[6\\] U.S.\nEnergy Information Administration (2023).\n*Form EIA-860*, \\[https://www.eia.gov/electricity/data/eia860/\\]\n\n\\[7\\] Economic Research Service of the US Department of Agriculture (2023).\n\\[https://www.ers.usda.gov/\\]\n\n\\[8\\] R Core Team (2022).\nR: A language and environment for statistical computing.\nR Foundation for Statistical Computing, Vienna, Austria.\nURL https://www.R-project.org/.\n\n\\[9\\] Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019).\n\"Welcome to the tidyverse.\" \\_Journal of Open Source Software\\_, \\*4\\*(43), 1686.\ndoi:10.21105/joss.01686 \\<https://doi.org/10.21105/joss.01686\\>.\n\n\\[10\\] Fox J, Weisberg S (2019).\n\\_An R Companion to Applied Regression\\_, Third edition.\nSage, Thousand Oaks CA.\n\\<https://socialsciences.mcmaster.ca/jfox/Books/Companion/\\>.\n\n\\[11\\] Hlavac, Marek (2022).\nstargazer: Well-Formatted Regression and Summary Statistics Tables.\nR package version 5.2.3.\nhttps://CRAN.R-project.org/package=stargazer\n",
    "supporting": [
      "FinalProject_JosephVincent_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}